graphql-hive/console

packages/web/app/pages/_document.tsx, packages/web/app/src/components/v2/tabs.tsx, packages/web/app/src/lib/hooks/use-clipboard.ts
fixes https://github.com/kamilkisiela/graphql-hive/issues/64
could reproduce and fix in Safari
1. 
2.
=> fix copy to clipboard and tabs styles in Safari

packages/web/app/tsconfig.json
Enables the TypeScript strict mode rules that require no additional code adjustments.
Please first merge https://github.com/kamilkisiela/graphql-hive/pull/82 - then rebase this branch upon origin/main and change the target branch to main.
=> chore: enable TypeScript flags noImplicitThis, strictBindCallApply and alwaysStrict for @hive/app

.eslintrc.cjs, package.json, packages/services/api/package.json, packages/services/cdn-worker/package.json, packages/services/cdn-worker/src/dev-polyfill.ts, packages/services/rate-limit/package.json, packages/services/schema/package.json, packages/services/server/package.json, packages/services/service-common/package.json, packages/services/storage/docker-compose.yml, packages/services/storage/package.json, packages/services/storage/src/index.ts, packages/services/stripe-billing/package.json, packages/services/tokens/package.json, packages/services/usage-common/package.json, packages/services/usage-estimator/package.json, packages/services/usage-ingestor/package.json, packages/services/usage/package.json, packages/services/webhooks/package.json, packages/web/app/package.json, packages/web/app/src/components/v2/header.tsx, packages/web/app/src/components/v2/toggle-group.tsx, packages/web/docs/package.json, packages/web/landing-page/package.json, rules/enforce-deps-in-dev.cjs, rules/index.cjs, rules/package.json, yarn.lock
Why?  Few reasons:
- tsup treats dependencies as external code and does not bundle them
- without dependencies turborepo will always serve stale code when some of dependencies changed
Moving internal dependencies to devDependencies makes tsup treat them as non-external and turborepo still keep tracks of relations
=> Fix missing dependencies between packages

packages/services/api/src/modules/shared/providers/storage.ts, packages/services/rate-limit/src/api.ts, packages/services/rate-limit/src/limiter.ts, packages/services/rate-limit/src/metrics.ts, packages/services/storage/src/index.ts, packages/services/usage/src/index.ts, packages/services/usage/src/metrics.ts, packages/web/app/src/graphql/fragments.graphql
=> Refactor rate-limit to support multi-targets orgs

packages/services/api/src/modules/project/resolvers.ts
Validation logic of the git repository field in the project's settings expected an URL instead of the `owner/name` format
=> Fix validation of git repository identifier

packages/services/storage/package.json, packages/web/app/src/components/admin/AdminStats.tsx, packages/web/app/src/components/target/operations/List.tsx
Combining react-window with react-table and chakra-ui is too weird... 
The goal is to improve the performance of the table and pagination works just fine.
=> Use paginated table in Admin Stats

packages/services/server/src/graphql-handler.ts
Our CLI sent a header with a typo.
We'll support both for the next 30 days or more to collect the correct versions.
After that, we will drop the header and use `SchemaPublishMissingServiceError` in the `schemaPublish` mutation by default.
Related #140
=> Temporarily support graphql-client-vesion header

packages/services/cdn-worker/src/handler.ts
Without the `await` statement `!Promise` is always cast to true. We actually want to check the value the Promise resolves to.
=> fix: await the promise

.changeset/strong-pandas-brake.md, integration-tests/docker-compose.yml, integration-tests/dockest.ts, integration-tests/testkit/flow.ts, integration-tests/tests/api/schema/publish.spec.ts, integration-tests/tests/api/target/usage.spec.ts, package.json, packages/libraries/cli/src/commands/schema/publish.graphql, packages/libraries/cli/src/commands/schema/publish.ts, packages/libraries/client/src/version.ts, packages/services/api/src/modules/schema/module.graphql.ts, packages/services/api/src/modules/schema/providers/schema-manager.ts, packages/services/api/src/modules/schema/providers/schema-publisher.ts, packages/services/api/src/modules/schema/resolvers.ts, packages/services/api/src/modules/shared/providers/storage.ts, packages/services/storage/src/index.ts, yarn.lock
- Removes the uniqueness requirement of commit it
- Makes the logic of schema publishing simpler and more readable
- Updating the service url results in a new version (previously na update of existing version)
- Introduces a requirement of defining service url in federated projects (new `SchemaPublishMissingUrlError` type)
=> Simplify the schema publishing logic

.changeset/strong-pandas-brake.md, integration-tests/tests/cli/schema.spec.ts, packages/libraries/cli/src/commands/schema/publish.graphql, packages/libraries/cli/src/commands/schema/publish.ts
This PR adds a dedicated error message with instructions when a service URL is missing (federated projects) thanks to the recently added `SchemaPublishMissingUrlError` type.
=> Support SchemaPublishMissingUrlError in CLI

packages/services/usage/src/validation.ts
Currently, we pass any number and it may crash the report at some point.
=> Validate the timestamp field in the usage report

packages/services/api/src/modules/rate-limit/providers/rate-limit.provider.ts
Because of error masking, user would see `Unexpected error` in CLI.
=> Show rate limit error to the user

integration-tests/scripts/pack.mjs
The script had weird side-effects depending on the path of your local hive repository as it replaced `hive-` within it. With this change only the filename is replaced.
=> chore: only mess with the filename not the path

packages/services/api/package.json, packages/services/api/src/modules/alerts/providers/adapters/common.ts, packages/services/api/src/modules/alerts/providers/adapters/webhook.ts, packages/services/api/src/modules/feedback/resolvers.ts, packages/services/api/src/modules/schema/providers/orchestrators/federation.ts, packages/services/api/src/modules/schema/providers/orchestrators/single.ts, packages/services/api/src/modules/schema/providers/orchestrators/stitching.ts, packages/services/api/src/modules/schema/providers/schema-publisher.ts, packages/services/api/src/modules/shared/providers/http-client.ts, packages/services/api/src/modules/shared/providers/tracking.ts, packages/services/api/src/modules/token/providers/token-storage.ts, packages/services/api/src/shared/sentry.ts, packages/services/schema/src/index.ts, packages/services/schema/src/orchestrators.ts, packages/services/server/package.json, packages/services/server/src/graphql-handler.ts, packages/services/server/src/index.ts, packages/services/service-common/src/errors.ts, packages/services/service-common/src/fastify.ts, packages/services/service-common/src/metrics.ts, packages/services/storage/src/db/sentry.ts, packages/services/tokens/src/index.ts, packages/services/webhooks/package.json, packages/services/webhooks/src/api.ts, packages/services/webhooks/src/index.ts, packages/services/webhooks/src/jobs.ts, packages/services/webhooks/src/scheduler.ts, packages/services/webhooks/src/types.ts, tsconfig.json
- No Sentry reporting for GraphQLErrors
- [No more debugging of that sentry issue](https://github.com/kamilkisiela/graphql-hive/commit/e7122b235310d0b9ca07d02931eafafee30926cc)
- Passes x-request-id to tRPC and uses `fastifyRequest.log` for logging (that extracts x-request-id and shows it in the log message)
=> Pass x-request-id to tRPC

integration-tests/docker-compose.yml, integration-tests/testkit/flow.ts, integration-tests/tests/api/schema/publish.spec.ts, integration-tests/tests/cli/schema.spec.ts, packages/libraries/cli/src/commands/schema/publish.graphql, packages/libraries/cli/src/commands/schema/publish.ts, packages/services/api/src/create.ts, packages/services/api/src/modules/schema/module.graphql.ts, packages/services/api/src/modules/schema/providers/config.ts, packages/services/api/src/modules/schema/providers/schema-publisher.ts, packages/services/server/src/index.ts
Related #185
When using CLI and publishing the first schema, the user will see:
> Available at https://app.graphql-hive.com/org/proj/tar
When publishing the second schema, the user will see:
> Available at https://app.graphql-hive.com/org/proj/tar/history/new-version-id
=> Expose link to website when publishing schema in GraphQL API

integration-tests/tests/api/schema/publish.spec.ts, integration-tests/tests/cli/schema.spec.ts, packages/services/server/src/graphql-handler.ts
This proves that the allegation made in https://github.com/kamilkisiela/graphql-hive/issues/188 is incorrect. Error masking does not mask `GraphQLYogaError` instances.
_____
Closes https://github.com/kamilkisiela/graphql-hive/issues/188
Closes https://github.com/kamilkisiela/graphql-hive/issues/189
=> test: prove error masking works as expected and always do error masking

.changeset/little-dingos-exercise.md, .changeset/quiet-dogs-flow.md, .prettierignore, integration-tests/dockest.ts, integration-tests/fixtures/init-invalid-schema.graphql, integration-tests/tests/cli/schema.spec.ts, packages/libraries/cli/src/commands/schema/publish.ts, packages/services/api/src/modules/schema/providers/schema-publisher.ts, packages/services/api/src/modules/schema/providers/schema-validator.ts, packages/services/api/src/shared/entities.ts, packages/services/server/src/graphql-handler.ts
In persuit of figuring out what causes https://github.com/kamilkisiela/graphql-hive/issues/188 I realized that the actual issue [for my test here](https://github.com/kamilkisiela/graphql-hive/pull/201#issuecomment-1169651610) is that the `GraphQLError` thrown from `parse` within our business logic causes the `unexpected error.`. This PR resolves that by wrapping the logic and rethrowing the error.
Note that this is probably still not a fix for the error mentioned in https://github.com/kamilkisiela/graphql-hive/issues/187, as the CLI would have failed before doing any API requests, because it is also using `parse` and `print`.
- Always log unexpected errors to the console, even in dev mode
- Catch `GraphQLError` raised by `parse` and format it into a more obvious error message for both the …
=> feat: always log unexpected errors

integration-tests/testkit/flow.ts, integration-tests/tests/api/target/usage.spec.ts, packages/services/api/src/modules/operations/module.graphql.ts, packages/services/api/src/modules/operations/providers/operations-manager.ts, packages/services/api/src/modules/operations/providers/operations-reader.ts, packages/services/api/src/modules/operations/resolvers.ts, packages/services/api/src/modules/schema/providers/inspector.ts, packages/services/api/src/modules/target/module.graphql.ts, packages/services/api/src/modules/target/providers/target-manager.ts, packages/services/api/src/modules/target/resolvers.ts, packages/services/api/src/shared/entities.ts, packages/services/storage/migrations/actions/2022.07.18T10.10.44.target-validation-client-exclusion.sql, packages/services/storage/migrations/actions/down/2022.07.18T10.10.44.target-validation-client-exclusion.sql, packages/services/storage/src/db/types.ts, packages/services/storage/src/index.ts, packages/services/usage-ingestor/__tests__/serializer.spec.ts, packages/services/usage-ingestor/package.json, packages/services/usage-ingestor/src/serializer.ts, packages/web/app/package.json, packages/web/app/pages/[orgId]/[projectId]/[targetId]/settings.tsx, packages/web/app/src/components/v2/combobox.tsx, packages/web/app/src/graphql/fragments.graphql, yarn.lock
What it is, and what it does?
Let's take GraphQL Hive as an example. 
Whenever we make breaking changes in GraphQL API, Hive detects them and prevent the PR from being merged.
That's fine but sometimes we do a breaking change that does not affect anyone because a removed/modified field is requested only by `@hive/app` (app.graphql-hive.com). We know it's not breaking but Hive does not.
This PR lets us define a list of GraphQL consumers (clients) like app.graphql-hive.com so that Hive knows they won't be affected by any breaking changes (`@hive/server` is deployed together with `@hive/app`).
Perfect example: https://github.com/kamilkisiela/graphql-hive/pull/241/checks?check_run_id=7340193063
This should be useful for many users.
Todo
=> Client exclusions in breaking change detection

packages/services/storage/docker-compose.yml
Currently the `postgres` container fails its docker healthcheck because the `POSTGRES_DB` isn't set, so the `pg_isready ...` command fails.
```bash
$ yarn workspace @hive/storage run db:start
...
$ docker ps --format "table {{.ID}}\t{{.Image}}\t{{.Status}}"
CONTAINER ID   IMAGE                                          STATUS
127d3df6ceac   confluentinc/cp-kafka:7.1.1-1-ubi8.amd64       Up 6 minutes (healthy)
b4605846c7fd   clickhouse/clickhouse-server:22.3.5.5-alpine   Up 6 minutes (healthy)
fe839cb9d5a4   confluentinc/cp-zookeeper:7.1.1-1-ubi8.amd64   Up 6 minutes
43af8004ae9e   postgres:13.4-alpine                           Up 6 minutes (unhealthy)
1b7e56e86242   bitnami/redis:6.2                              Up 6 minutes (healthy)
```
=> fix postgres container healthcheck

packages/web/app/pages/_app.tsx, packages/web/app/pages/index.tsx
Now it includes a checksum, if it's a different session, it won't use the cookie.
The format is the following: `${cleanId}:${checksum}` where the checksum is specific to the user's session.
Few rules:
- Cookie is not used when the checksum does not match the user's session.
- Cookie is not updated/used when it's in the legacy format (we used to store just the `cleanId`).
- Cookies in the legacy format are replaced with the new format.
- If loading an organization fails, the cookie is removed.
This way a user won't end up in a situation where the cookie tells him/her to visit the wrong organization.
=> Fix last visited org cookie

packages/services/api/src/modules/shared/providers/storage.ts, packages/services/api/src/shared/entities.ts, packages/services/server/src/index.ts, packages/services/storage/src/index.ts, packages/web/app/src/config/backend-config.ts
Currently, the password of accounts that have not been migrated from Auth0 to SuperTokens (via a login) cannot be recovered.
This PR solves this by applying the following flow upon a password reset:
- Check if user exists in our database but not within supertokens
- If he does not exist in supertokens, create an supertokens user with a random password
- Continue the flow as usual
=> feat: import auth0 accounts into supertokens when doing a password reset

.github/workflows/ci.yaml
pull requests from public forks won't have access to `${{ secrets.HIVE_TOKEN }}`, so skip the `schema-check` job since they won't pass ([example run](https://github.com/kamilkisiela/graphql-hive/actions/runs/3061843689/jobs/4942159792#step:7:30)).
=> ci: skip schema-check if hive token isn't available

packages/libraries/client/src/apollo.ts, packages/libraries/client/src/gateways.ts, packages/libraries/client/tests/apollo.spec.ts, packages/libraries/client/tests/gateways.spec.ts, packages/services/cdn-worker/src/handler.ts, packages/services/cdn-worker/tests/cdn.spec.ts, packages/web/docs/pages/features/registry-usage.mdx
1. A GET request to CDN -> http response with data and ETag header (OK 200)
1. A GET request to CDN with If-None-Match: <etag> -> http response with no data (Not Modified 304)
1. A GET request to CDN with If-None-Match: <etag> -> http response with no data (Not Modified 304)
1. CDN state changes and previously fetched data becomes stale
1. A GET request to CDN with If-None-Match: <etag> -> http response with new data and ETag header (OK 200)
1. A GET request to CDN with If-None-Match: <new-etag> -> http response with no data (Not Modified 304)
Closes #414
=> Use ETag and If-None-Match in CDN and clients

.changeset/fuzzy-plants-crash.md, packages/libraries/client/README.md, packages/libraries/client/src/client.ts, packages/libraries/client/src/internal/operations-store.ts, packages/libraries/client/src/internal/reporting.ts, packages/libraries/client/src/internal/types.ts, packages/libraries/client/src/internal/usage.ts, packages/libraries/client/tests/info.spec.ts, packages/libraries/client/tests/reporting.spec.ts, packages/libraries/client/tests/usage.spec.ts
```diff
{
usage: {
-    endpoint: 'https://api.com/usage'
},
reporting: {
-    endpoint: 'https://api.com/graphql'
},
+  selfHosting: {
+    graphqlEndpoint: 'https://api.com/graphql',
+    applicationUrl: 'https://app.com',
+    usageEndpoint: 'https://api.com/usage',
+  }
}
```
This way everything that's related to GraphQL Hive Cloud can be replaced, the links, the endpoints, token info, everything.
=> Add self-hosting options to GraphQL Hive client

packages/web/app/next.config.mts, packages/web/docs/next.config.mjs, packages/web/landing-page/next.config.js
=> Minor security adjustments to NextJS apps

.github/workflows/ci.yaml, packages/libraries/client/package.json, packages/services/api/package.json, packages/services/server/package.json, yarn.lock
we already were using this version from canary releases now just moves to use to a `alpha` release
=> update to next yoga version

deployment/index.ts, deployment/package.json, deployment/services/cloudflare-security.ts, deployment/services/cloudflare.ts, deployment/services/police.ts, deployment/utils/police.ts, deployment/yarn.lock, packages/web/app/pages/_document.tsx, packages/web/app/src/components/common/Navigation.tsx
=> Fixes for CSP on Safari, made hostname inference dynamic, remove headway scripts, update and adjust `@pulumi/cloudflare` setting to use latest version

.changeset/slow-pets-scream.md, packages/libraries/client/src/internal/usage.ts, packages/libraries/client/tests/usage-collector.spec.ts, packages/web/app/src/components/target/explorer/common.tsx, packages/web/app/src/components/target/explorer/input-object-type.tsx
Fix for the case when an optional variable is not provided
=> (processVariables: true) do not collect input if variable is missing

docs/ARCHITECTURE.md, docs/architecture.puml
Adds a design diagram.
I verified the link works on the fork, it should work after it merges:
=> Architecture Diagram

.changeset/famous-readers-cheat.md, packages/libraries/client/src/gateways.ts
We found that when a service doesn't set an explicit service URL, which seems to be valid state, the fetcher fails when it tries to create the hash since you can't give `null` into a Node.js crypto hash
screenshot of reference:
cc @saihaj @kamilkisiela
=> Fix createServicesFetcher handle null service url

.gitignore
When starting the services using docker compose, a local `.hive` folder is filled with artefacts. Ignore it.
=> Ignore `.hive` folder

.npmrc
If you have a layout like this:
```
packages/
service-common/
package.json -> depends on "fastify-cors"
node_modules
fastify-cors
server/
package.json -> depends on "service-common@workspace"
src/
index.ts -> imports "service-common"
```
and you use `tsup` - the built code will **not** bundle the deps of `service-common`, instead the deps will be accessed regulary through an import statement.
In essence, code like this:
```js
// server/src/index.ts
import '@service-common';
```
will build to:
```
// server/dist/index.ts
<code from service-common>
```
The easiest solution is to simply hoist all deps so that the built code can run.
We might revisit this in the future with a more comprehensive solution that doesn't require hoisting, but for now - this should be enough.
=> Hoist all modules because of common deps

packages/web/app/src/components/organization/Permissions.tsx, packages/web/app/src/components/v2/modals/change-permissions.tsx
Currently, when you want to modify user's access, every access scope shows "no access", even though the user has some of them. This PR fixes it, the currently available scopes will be visible every time the modal is open.
Closes #500
=> Present user's permissions when opening a modal

package.json, pnpm-lock.yaml
App's login screen styles break if multiple instances of emotion are used. This PR locks all @emotion/react resolutions to a single version so we can guarantee a single instance.
=> Resolve to single @emotion/react version

packages/web/app/src/config/supertokens/backend.ts
in `trySignIntoAuth0WithUserCredentialsAndRetrieveUserInfo`
=> Read body only once when using legacy Auth0 flow

deployment/services/proxy.ts, deployment/utils/reverse-proxy.ts, packages/web/app/pages/[orgId]/[projectId]/[targetId]/explorer.tsx, packages/web/app/pages/[orgId]/[projectId]/[targetId]/explorer/[typename].tsx, packages/web/app/pages/[orgId]/[projectId]/[targetId]/history.tsx, packages/web/app/pages/[orgId]/[projectId]/[targetId]/index.tsx, packages/web/app/pages/[orgId]/[projectId]/[targetId]/laboratory.tsx, packages/web/app/pages/[orgId]/[projectId]/[targetId]/operations.tsx, packages/web/app/pages/[orgId]/[projectId]/[targetId]/settings.tsx, packages/web/app/pages/[orgId]/[projectId]/alerts.tsx, packages/web/app/pages/[orgId]/[projectId]/index.tsx, packages/web/app/pages/[orgId]/[projectId]/settings.tsx, packages/web/app/pages/[orgId]/index.tsx, packages/web/app/pages/[orgId]/members.tsx, packages/web/app/pages/[orgId]/settings.tsx, packages/web/app/pages/[orgId]/subscription/index.tsx, packages/web/app/pages/[orgId]/subscription/manage.tsx
I updated the helm chart `7.8.0 -> 10.0.0`
Whenever a request is dropped because of connection reset, we do a retry (max 2) now.
The timeout (response) is higher `60s -> 15s` for all upstream routes.
=> envoy - bump timeoutPolicy to 60s and retry twice on reset

integration-tests/tests/api/rate-limit/emails.spec.ts, packages/services/rate-limit/src/emails.ts, pnpm-lock.yaml
The title today contains the term `rate-limit` which might be a bit confusing. We are using this term internally for limiting the reserved quota, but I think it's kinda confusing when it's sent to end-users.
=> Improve rate-limit email title

packages/services/tokens/src/api.ts, packages/services/usage/src/index.ts, packages/services/usage/src/metrics.ts
It should give us more insights.
`tokens_http_requests` - to track number of calls received by the tokens service
`usage_tokens_duration_seconds` - to track the duration (useful once we switch to Redis at some point)
=> Introduce tokens_http_requests and usage_tokens_duration_seconds metrics

packages/services/emails/src/environment.ts, packages/services/emails/src/providers.ts
Without this setup it is not possible to send emails via smtp server with self-signed certificate. You will reverie such error
{"level":50,"time":1669707712901,"pid":1,"hostname":"hive-emails-deploy-7944bbd7-f5gft","code":"ESOCKET","command":"CONN","stack":"Error: self signed certificate\n    at TLSSocket.onConnectSecure (node:_tls_wrap:1539:34)\n    at TLSSocket.emit (node:events:513:28)\n    at TLSSocket.emit (node:domain:489:12)\n    at TLSSocket._finishInit (node:_tls_wrap:953:8)\n    at TLSWrap.ssl.onhandshakedone (node:_tls_wrap:734:12)","type":"Error","msg":"self signed certificate"}
=> Added posibility to use mail smtp server without trusted certificate

packages/services/emails/src/environment.ts
Fixed parse from env, as env variable is always string and zod cannot parse string to boolean - it is needed to convert it to boolean
=> Fixed parse env variable EMAIL_PROVIDER_SMTP_REJECT_UNAUTHORIZED

docker-compose.community.yml, integration-tests/docker-compose.yml, packages/services/storage/docker-compose.yml, packages/services/storage/package.json
`/usr/bin/mc mb myminio/artifacts` throws an exception if the bucket already exists.
=> Create bucket if non-existing, do not abort on exit

packages/services/external-composition/federation-2/README.md, packages/services/external-composition/federation-2/package.json, packages/services/external-composition/federation-2/src/environment.ts, packages/services/external-composition/federation-2/src/index.ts, packages/services/external-composition/federation-2/src/server.ts, packages/web/docs/src/pages/features/external-schema-composition.mdx, pnpm-lock.yaml
=> Refactor external composition service and added better documentation

deployment/index.ts, deployment/package.json, deployment/services/cf-broker.ts, deployment/services/cf-cdn.ts, deployment/services/graphql.ts, deployment/services/kafka.ts, deployment/services/proxy.ts, deployment/services/redis.ts, deployment/services/schema.ts, deployment/services/supertokens.ts, deployment/services/usage-ingestor.ts, deployment/services/usage.ts, deployment/utils/clickhouse.ts, deployment/utils/helpers.ts, deployment/utils/kafka.ts, deployment/utils/local-config.ts, deployment/utils/reverse-proxy.ts, pnpm-lock.yaml
=> Adjustments to Pulumi code to support more pre-prod envs

integration-tests/testkit/cli.ts, package.json, patches/@oclif__core@1.23.0.patch, pnpm-lock.yaml
```
./bin/dev whoami  5.15s
./bin/run whoami  0.35s
tests/cli/schema.spec.ts (149.848 s)
tests/cli/schema.spec.ts ( 38.438 s)
```
Speeds up the integration tests by almost 2 minutes.
It's a little hacky, because `@oclif/core` uses `require.resolve` to load the commands and they are in an entirely different directory (not part of `require.resolve.paths()`).
=> Use the production version of CLI

packages/services/api/src/modules/billing/module.graphql.ts, packages/services/api/src/modules/billing/resolvers.ts, packages/web/app/src/graphql/fragments.graphql
`BillingDetails.postalCode` was `Int`, but some postal codes include other characters than numbers.
App does not need some parts of billingConfiguration (postalCode included).
=> BillingDetails.postalCode as String, fetch less billingConfiguration in web/app

packages/services/server/src/graphql-handler.ts
We used to detect non-masked errors with `isGraphQLError` but now it's `isOriginalGraphQLError`
=> Use default skipError of @envelop/sentry

packages/services/api/src/modules/schema/providers/schema-publisher.ts
It was using target's id instead.
=> Fix target's name in GitHub schema:check

.changeset/nine-moose-itch.md, packages/libraries/client/src/apollo.ts, packages/libraries/client/src/gateways.ts, packages/libraries/client/tests/apollo.spec.ts, packages/libraries/client/tests/gateways.spec.ts, packages/services/api/src/modules/schema/providers/artifact-storage-reader.ts, packages/services/api/src/shared/aws.ts, packages/services/cdn-worker/package.json, packages/services/cdn-worker/src/dev.ts, packages/services/cdn-worker/src/index.ts, packages/services/server/src/index.ts, pnpm-lock.yaml
This replaces the AWS s3 SDK for the isomorphic code (Node.js + Cloudflare Workers) with an inlined version of [`aws4fetch`](https://github.com/mhart/aws4fetch).
The reason for this is that we used to generate pre-signed URLs for HEAD requests instead of doing direct requests with the AWS S3 SDK.
We could not do the requests through the AWS S3 SDK as it provided no way of providing a custom `fetch` implementation that is able to successfully execute requests on Cloudflare Workers (https://github.com/aws/aws-sdk-js-v3/issues/3104).
There is another issue with the Cloudflare R2 S3 compatible API. We noticed 500 (https://community.cloudflare.com/t/sometimes-r2-response-code-500/430205/14), sometimes 503, and recently also 499 status codes issued for the pre-signed HEAD requests.
Thus, we …
=> feat: use non-presigned url for S3 HEAD requests

deployment/services/kafka.ts
(TBH I didnt even know this syntax is possible haha)
Replace generic on literal with `as` statement, fixes issues with prettier and https://github.com/the-guild-org/shared-config/pull/154#pullrequestreview-1249865147.
The change will still have the same effect, see [TS playground](https://www.typescriptlang.org/play?#code/C4TwDgpgBAysBOBnKBeKAlCBjA9vAJgDyIICWAdgOYA0UJ8FlAfANwBQbu5JUAhgFywEyNAG8oAdxy8AFoIDk9eVAC+7Lj14AxXqQA2guElRRxU2YICMq9pxzdgUAEYmz0uVEUJlKvsiOI6vY8Tjr6rpLuVqp+QkjsQA).
=> Avoid generics on literals

packages/services/server/package.json, pnpm-lock.yaml
it should fix: https://github.com/kamilkisiela/graphql-hive/actions/runs/3939974567/jobs/6740492300
> ERR_PNPM_OUTDATED_LOCKFILE  Cannot install with "frozen-lockfile" because pnpm-lock.yaml is not up to date with packages/services/server/package.json
It happens when we cut a new release of libraries
=> Use workspace:* for client lib in server package

docker-compose.community.yml, integration-tests/docker-compose.integration.yaml, packages/services/storage/docker-compose.yml
With a memory limit, it operates on 75MB of RAM and spins up much much faster.
=> Use Redpanda instead of Kafka and ZooKeeper (integration tests and local)

integration-tests/testkit/flow.ts, integration-tests/testkit/seed.ts, integration-tests/tests/api/legacy-auth.spec.ts, integration-tests/tests/api/target/usage.spec.ts, packages/services/api/src/modules/operations/module.graphql.ts, packages/services/api/src/modules/operations/providers/operations-manager.ts, packages/services/api/src/modules/operations/providers/operations-reader.ts, packages/services/api/src/modules/operations/resolvers.ts, packages/web/app/src/components/target/operations/List.tsx, packages/web/app/src/graphql/fragments.graphql
This should speed up the slowest ClickHouse query from 12s to 1s.
I noticed that we reuse one query that is super heavy, and we do it for no reason.
The query is used in two places:
- to count the number of operations (unique per body)
- to generate a list of operations
In the first case, I wrote a much faster query to just count the operations.
In the second scenario, I had to do a little more.
On the "Operations" page, a body of an operation is only visible when a user clicks on a table's row.
The slowest part of the query is the `body` column in the `group` clause.
I decided to ignore `body` as it's needed only when a user performs a specific action and moved it to a separate query, that is executed lazily.
=> Avoid overfetching and get operation's body on-demand

packages/migrations/src/actions/2023.01.17T10.46.28.import-legacy-s3-keys-to-database.mts
=> fix: use correct key prefix for migration

packages/services/emails/src/index.ts, packages/services/tokens/src/index.ts, packages/services/usage-ingestor/src/index.ts, packages/services/webhooks/src/index.ts
`pino` does not allow to pass the logging functions, it needs the `this` context because it does not do `bind` ahead of time.
This should fix that.
Related  https://github.com/pinojs/pino/issues/956
=> Fix logger issue with heartbeat onError

.changeset/two-yaks-change.md, integration-tests/tests/api/schema/external-composition.spec.ts, package.json, packages/libraries/external-composition/build-example.mjs, packages/libraries/external-composition/example.mjs, packages/libraries/external-composition/src/index.ts, packages/libraries/hive-self-hosted-demo/README.md, packages/services/schema/package.json, packages/services/schema/src/orchestrators.ts, pnpm-lock.yaml
=> Pass errors coming from the external composition to the end-user

deployment/index.ts, deployment/services/cf-cdn.ts, deployment/services/graphql.ts, deployment/utils/cloudflare.ts, integration-tests/tests/api/artifacts-cdn.spec.ts, packages/services/cdn-worker/src/dev-polyfill.ts, packages/services/cdn-worker/src/dev.ts, packages/services/cdn-worker/src/index.ts, packages/services/cdn-worker/src/key-validation.ts, packages/services/cdn-worker/tests/cdn.spec.ts, packages/services/server/src/index.ts
Re-applies remaining changes from https://github.com/kamilkisiela/graphql-hive/pull/1005 for using the new s3 method for validating the CDN access tokens instead of using the old "static" method.
=> feat: use s3 bucket for validating CDN access tokens

.github/workflows/build-and-dockerize.yaml
https://github.com/docker/build-push-action/issues/761 was fixed, so we can drop the versioning pinning
=> Use latest `buildx` 

deployment/services/kafka.ts, packages/services/cdn-worker/src/dev-polyfill.ts, packages/services/tokens/src/api.ts, packages/services/tokens/src/cache.ts, packages/services/tokens/src/index.ts, packages/services/tokens/src/metrics.ts, packages/services/tokens/src/storage.ts
- An LRU cache for exceptions no longer stores 404.
- cache hit/miss metrics cover exceptions as well
- fix incorrect ttl in the in-memory cache (it was 60ms)
=> Fix the cache logic in Tokens service

packages/services/emails/src/api.ts, packages/services/emails/src/context.ts, packages/services/emails/src/index.ts, packages/services/rate-limit/src/api.ts, packages/services/rate-limit/src/index.ts, packages/services/schema/src/api.ts, packages/services/schema/src/index.ts, packages/services/server/src/api.ts, packages/services/server/src/index.ts, packages/services/service-common/package.json, packages/services/service-common/src/fastify.ts, packages/services/service-common/src/index.ts, packages/services/service-common/src/trpc.ts, packages/services/stripe-billing/src/api.ts, packages/services/stripe-billing/src/index.ts, packages/services/tokens/src/api.ts, packages/services/tokens/src/index.ts, packages/services/usage-estimator/src/api.ts, packages/services/usage-estimator/src/index.ts, packages/services/webhooks/src/api.ts, packages/services/webhooks/src/index.ts, packages/services/webhooks/src/types.ts
Make sure we use `req.log` to get the `x-request-id` header value in the log line.
Share a function to register `/trpc` server (better type safety, less boilerplate).
=> Log errors in tRPC servers

packages/services/cdn-worker/src/handler.ts, packages/services/cdn-worker/tests/cdn.spec.ts
Do an extra attempt to read the value from the store.
If we see that a single retry does not help, we should do a proper retry logic here.
Why not now? Because we have a new implementation based on R2 storage, and this change is simple enough to potentially fix it.
SENTRY-3793877087
=> Extra read from KV storage

packages/services/broker-worker/src/handler.ts, packages/services/webhooks/src/jobs.ts
Makes sure we use the correct content-type header value and give us some indicator that the request was proxied through Broker.
=> Add user-agent and content-type headers to response from Broker

packages/services/external-composition/federation-2/package.json, packages/services/external-composition/federation-2/src/environment.ts, packages/web/docs/src/pages/features/external-schema-composition.mdx
It was `0` by default (when parsed by Zod) and then the `??` operator didn't do anything because `0` is not `null` or `undefined`.
Now it's `3069` by default if no value is provided.
=> Fix port's default value in external-composition docker image

packages/migrations/package.json
I had a lot of headaches debugging.
This uses the `files` key in the `package.json` for only copying specific files instead of everything [as described on the docs](https://pnpm.io/cli/deploy).
Closes https://github.com/kamilkisiela/graphql-hive/issues/1209
=> fix: exclude .env file from migrations container

packages/services/cdn-worker/src/cdn-token.ts
closes https://github.com/kamilkisiela/graphql-hive/issues/1296
=> fix: gracefully handle base64 decoding error in case of invalid access token

.changeset/hip-needles-search.md, .changeset/ninety-windows-live.md, .changeset/soft-gifts-mix.md, packages/libraries/client/package.json, packages/libraries/client/src/apollo.ts, packages/libraries/client/src/internal/reporting.ts, packages/libraries/client/src/internal/types.ts, packages/libraries/client/src/internal/usage.ts, packages/libraries/client/src/internal/utils.ts, packages/libraries/client/tests/integration.spec.ts, packages/libraries/client/tests/reporting.spec.ts, pnpm-lock.yaml
- Support Federation v2 in schema reporting (ships the original schema now, not a schema processed by Apollo)
- Add @apollo/server and @envelop/types as optional dependencies
- Support @apollo/server (its plugin system)
=> Support @apollo/server and Federation v2 in Hive Plugin for Apollo

packages/services/server/src/index.ts
Just in case somebody uses GraphQL over HTTP spec-complaint headers (with literally 0.000000000001% adoption)
=> Support weird content types

.changeset/many-jobs-perform.md, packages/libraries/client/src/internal/usage.ts, packages/libraries/client/tests/usage-collector.spec.ts
fixes https://github.com/kamilkisiela/graphql-hive/issues/1220
GraphQL visitor `typeInfo.getFieldDef()` yields `undefined` when visiting arguments of a directive applied to a fragment spread within a fragment. 
When visiting a GraphQL operation, skip visiting the arguments of a directive - there is no value in visiting directive arguments (or even directives in general) in the context of determining field usage
Client side GraphQL directives on query documents don't affect the actual field usage of a schema.  i.e. it wouldn't matter if `@skip` or `@include` exclude a field for a particular operation - the execution of a query would fail if the schema didn't have the fields in the first place.
=> fix: skip visiting directive arguments when collecting usage

packages/services/schema/package.json, packages/services/schema/src/orchestrators.ts, pnpm-lock.yaml
Make sure it runs no longer than 30 seconds, otherwise CF yells at us.
Oh and yes I did use `got` instead of the amazing `fetch`, to get shit done quickly and avoid creating yet another retry + timeout logic with `AbortController`.
=> Add a timeout to external schema composition

integration-tests/docker-compose.integration.yaml, packages/services/broker-worker/src/dev.ts, packages/services/broker-worker/src/errors.ts, packages/services/broker-worker/src/handler.ts, packages/services/broker-worker/src/index.ts, packages/services/broker-worker/src/models.ts, packages/services/broker-worker/tests/broker.spec.ts, packages/services/schema/src/orchestrators.ts
The schema service couldn't make calls to external services due to a missing method property
This Pull Request fixes it and connects the Schema service with the Request Broker in the integration tests.
It also captures exceptions via Sentry now.
The request to the broker is now strongly typed.
=> Add missing method property in Request Broker

.changeset/long-cherries-invite.md, packages/libraries/client/src/internal/reporting.ts
=> Remove Query._entities when extracting original SDL from Fed v2

packages/services/schema/src/cache.ts, packages/services/schema/src/orchestrators.ts
Equal to the timeout defined for redis cache, but not higher than 25s (CF has 30s timeout anyway).
=> Set higher timeout when calling external composition service

docker/router.dockerfile
It should fix:
```
> [linux/arm64 build 12/15] RUN cargo build --release:
#0 4.824     Updating git repository `[https://github.com/graphql-rust/graphql-parser.git`](https://github.com/graphql-rust/graphql-parser.git%60)
#0 5.862     Updating crates.io index
#52 272.5 Killed
ERROR: failed to solve: process "/bin/sh -c cargo build --release" did not complete successfully: exit code: 137
```
Another option to fix it and avoid using `nightly` is passing `--config net.git-fetch-with-cli=true` to `cargo build`.
=> Build Docker Image of Apollo Router using sparse-registry (nightly)

.github/workflows/pr.yaml, .github/workflows/release-stable.yaml
This one also fixes https://github.com/kamilkisiela/graphql-hive/issues/861 because the PAT has higher rate-limit 🤦
=> `rc` releases for Changesets release PR

.eslintrc.cjs, package.json, packages/services/broker-worker/package.json, packages/services/cdn-worker/package.json, packages/services/emails/package.json, packages/services/external-composition/federation-2/package.json, packages/services/rate-limit/package.json, packages/services/schema/package.json, packages/services/server/package.json, packages/services/stripe-billing/package.json, packages/services/tokens/package.json, packages/services/usage-estimator/package.json, packages/services/usage-ingestor/package.json, packages/services/usage/package.json, packages/services/webhooks/package.json, pnpm-lock.yaml, tsconfig.json, tsup/dev.config.node.ts, tsup/dev.config.worker.ts, tsup/utils.ts
Now when you change something in api/common/service-common, you'll get all dependant packages reloaded
=> Refactor `tsup` configurations and fix watch mode

deployment/services/database-cleanup.ts, deployment/utils/botkube.ts, deployment/utils/helm.ts, deployment/utils/observability.ts, deployment/utils/reverse-proxy.ts, renovate.json
Closes https://github.com/kamilkisiela/graphql-hive/issues/1510
=> fix renovate config and extract versions from files under deployment dir

packages/web/app/pages/[orgId]/[projectId]/[targetId]/explorer.tsx, packages/web/app/pages/[orgId]/[projectId]/[targetId]/history.tsx, packages/web/app/pages/[orgId]/[projectId]/[targetId]/index.tsx, packages/web/app/pages/[orgId]/[projectId]/[targetId]/laboratory.tsx, packages/web/app/pages/[orgId]/[projectId]/[targetId]/operations.tsx, packages/web/app/pages/[orgId]/[projectId]/[targetId]/settings.tsx
This was somehow not caught by typescript. I am investigating further on the root cause.
=> fix: show cdn button

integration-tests/testkit/flow.ts, integration-tests/tests/api/schema/composition-federation-2.spec.ts, integration-tests/tests/api/schema/external-composition.spec.ts, packages/services/api/src/modules/project/providers/project-manager.ts, packages/services/api/src/modules/schema/module.graphql.ts, packages/services/api/src/modules/schema/providers/schema-manager.ts, packages/services/api/src/modules/schema/resolvers.ts, packages/web/app/src/components/project/settings/external-composition.tsx, packages/web/app/src/components/v2/tooltip.tsx, packages/web/app/src/lib/urql-cache.ts
On hold - I will do a button with 3 states (success, in progress, failure) and let users test the endpoint + secret they provided but also the already existing endpoint (with already existing secret).
=> Show status of external schema composition service

.prettierignore, integration-tests/testkit/flow.ts, integration-tests/tests/api/schema/composite.spec.ts, packages/services/api/src/modules/lab/resolvers.ts, packages/services/api/src/modules/schema/providers/models/composite-legacy.ts, packages/services/api/src/modules/schema/providers/models/composite.ts, packages/services/api/src/modules/schema/providers/models/shared.ts, packages/services/api/src/modules/schema/providers/models/single-legacy.ts, packages/services/api/src/modules/schema/providers/models/single.ts, packages/services/api/src/modules/schema/providers/orchestrators/errors.ts, packages/services/api/src/modules/schema/providers/orchestrators/federation.ts, packages/services/api/src/modules/schema/providers/orchestrators/single.ts, packages/services/api/src/modules/schema/providers/orchestrators/stitching.ts, packages/services/api/src/modules/schema/providers/registry-checks.ts, packages/services/api/src/modules/schema/providers/schema-helper.ts, packages/services/api/src/modules/schema/providers/schema-manager.ts, packages/services/api/src/modules/schema/providers/schema-publisher.ts, packages/services/api/src/modules/schema/resolvers.ts, packages/services/api/src/modules/shared/providers/storage.ts, packages/services/api/src/shared/entities.ts, packages/services/api/src/shared/mappers.ts, packages/services/api/src/shared/schema.ts, packages/services/schema/src/api.ts, packages/services/schema/src/metrics.ts, packages/services/schema/src/orchestrators.ts, packages/services/schema/src/types.ts, packages/services/storage/src/index.ts
- Uploading artifacts to CDN is now done as part of transaction
- Schema is published only after all artifacts are uploaded
- Only `composeAndValidate` procedure in the schema service
- Less calls to the schema service (SDLs of full schema and supegraph are passed as arguments)
- `schema_validate_total`, `schema_build_total` and `schema_supergraph_total` counter metrics are now replaced by `schema_compose_and_validate_total` counter metric
=> Small improvements to the schema publishing flow

packages/services/api/src/modules/schema/providers/schema-helper.ts
The object from `composeAndValidationResult.errors` array is not `Error`, it's an object with two props: `message` and `source`.
=> Fix missing composition error message

packages/web/docs/src/pages/integrations/_meta.json, packages/web/docs/src/pages/integrations/graphql-code-generator.mdx
Appending `.graphql` to SDL endpoint will return SDL which can be used in codegen and enables the [`handleAsSDL` option](https://the-guild.dev/graphql/codegen/docs/config-reference/schema-field#handleassdl) implicity.
=> docs: setting up codegen to use with Hive CDN

packages/web/docs/src/pages/docs/self-hosting/get-started.mdx
It seems the docker-compose.community.yml file is elsewhere than on example wget command.
The change is only to the documentation in getting started tutorial with self-hosting Hive.
=> Update wget command to a correct url

.github/workflows/pr-rust.yaml, .github/workflows/pr.yaml
This should allow us to easily re-run `pr` workflow, and should unblock the CI queues
=> Split `pr` and `rust-pr` workflows

packages/web/app/src/components/target/operations/Stats.tsx
Because of `Autosize disableHeight` and `!size.height` combo, the child element never renders.
=> Fix Clients block in Operations page

integration-tests/tests/api/schema/publish.spec.ts, packages/services/api/src/modules/schema/providers/registry-checks.ts, packages/services/api/src/modules/schema/resolvers.ts, packages/services/api/src/modules/schema/schema-change-from-meta.ts
- adds a test for the service url change construction altered in https://github.com/kamilkisiela/graphql-hive/pull/2149
- reenables serving schema URL changes from the database for stitching projects
- use correct message for schema URL changes loaded from the database
=> feat: make sure legacy project records are not broken

docs/DEVELOPMENT.md, integration-tests/tests/api/schema/publish.spec.ts, packages/migrations/src/actions/2023.05.12T08.29.06.store-supergraph-on-schema-versions.sql, packages/migrations/src/actions/down/2023.05.12T08.29.06.store-supergraph-on-schema-versions.sql, packages/services/api/src/modules/schema/lib/__tests__/federation-super-graph.spec.ts, packages/services/api/src/modules/schema/lib/federation-super-graph.ts, packages/services/api/src/modules/schema/module.graphql.ts, packages/services/api/src/modules/schema/providers/schema-manager.ts, packages/services/api/src/modules/schema/providers/schema-publisher.ts, packages/services/api/src/modules/schema/resolvers.ts, packages/services/api/src/modules/shared/providers/storage.ts, packages/services/api/src/shared/entities.ts, packages/services/api/src/shared/mappers.ts, packages/services/external-composition/federation-2/package.json, packages/services/storage/src/db/types.ts, packages/services/storage/src/index.ts, packages/web/app/pages/[orgId]/[projectId]/[targetId]/index.tsx, packages/web/app/src/components/target/explorer/common.tsx, packages/web/app/src/components/target/explorer/enum-type.tsx, packages/web/app/src/components/target/explorer/input-object-type.tsx, packages/web/app/src/components/target/explorer/interface-type.tsx, packages/web/app/src/components/target/explorer/object-type.tsx, packages/web/app/src/components/target/explorer/scalar-type.tsx, packages/web/app/src/components/target/explorer/super-graph-metadata.tsx, packages/web/app/src/components/target/explorer/union-type.tsx, packages/web/app/src/components/v2/icon.tsx, pnpm-lock.yaml, pnpm-workspace.yaml, scripts/package.json, scripts/seed-local-env.ts
On the Explorer page, we want to show users from which subgraph a specific schema coordinate (field/type/etc.) originates.
We can extract this data from the annotated supergraph SDL.
https://www.notion.so/theguildoss/Display-the-subgraph-from-which-the-type-is-originated-0734755cb4cf4a7fb298f923da6140ea?pvs=4
- Refactors the insert/decoding logic for schema versions
- Store supergraph SDL in the schema_versions database table
- Attempt to construct meta information based on the supergraph SDL and expose it via the GraphQL API if available
=> feat: supergraph field information in explorer

packages/services/server/package.json, packages/services/server/src/graphql-handler.ts, packages/services/server/src/use-unexpected-serialization-error.ts, pnpm-lock.yaml
See https://github.com/n1ru4l/envelop/issues/1808
This maps GraphQLErrors raised by scalars `serialize` function/method to normal Errors in order to get them masked and reported via Sentry.
=> feat: make sure unexpected serialization errors are reported

packages/web/app/src/components/target/operations/Stats.tsx, packages/web/app/src/lib/hooks/index.ts, packages/web/app/src/lib/hooks/use-formatted-duration.ts
% as units (x axes)
No longer a smooth line, units (y axis), dashed separators
=> Change a bit the styling of charts

packages/services/api/src/modules/rate-limit/providers/rate-limit.provider.ts, packages/services/api/src/modules/rate-limit/resolvers.ts, packages/services/api/src/modules/shared/providers/storage.ts, packages/services/rate-limit/src/limiter.ts, packages/services/storage/src/index.ts, packages/web/app/pages/[orgId]/index.tsx, packages/web/app/pages/[orgId]/view/subscription/index.tsx, packages/web/app/src/components/layouts/organization.tsx, packages/web/app/src/components/organization/billing/RateLimitWarn.tsx
Closes https://github.com/the-guild-org/graphql-hive-deployment/issues/1379 
This PR removes the hard rate-limit for Enterprise users. 
This is the new behavior:
- When the limit is reached, a hard limit is performed and data ingestion stops. 
- Info about the limit is reported to Grafana. 
- Email is sent when 90% and 100% are reached. 
- Users will see the following message on the dashboard:
- When the limit is reached, a soft limit is performed and data is still ingested. 
- Info about the limit is reported to Grafana. 
- Info about the limit is reported to Grafana. 
- Email is sent when 90% and 100% are reached. 
- Users will see the following message on the dashboard:
=> Changes in rate-limiter to allow no data-loss for Enterprise users

packages/services/api/src/modules/schema/providers/models/composite-legacy.ts, packages/services/api/src/modules/schema/providers/models/composite.ts, packages/services/api/src/modules/schema/providers/models/shared.ts, packages/services/api/src/modules/schema/providers/models/single-legacy.ts, packages/services/api/src/modules/schema/providers/models/single.ts, packages/services/api/src/modules/schema/providers/schema-publisher.ts
Part of a series of smaller PRs for cleaning up things before I pull in larger changes for persisting schema checks.
Related https://github.com/kamilkisiela/graphql-hive/issues/333
This removes the unnecessary casting of a boolean from each of the individual models (and returning them; while being unused locally) by instead having the same code once where it is actually needed and can be coomputed in the same way.
=> refactor: lift boolean that is not used locally up

packages/services/api/src/modules/schema/providers/models/composite-legacy.ts, packages/services/api/src/modules/schema/providers/models/composite.ts, packages/services/api/src/modules/schema/providers/models/shared.ts, packages/services/api/src/modules/schema/providers/models/single-legacy.ts, packages/services/api/src/modules/schema/providers/models/single.ts, packages/services/api/src/modules/schema/providers/schema-publisher.ts
Part of a series of smaller PRs for cleaning up things before I pull in larger changes for persisting schema checks.
I discussed a bit with @kamilkisiela on whether a check that failed because of a missing service name should be persisted.
We came to the conclusion that having the service name is rather a prerequisite for doing the check. Thus, it makes sense to lift the service name check outside the individual models `check` method to the `SchemaPublisher.check` method, as we also letter on do not want to persist a check with this reason.
Related https://github.com/kamilkisiela/graphql-hive/issues/333
see background. lift the service name check outside the individual models `check` method to the `SchemaPublisher.check` method. Also remove `!` 👀
=> refactor: lift the service name check to the schema publisher

packages/libraries/router/src/agent.rs, packages/libraries/router/src/registry.rs, packages/libraries/router/src/usage.rs, packages/web/docs/src/pages/docs/integrations/apollo-router.mdx
Fixes #2340
Ideally we should accept a list of certificates but this PR aims to unblock users quickly.
=> Apollo Router accepts invalid SSL certificates (opt-in)

packages/services/api/src/modules/schema/providers/models/composite-legacy.ts, packages/services/api/src/modules/schema/providers/models/composite.ts, packages/services/api/src/modules/schema/providers/models/shared.ts, packages/services/api/src/modules/schema/providers/models/single-legacy.ts, packages/services/api/src/modules/schema/providers/models/single.ts, packages/services/api/src/modules/schema/providers/registry-checks.ts, packages/services/api/src/modules/schema/providers/schema-publisher.ts, packages/services/api/src/modules/schema/resolvers.ts
Part of a series of smaller PRs for cleaning up things before I pull in larger changes for persisting schema checks.
Related https://github.com/kamilkisiela/graphql-hive/issues/333
This changes the structure of the check failure state so it is later easier to read and write it to the database. Also removes some duplicated code.
=> refactor: remodel schema check failure object

packages/services/api/src/modules/schema/providers/registry-checks.ts
Seems like some changes in https://github.com/kamilkisiela/graphql-hive/commit/71b22e34364418dbfc5375a51c8b597186a45eeb cause build/typecheck issues. We missed it because of some turbo caching issues (i guess).
Running with `--force` seems to bring this error. Also it happens in other PRs.
=> fix typecheck issues after refactor

integration-tests/tests/api/policy/policy-check.spec.ts, packages/services/api/src/modules/schema/providers/models/composite.ts, packages/services/api/src/modules/schema/providers/models/shared.ts, packages/services/api/src/modules/schema/providers/models/single.ts, packages/services/api/src/modules/schema/providers/orchestrators/single.ts, packages/services/api/src/modules/schema/providers/registry-checks.ts, packages/services/api/src/modules/schema/providers/schema-helper.ts, packages/services/schema/src/cache.ts, packages/services/schema/src/orchestrators.ts
Related https://github.com/kamilkisiela/graphql-hive/issues/333
After talking with @dotansimha, we came to the conclusion that these checks can potentially expose sensitive messages. It makes more sense to drop the try-catch statement and let those kind of errors escalate.
=> fix: avoid leaking internal (unexpected) errors to the outside world

packages/services/service-common/src/graceful-shutdown.ts, packages/services/usage/src/index.ts, packages/services/usage/src/usage.ts
It should mark the pod as not ready when Kafka producer fails to send a message.
=> Set readiness of usage service based on errors returned by Kafka

integration-tests/tests/api/tokens.spec.ts, package.json, packages/services/server/package.json, packages/services/server/src/graphql-handler.ts, pnpm-lock.yaml
This should take some pressure off from `Query.tokenInfo`
=> Cache Query.tokenInfo for 5s

.changeset/fifty-lions-cheat.md, packages/libraries/client/package.json, packages/libraries/client/src/apollo.ts, packages/libraries/client/src/client.ts, packages/libraries/client/src/envelop.ts, packages/libraries/client/src/index.ts, packages/libraries/client/src/internal/types.ts, packages/libraries/client/src/internal/usage.ts, packages/libraries/client/src/yoga.ts, packages/libraries/client/tests/tsconfig.json, packages/libraries/client/tests/usage.spec.ts, packages/libraries/client/tests/yoga.spec.ts, packages/services/server/src/graphql-handler.ts, pnpm-lock.yaml
When using the yoga response cache plugin, hive metrics wont be reported with the `useHive` envelop plugin, as the execution phase is skipped.
This Yoga plugin that acts in the `onParams`  and `onResultProcess` hooks, which are always invoked. This leads to the usage data being always reported.
=> feat: useYogaHive

packages/web/app/src/components/target/operations/Stats.tsx
We were using `clsx` but it does not merge taildwind classes correcly.
=> Fix styling in Operations view

packages/services/api/src/modules/schema/providers/models/shared.ts, packages/services/api/src/modules/schema/providers/models/single.ts, packages/services/api/src/modules/schema/providers/registry-checks.ts
Nothing major, but after this got deployed we should run these SQL statements.
```sql
UPDATE schema_checks set schema_policy_warnings = NULL where schema_policy_warnings = '[]'::jsonb;
UPDATE schema_checks set safe_schema_changes = NULL where safe_schema_changes = '[]'::jsonb;
```
=> feat: insert null instead of empty array

packages/services/api/src/modules/schema/providers/artifact-storage-writer.ts
Seems like Google Cloud Storage is very sensitive and needs additional care.
Works on R2 (tested locally and on dev).
Closes #2151
=> A boolean that makes Google Cloud Storage happy

.changeset/dirty-adults-clap.md, packages/libraries/cli/src/helpers/config.ts
Reading `registry.endpoint` from the config below, results in `Cannot read properties of undefined (reading 'endpoint')`.
```json
{
"token": "123456",
"registry": "it should be an object..."
}
```
=> cli: prevent reading a key of undefined value from config file

docker/app.dockerfile, docker/cli.dockerfile, docker/migrations.dockerfile
When deploying hive with using Hashicorp Vault init container, the container fails with error
```
time="2022-10-19T17:58:45Z" level=error msg="failed to request new Vault token" app=vault-env err="Put \"********/login\": x509: certificate signed by unknown authority"
```
Add CA-certificates to base images
=> Add ca certificates to base docker images

packages/services/usage/src/index.ts
otherwise it breaks `maskToken` function
=> Check length of token in usage service

packages/web/docs/src/pages/docs/get-started/single-project.mdx
The documentation has a simple typo; "Monintoring" is a misspelling of "Monitoring" which this PR corrects
No major changes, just a simple copy update
=> Correcting simple copy typo

.github/workflows/apollo-router-updater.yaml, package.json, pnpm-lock.yaml, scripts/apollo-router-action.ts
This PR adds a cron job (runs every 2 hours but can be triggered manually as well) to check the latest version of `apollo-router` and compare it with the local version from `Cargo.lock`.
If the local version is out of date, a `Cargo.lock` file will be updated and a Pull Request opened.
Current solution (renovate) does not work...
=> Update apollo-router automatically

docs/TESTING.md, packages/services/api/src/create.ts, packages/services/cdn-worker/README.md, packages/services/cdn-worker/src/index.ts, packages/services/server/README.md, packages/services/server/src/environment.ts, packages/services/server/src/index.ts
This fixes an issue when using graphql-hive with aws s3 as the artifact storage provider.
Adding a way to pass the optional S3_SESSION_TOKEN variable. This should not change any existing behavior.
Also removing setting the region to 'auto'  while creating the AWS client. The region should be guessed correctly via:
https://github.com/kamilkisiela/graphql-hive/blob/d6c417837d9bcd80412d1b2283244d0dbf9e3649/packages/services/cdn-worker/src/aws.ts#L413
nit: added some indentation fixes to the Testing readme file.
By the way, this is a great project!
=> add optional s3_session_token variable and remove setting region to auto

packages/services/server/src/graphql-handler.ts, packages/web/app/src/components/ui/query-error.tsx
+ extract operation name from DocumentNode if not available on the request object
+ show only the first error message from `result.errors[]` instead of using `CombinedError` class from URQL (it combines error messages and usually they are more than one and we end up with duplicates)
=> Improvements to error handling in Yoga

packages/services/server/scripts/copy-persisted-operations.mts
Fixes an issue with `TypeError: Cannot read properties of undefined (reading 'body') at getLocation`
=> Parse persisted operations with noLocation

packages/services/api/src/create.ts, packages/services/api/src/modules/lab/index.ts, packages/services/api/src/modules/lab/module.graphql.ts, packages/services/api/src/modules/lab/resolvers.ts, packages/web/app/package.json, packages/web/app/pages/[orgId]/[projectId]/[targetId]/laboratory.tsx, packages/web/app/pages/api/lab/[...lab].ts, packages/web/app/src/components/layouts/target.tsx, packages/web/app/src/components/target/laboratory/connect-lab-modal.tsx, packages/web/app/src/components/ui/alert.tsx, packages/web/app/src/lib/hooks/use-reset-state.ts, packages/web/docs/src/pages/docs/features/laboratory.mdx, pnpm-lock.yaml
We removed the laboratory mock API, as we thought nobody uses it. Actually, it is used. So we bring it back.
Closes https://github.com/kamilkisiela/graphql-hive/issues/2686
=> feat: bring back the lab mock api

packages/migrations/src/actions/2023.08.01T11.44.36.schema-checks-expires-at.ts, packages/migrations/src/run-pg-migrations.ts, packages/services/api/src/index.ts, packages/services/api/src/modules/rate-limit/providers/rate-limit.provider.ts, packages/services/api/src/modules/schema/providers/schema-publisher.ts, packages/services/api/src/modules/shared/lib/task-runner.ts, packages/services/api/src/modules/shared/providers/storage.ts, packages/services/server/src/environment.ts, packages/services/server/src/index.ts, packages/services/storage/src/db/types.ts, packages/services/storage/src/index.ts
See https://github.com/kamilkisiela/graphql-hive/issues/2690
Adds an `expires_at` column to the `schema_checks` pg table.
New records in the `schema_checks` table will be inserted with an `expires_at` data based on the data retention (if the usage service is configured).
A cron job runs within the server container for deleting `schema_checks` whose `expires_at` is reached.
Additional things to consider:
- For all the records we already have within our database we need to run an additional migration that populates the `expires_at` values. We don't need to automatically run this for the self-hosted database migrations.
=> feat: apply data retention constraint on schema checks

docker/docker-compose.dev.yml, packages/services/api/src/modules/organization/providers/organization-manager.ts, packages/services/api/src/shared/entities.ts, packages/services/storage/src/index.ts
The `docker-compose.dev.yml` file was broken for the oidc service. While testing stuff I also noticed that you can leave an organization as an oidc member. This should not be the case.
brrrt
=> feat: disable leave organization for oidc members

packages/web/app/pages/[orgId]/[projectId]/[targetId]/operations.tsx, packages/web/app/src/components/target/operations/Stats.tsx
Show up to 90d of collected data. Charts with resolution between 90 and 60 data points (depending on the date range).
Hide date range options shorter than the data retention period.
This is a preparation for big changes we're going to introduce soon (ClickHouse).
=> Use different resolution for different date ranges

packages/web/app/src/components/schema-editor.ts
=> fix `Should not import the named export 'dependencies'.'monaco-editor'`

.github/workflows/release-stable.yaml, docker/docker.hcl
Build and Push docker image of CLI only when a new stable release is published.
This should speed up our CI.
Effect? "Only" 3 minutes (before it was ~10 minutes or more) spent on `build docker images` step.
=> Skip CLI when building docker images

.changeset/spotty-squids-sniff.md, packages/libraries/cli/README.md, packages/libraries/cli/src/commands/operations/check.ts, packages/libraries/cli/src/helpers/operations.ts
```bash
hive operations:check  --graphqlTag graphql-tag
hive operations:check --graphqlTag graphql:react-relay
hive operations:check --graphqlTag graphql-tag --graphqlTag graphql:react-relay
hive operations:check --globalGraphqlTag gql
hive operations:check --globalGraphqlTag graphql
hive operations:check --globalGraphqlTag graphql --globalGraphqlTag graphql
```
=> Support custom graphql tag pluck config

deployment/services/proxy.ts, deployment/utils/reverse-proxy.ts, packages/services/usage/src/index.ts, packages/services/usage/src/metrics.ts
Pod can be marked as not ready to accept requests but the gateway may not be aware yet. This PR adds a retry logic for such cases. Fastify (the http server framework we use) returns 503 after close() method is called so it matches our scenario as well.
https://projectcontour.io/docs/v1.7.0/api/#projectcontour.io/v1.RetryPolicy
=> Retry requests to /usage when it is not ready

package.json, packages/web/app/package.json, pnpm-lock.yaml, turbo.json
Not sure why `@hive/server` depends on `@hive/app`. It should be the opposite.
It caused a build speed issue when running `pnpm build:services`. The `hive/app` was one of the dependencies of `hive/server` so whenever the `pnpm build:services` ran (integration-tests), the `hive/app` was built as well. The build output of `hive/app` is not cached and takes a lot of time (minutes) so it was slowing down the integration-test (1,2,3) jobs.
This Pull Request adds `@hive/server` as a devDependency of `@hive/app` and removes `@hive/app` from `@hive/server` dependencies.
=> Make hive/app dependent on hive/server, not the other way around

deployment/utils/observability.ts
Route them to debug sink.
Updates to `loki` sink:
- sets `out_of_order_action: 'accept'`
- sets `remove_timestamp: false`
=> Drop envoy logs when they fail at remap stage

packages/services/cdn-worker/src/analytics.ts, packages/services/cdn-worker/src/artifact-handler.ts, packages/services/cdn-worker/src/artifact-storage-reader.ts, packages/services/cdn-worker/src/errors.ts, packages/services/cdn-worker/src/handler.ts, packages/services/cdn-worker/src/index.ts, packages/services/cdn-worker/src/key-validation.ts, packages/services/cdn-worker/src/tracked-response.ts, packages/services/server/src/index.ts
Introduces two new metrics: `r2` (calls to R2) and `response` (status code + targetId of all responses).
=> Track responses and R2 calls

deployment/index.ts, deployment/services/app.ts, deployment/services/billing.ts, deployment/services/emails.ts, deployment/services/graphql.ts, deployment/services/policy.ts, deployment/services/proxy.ts, deployment/services/rate-limit.ts, deployment/services/schema.ts, deployment/services/supertokens.ts, deployment/services/tokens.ts, deployment/services/usage-estimation.ts, deployment/services/usage-ingestor.ts, deployment/services/usage.ts, deployment/services/webhooks.ts, deployment/utils/service-deployment.ts
Closes https://github.com/the-guild-org/graphql-hive-deployment/issues/1377
=> Explore `topologySpreadConstraints` for K8s deployments 

docker/app.dockerfile, docker/cli.dockerfile, docker/migrations.dockerfile, docker/router.dockerfile, docker/services.dockerfile
https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry
As per the `opencontainers/image-spec` setting the correct label for source of repository.
=> fix: opencontainer label for images

packages/services/api/src/modules/integrations/providers/github-integration-manager.ts, packages/services/api/src/modules/schema/providers/schema-publisher.ts
Instead of creating a GitHub check run at the end of the pipeline, we try to create a GitHub check run before running any of the schema composition or schema check logic as some kind of way to verify we can access the repository and then, afterward update the existing check-run.
=> reintroduce GitHub repository access check

integration-tests/testkit/seed.ts, integration-tests/tests/api/schema/publish.spec.ts, packages/services/api/src/modules/schema/providers/schema-publisher.ts
To prove it was a bug: https://github.com/kamilkisiela/graphql-hive/actions/runs/6494033401/job/17636446607?pr=3040
=> Publishing schema with a deprecated "github: false" should be successful

packages/web/docs/src/pages/docs/management/projects.mdx
I'm just diving into the docs for GraphQL hive and noticed a couple small typos that I thought I'd fix.
A couple of small typo fixes in the documentation.
n/a
=> Very small typo fixes

packages/web/app/pages/[organizationId]/[projectId]/view/settings.tsx
@n1ru4l it is no longer needed I think, the only purpose is to display either "No github connected" or "here's a list of repositories". I think it's fine to remove it as there is no action button.
I left there only the "use project's name in check" migration.
=> Remove Github Integration from project settings

.changeset/brave-chairs-give.md, patches/oclif@3.17.1.patch, pnpm-lock.yaml
Fixes https://github.com/kamilkisiela/graphql-hive/actions/runs/6507151920/job/17674025253#step:4:23
=> Fix [: /bin: unexpected operator on POSIX

packages/libraries/router/router.yaml, packages/libraries/router/src/registry.rs
Closes #3052
Pass supergraph SDL to Router only if the response status is 2XX and the response body contains a valid supergraph.
=> Ensure valid supergraph in Router

packages/services/api/src/modules/operations/providers/operations-reader.ts
A query I used for benchmarking shows 2.5x improvement: 3.5s -> 1s.
The "before" query had a long list of WHERE conditions. The new query fetches all rows, aggregates them to sum(total) and only then applies a long list of WHERE conditions. I would expect it to be less performant but it actually do less computation this way.
=> Improve performance of OperationsReader.getTopOperationsForTypes

.github/workflows/main.yaml
Update `Accept` and `X-GitHub-Api-Version` headers according to https://docs.github.com/en/free-pro-team@latest/rest/repos/repos?apiVersion=2022-11-28#create-a-repository-dispatch-event
Looks like the api is stable now.
=> Update "Trigger staging deployment" step

packages/web/app/src/components/organization/Permissions.tsx, packages/web/app/src/components/v2/modals/create-access-token.tsx, packages/web/app/src/lib/access/common.ts
Since registry access tokens are only meant to access the registry and usage, it does not make sens to give the user options for selecting all the other scopes for organization and user management. This PR adjusts the modal, so it only manages permissions for the registry and usage.
This PR reapplies the previous effort (that got reverted due to issues).
- https://github.com/kamilkisiela/graphql-hive/pull/3060
- https://github.com/kamilkisiela/graphql-hive/pull/3004
=> limit registry/usage access tokens to registry/access token scopes

.changeset/bright-seahorses-collect.md, packages/libraries/cli/src/commands/whoami.ts
Cleanup for https://github.com/kamilkisiela/graphql-hive/pull/3215
=> Remove `Access to operation:publish` information from CLI command "whoami" (unused)

packages/migrations/src/actions/2023.10.26T12.44.36.schema-checks-filters-index.ts, packages/migrations/src/index.ts, packages/migrations/src/pg-migrator.ts
Adding indices to the `schema_checks` table is slow and would block pending operations on the table (writes, updates) for at least 30 seconds, according to @kamilkisiela estimations), which would block our customers from using any features related to schema_checks for that timeframe...
Instead, we can create indices concurrently using the [`CONCURRENTLY` keyword](https://www.postgresql.org/docs/current/sql-createindex.html).
However, this requires us to run database migrations outside a transaction, which is fine but requires adjustments to our migrations-runner, which is running everything inside a single transaction. 
I also added some time logging, which makes it easier for us to see the actual runtimes of the single migrations.
Example output:
=> feat: run migrations outside transaction

packages/libraries/client/src/version.ts, packages/migrations/package.json, packages/migrations/src/actions/2023.11.02T14.41.41.schema-checks-dedup.ts, packages/migrations/src/run-pg-migrations.ts, packages/migrations/test/2023.02.22T09.27.02.delete-personal-org.test.ts, packages/migrations/test/2023.09.25T15.23.00.github-check-with-project-name.test.ts, packages/migrations/test/2023.10.25T14.41.41.schema-checks-dedup.test.ts, packages/migrations/test/2023.11.02T14.41.41.schema-checks-dedup.test.ts, packages/migrations/test/index.ts, packages/migrations/test/utils/testkit.ts, packages/services/api/src/modules/schema/providers/schema-publisher.ts, packages/services/api/src/modules/shared/providers/storage.ts, packages/services/api/src/shared/entities.ts, packages/services/server/src/index.ts, packages/services/storage/src/db/types.ts, packages/services/storage/src/index.ts, packages/services/storage/src/schema-change-model.ts
Closes https://github.com/kamilkisiela/graphql-hive/issues/2603
Adds `sdl_store` table with `id` (hash of sdl) and `sdl` columns.
Replaces `schema_sdl`, `supergraph_sdl`, `composite_schema_sdl` with `schema_sdl_store_id`, `supergraph_sdl_store_id` and `composite_schema_sdl_store_id`.
=> Use KV storage to deduplicate SDLs from schema_checks

packages/services/api/src/modules/project/providers/project-manager.ts
Right now, anyone can create projects for an organization.
=> fix: require project read access for creating new projects within an organization

deployment/services/graphql.ts, packages/services/api/src/modules/cdn/providers/cdn.provider.ts, packages/services/api/src/modules/cdn/providers/tokens.ts, packages/services/api/src/modules/schema/providers/schema-publisher.ts, packages/services/cdn-worker/src/artifact-handler.ts, packages/services/cdn-worker/src/dev-polyfill.ts, packages/services/cdn-worker/src/dev.ts, packages/services/cdn-worker/src/env.ts, packages/services/cdn-worker/src/handler.ts, packages/services/cdn-worker/src/index.ts, packages/services/cdn-worker/tests/cdn.spec.ts, packages/services/server/README.md, packages/services/server/src/environment.ts
=> feat: no longer publish to the legacy CDN

packages/web/app/pages/[organizationId]/[projectId]/[targetId]/settings.tsx, packages/web/app/pages/[organizationId]/[projectId]/index.tsx, packages/web/app/pages/[organizationId]/index.tsx, packages/web/app/pages/manage/index.tsx, packages/web/app/src/components/common/TimeFilter.ts, packages/web/app/src/components/target/explorer/provider.tsx, packages/web/app/src/lib/date-time.ts, packages/web/app/src/lib/hooks/use-date-range-controller.ts
The `subDays` function from `date-fns` adjusts the hour based on daylight savings.
We want to keep the hour the same as TTL in ClickHouse is set to 30 * 24 hours and it conflicts with date-fns logic.
=> Fix "requested date range is too old for the selected query type" error

packages/web/app/pages/[organizationId]/[projectId]/[targetId]/laboratory.tsx
As we reset the colours, the background became transparent. There are possibly other ways to fix it by rethinking the CSS we apply, but this works, and the bg colour I applied aligns with the other colours.
=> Fix GraphiQL's hints transparent background

integration-tests/tests/api/schema/delete.spec.ts, integration-tests/tests/api/schema/publish.spec.ts, packages/libraries/cli/tsconfig.json, packages/libraries/client/tsconfig.json, packages/libraries/core/tsconfig.json, packages/libraries/external-composition/tsconfig.json, packages/services/api/src/modules/schema/providers/registry-checks.ts, packages/services/api/src/modules/schema/providers/schema-manager.ts, packages/services/api/src/modules/schema/providers/schema-publisher.ts, packages/services/api/src/modules/schema/resolvers.ts, packages/services/api/src/modules/schema/to-graphql-schema-check.ts, packages/services/api/src/modules/shared/providers/storage.ts, packages/services/api/src/shared/mappers.ts, packages/services/storage/package.json, packages/services/storage/src/index.ts, packages/services/storage/src/schema-change-meta.ts, packages/services/storage/src/schema-change-model.ts, pnpm-lock.yaml, tsconfig.json
There is not really a reason to do that later on aside from unnecessarily increasing complexity and small performance wins when not using the schema changes...
=> refactor: inflate schema changes as early as reading from the database

deployment/services/supertokens.ts, docker/docker-compose.community.yml, docker/docker-compose.dev.yml, integration-tests/testkit/auth.ts, packages/services/server/src/graphql-handler.ts
See https://github.com/kamilkisiela/graphql-hive/issues/3332
Bumps supertoken core to v7 and cdi API usages to 4.0 (see https://app.swaggerhub.com/apis/supertokens/CDI).
=> chore: upgrade supertokens core to 7

integration-tests/tests/api/schema/delete.spec.ts, packages/libraries/cli/src/commands/schema/check.ts, packages/libraries/cli/src/commands/schema/publish.ts, packages/services/api/src/modules/alerts/providers/adapters/common.ts, packages/services/api/src/modules/alerts/providers/adapters/slack.ts, packages/services/api/src/modules/schema/module.graphql.ts, packages/services/api/src/modules/schema/providers/inspector.ts, packages/services/api/src/modules/schema/providers/models/composite-legacy.ts, packages/services/api/src/modules/schema/providers/models/composite.ts, packages/services/api/src/modules/schema/providers/models/shared.ts, packages/services/api/src/modules/schema/providers/models/single-legacy.ts, packages/services/api/src/modules/schema/providers/models/single.ts, packages/services/api/src/modules/schema/providers/registry-checks.ts, packages/services/api/src/modules/schema/providers/schema-manager.ts, packages/services/api/src/modules/schema/providers/schema-publisher.ts, packages/services/api/src/modules/schema/resolvers.ts, packages/services/api/src/modules/shared/providers/storage.ts, packages/services/storage/src/index.ts, packages/services/storage/src/schema-change-model.ts, packages/web/app/pages/[organizationId]/[projectId]/[targetId]/checks.tsx, packages/web/app/src/components/target/history/errors-and-changes.tsx, packages/web/app/src/graphql/fragments.graphql, packages/web/app/src/stories/history-page.stories.tsx
>We show “breaking changes” that are safe based on usage on the “Safe Changes” section.
I feel like it makes more sense to show them on the “Breaking Changes” section with an annotation instead (similar to screenshot attached). We actually already have the annotation “(safe based on usage)“, but having the change within Safe Changes still feels a bit misleading.
[Internal discussion](https://guild-oss.slack.com/archives/C01E8ATBQGN/p1699872922797379)
=> feat: revise breaking change presentation in web app

packages/web/app/pages/[organizationId]/[projectId]/[targetId]/checks.tsx
This fixes #3261 . The state is initialized to empty and on re-render we need to fetch the state from router's query params so that the checks are persisted.
This affects the frontend module for the checks page under target. The state for filter checks would be fetched from router's query params and would be updated when filters are changed.
=> Persist the schema filter checks as query parameters on page refresh

packages/web/app/pages/[organizationId]/[projectId]/[targetId]/checks.tsx
Closes https://github.com/kamilkisiela/graphql-hive/issues/3180
[This issue](https://github.com/kamilkisiela/graphql-hive/issues/3180) and the "Invariant: attempted to hard navigate to the same URL" issue that popped up on Sentry is solved with this PR.
This issue was that we used `checkId` instead of `schemaCheckId` in the pathname. The pathname variables must mirror the filesystem routing files...
=> fix: use same pathname parameter name as route filename

packages/services/schema/package.json, pnpm-lock.yaml
Makes stripFederationFromSupergraph less strict and remove only Federation directives
=> Update theguild/federation-composition to 0.1.4

integration-tests/tests/api/schema/publish.spec.ts, packages/services/external-composition/federation-2/package.json, packages/services/external-composition/federation-2/src/server.ts, packages/services/schema/package.json, packages/services/schema/src/orchestrators.ts, pnpm-lock.yaml
We are currently returning the supergraph instead of the schema SDL (which is what should be used by tools like graphql code generator).
=> fix: return api schema for sdl instead of supergraph schema

packages/services/api/src/modules/schema/providers/registry-checks.ts
In https://github.com/kamilkisiela/graphql-hive/pull/3439 we fixed an issue where the supergraph instead of the public API schema was stored for the SDL. However, this now started failing schema publishes and checks. By filtering out federation directive related changes within the diff command, we avoid these failures.
=> fix: omit federation related changes from diff output

packages/libraries/client/tests/usage-collector.spec.ts, packages/libraries/client/tests/usage.spec.ts
Easier to understand what the fields should look like.
=> Use inline snapshots for usage operation record fields

.changeset/old-pigs-dress.md, .changeset/twenty-adults-cough.md, packages/libraries/client/README.md, packages/libraries/client/src/index.ts, packages/libraries/client/src/internal/sampling.ts, packages/libraries/client/src/internal/types.ts, packages/libraries/client/src/internal/usage.ts, packages/libraries/client/src/samplers.ts, packages/libraries/client/tests/usage.spec.ts, packages/web/docs/src/pages/docs/api-reference/client.mdx
Compute sample rate dynamically.
If `sampler` is defined, `sampleRate` is ignored.
The `sampler` function returns a sample rate between 0 and 1.
- 0 = 0% chance of being sent
- 1 = 100% chance of being sent.
- 0.5 = 50%
- true = 100%
- false = 0%
This allows to provide a set of samplers (like "report at least once, then use sampleRate") that we can expose in graphql-hive/client
---
Adds `atLeastOnceSampler` where every operation is reported at least once, but every next occurrence is decided by the sampler.
```typescript
import { atLeastOnceSampler } from '@graphql-hive/client';
useHive({
usage: {
sampler: atLeastOnceSampler({
keyFn(ctx) {
return ctx.operationName;
},
sampler(ctx) {
return shouldOperationBeReported(ctx);
},
}),
},
});
```
---
Closes #3330
=> Dynamic sampling in GraphQL Hive client

.changeset/sweet-dots-relate.md, packages/libraries/cli/src/commands/operations/check.ts
As we don't want to allow users to pass JSON object with GraphQL Inspector specific configuration (version of @graphql-inspector/core may change over time and it could lead to breaking changes at Hive CLI level),  we prefer to control the available flags and support them long term by moving some logic into Hive CLI.
This way we are aware of the actual usage of these flags and can predict/prevent breaking change.
Closes #3356
=> Support Apollo Client directives in hive operations:check

packages/libraries/client/src/version.ts, packages/services/storage/src/index.ts
`sql.unnest` creates a variable per every column; values for each column are passed as an array.
The previous solution created too many variable and we reached the limit a few times.
Fixes #3594
=> Use sql.unnest for inserting large set or rows

packages/services/api/src/modules/alerts/resolvers.ts
GraphQL-JIT does not understand `{ foo: Promise, bar: Promise}`
=> await updated project and added alert channel

packages/services/api/src/modules/alerts/providers/adapters/slack.ts, packages/services/api/src/modules/alerts/providers/alerts-manager.ts, packages/web/docs/src/pages/docs/management/projects.mdx
- explain private channels in docs
- add channel name to the printed log
=> Fix Slack's "goodbye" message to the deleted channel

codegen.mts, packages/services/api/package.json, packages/services/api/src/modules/schema/module.graphql.ts, packages/services/api/src/modules/schema/providers/orchestrators/federation.ts, packages/services/api/src/modules/schema/providers/schema-manager.ts, packages/services/api/src/modules/schema/resolvers.ts, packages/services/api/src/modules/shared/providers/storage.ts, packages/services/api/src/shared/entities.ts, packages/services/storage/src/index.ts, packages/web/app/pages/[organizationId]/[projectId]/view/settings.tsx, packages/web/app/src/components/project/settings/external-composition.tsx, packages/web/app/src/components/project/settings/native-composition.tsx, packages/web/app/src/components/v2/docs-note.tsx, packages/web/docs/src/pages/product-updates/2023-10-10-native-federation-2.mdx, pnpm-lock.yaml
Adds "Native Composition" component to project settings to enable / disable native composition.
User will see one of the following statuses:
We check compatibility by comparing the most recent supergraphs from all project's targets.
If all of them are identical: COMPATIBLE
If some of them are not: NOT COMPATIBLE
if project has no supergraphs: UNKNOWN
=> Allow to enable native Federation composition

packages/services/api/src/modules/schema/providers/models/composite-legacy.ts, packages/services/api/src/modules/schema/providers/models/composite.ts, packages/services/api/src/modules/schema/providers/models/single-legacy.ts, packages/services/api/src/modules/schema/providers/models/single.ts, packages/services/api/src/modules/schema/providers/registry-checks.ts, packages/services/api/src/modules/schema/resolvers.ts
related https://github.com/kamilkisiela/graphql-hive/issues/3491
This is a small improvement, that avoids unnecessary composition calls for the registry checks "diff" and "schemaPolicy". There can be additional improvements, as stated in https://github.com/kamilkisiela/graphql-hive/issues/3491, this however, would require more refactoring. This change is a quick win and helps for what I am working on in https://github.com/kamilkisiela/graphql-hive/pull/3506
=> refactor: use composition result for diff and policy checks

packages/services/api/src/modules/schema/providers/models/composite-legacy.ts, packages/services/api/src/modules/schema/providers/models/composite.ts, packages/services/api/src/modules/schema/providers/models/single-legacy.ts, packages/services/api/src/modules/schema/providers/models/single.ts, packages/services/api/src/modules/schema/providers/registry-checks.ts, packages/services/api/src/modules/schema/providers/schema-publisher.ts
Closes https://github.com/kamilkisiela/graphql-hive/issues/3491
This adds some more code, however, it is for a good reason. So far the diff registry check would attempt to compose the existing schema version from scratch, which is not necessary, as for newer schemas we always have the composite schema SDL already in our database. Thus, we can skip attempting the composition for most scenarios.
In addition, this is useful for https://github.com/kamilkisiela/graphql-hive/pull/3506, as we want to diff all contracts (and we also always have the latest contract version within our database; and can thus reduce multiple HTTP calls to the composition service.. N = count of contract definitions).
=> refactor: use sdl as input for diff registry check instead of composing

packages/web/docs/src/pages/docs/self-hosting/get-started.mdx
Removes a duplicated reference of bounded ports
docs update
see above
N/A
=> docs: remove duplicated bounded ports reference

packages/services/schema/src/lib/federation-tag-extraction.spec.ts, packages/services/schema/src/lib/federation-tag-extraction.ts, packages/services/schema/src/orchestrators.ts
Before we do the composition of contracts, we pre-process the subgraphs, remove `@tag` directives, and add `@inaccessible` directives based on the contract filter definition.
```graphql
type Foo {
a: String @tag(name: "a")
b: String
}
```
--apply “Filter: include a tag with the name `a`” transform-->
```graphql
type Foo {
a: String
b: String @inaccessible
}
```
The issue that occurred here is that, if all types of an object, interface, input object, or enum type are `@inaccessible`, the composition fails as in the public GraphQL schema there would be types without fields/properties, which is not a valid GraphQL schema.
```graphql
type Foo {
a: String
b: String
}
```
--apply “Filter: include a tag with the name `a`” transform-->
```graphql
type Foo {
a: String @inaccessible
b: String …
```
=> feat: apply inaccessible directive based on subgraph fields

packages/libraries/router/src/registry.rs, packages/web/docs/src/pages/docs/integrations/apollo-router.mdx
Make it easier to as non root by allowing the user to specify where to download the supergraph schema file from the hive cdn. Typically, /tmp is writable and is a suitable place to download the file to. Alternatively, if using kubernetes, one could create an emptyDir volume and download the schema file to there.
The change affects the router rust package, specifically the registry module.
=> feat: Make schema file path configurable in router registry plugin

.changeset/eight-swans-teach.md, packages/libraries/client/package.json, packages/libraries/client/src/yoga.ts, packages/libraries/client/tests/yoga.spec.ts, packages/services/server/package.json, pnpm-lock.yaml
Requires https://github.com/dotansimha/graphql-yoga/pull/3164 for properly handling response cache compatibility.
Closes https://github.com/kamilkisiela/graphql-hive/issues/3807
=> fix: do not report operations that don't pass GraphQL validation

integration-tests/tests/api/schema/check.spec.ts, packages/services/api/src/modules/schema/providers/models/composite-legacy.ts, packages/services/api/src/modules/schema/providers/models/composite.ts, packages/services/api/src/modules/schema/providers/models/shared.ts, packages/services/api/src/modules/schema/providers/models/single-legacy.ts, packages/services/api/src/modules/schema/providers/models/single.ts, packages/services/api/src/modules/schema/providers/schema-publisher.ts, packages/services/api/src/modules/schema/providers/schema-version-helper.ts, packages/services/api/src/modules/shared/providers/storage.ts, packages/services/storage/src/index.ts
An error popped up within our error monitoring system regarding this code
We made the wrong assumption that a skipped schema check is always successful. This resolves it by determining the schema check result based on the schema version we compared against.
=> fix: correctly handle schema check composition skip

packages/services/api/src/modules/schema/module.graphql.ts, packages/services/storage/src/schema-change-model.ts, packages/web/app/pages/[organizationId]/[projectId]/[targetId]/checks.tsx
Some errors (like GraphQL errors) don't have `ruleId` defined (it's `null`), the same applies to `line` and `column` as well.
=> Relax SchemaPolicyWarningModel

integration-tests/tests/schema/contracts.spec.ts, packages/services/api/src/modules/schema/providers/registry-checks.ts, packages/services/schema/src/lib/reachable-type-filter.spec.ts, packages/services/schema/src/lib/reachable-type-filter.ts, packages/services/schema/src/orchestrators.ts
Apollo router will fail to process and startup a supergraph that contains `@inaccessible` on federation types.
This changes the federation contract filtering to exclude the federation types from being marked as inaccessible.
Closes https://github.com/kamilkisiela/graphql-hive/issues/4013
=> fix: avoid @inaccessible directive on apollo federation supergraph types

packages/services/api/src/modules/organization/providers/organization-manager.ts, packages/services/api/src/modules/organization/resolvers.ts, packages/services/api/src/modules/project/resolvers.ts, packages/services/api/src/modules/shared/providers/emails.ts, packages/services/api/src/modules/target/resolvers.ts, packages/services/api/src/shared/entities.ts
Restrict organization/project/target names to alphanumerical characters, spaces and . , _ - / &.
Espace HTML in emails.
=> Restrict names to alphanum chars, spaces . , _ - / & and escape HTML in email bodies

packages/services/api/package.json, packages/services/api/src/modules/operations/providers/operations-manager.ts, packages/services/api/src/modules/schema/providers/registry-checks.ts, packages/services/api/src/modules/schema/providers/schema-manager.ts, packages/services/api/src/modules/schema/providers/schema-version-helper.ts, packages/services/schema/package.json, pnpm-lock.yaml
There's a possibility that the composite schema SDL contains parts of the spergraph spec. This is a problem because we want to show the public schema to the user, and the supergraph spec is not part of that. This may happen when composite schema was produced with an old version of transformSupergraphToPublicSchema or when supergraph sdl contained something new.
the-guild-org/federation#44
=> Auto-fix persisted composite schema sdl

packages/libraries/client/src/internal/types.ts
It was originally on `operationStore` property and moved here probably because of incorrect merge conflict resolution.
=> Remove `@deprecated` from Hive.dispose()

packages/web/app/src/components/v2/modals/delete-organization.tsx
https://github.com/kamilkisiela/graphql-hive/issues/3706
Changed route to `/` after delete organization:
1. When we have 1 organization or more: the router will navigate to the last organization.
2. When we have 0 organization, the router will navigate to `/org/new`
=> Fixed: Deletion of organization results in error

.eslintrc.cjs, packages/services/api/src/modules/operations/providers/operations-reader.ts, packages/web/app/package.json, packages/web/app/pages/[organizationId]/[projectId]/[targetId]/explorer.tsx, packages/web/app/pages/[organizationId]/[projectId]/[targetId]/explorer/[typename].tsx, packages/web/app/pages/[organizationId]/[projectId]/[targetId]/explorer/unused.tsx, packages/web/app/pages/[organizationId]/[projectId]/[targetId]/insights.tsx, packages/web/app/pages/[organizationId]/[projectId]/[targetId]/insights/[operationName]/[operationHash].tsx, packages/web/app/pages/[organizationId]/[projectId]/[targetId]/insights/client/[name].tsx, packages/web/app/pages/[organizationId]/[projectId]/[targetId]/insights/schema-coordinate/[coordinate].tsx, packages/web/app/src/components/layouts/target.tsx, packages/web/app/src/components/target/explorer/filter.tsx, packages/web/app/src/components/target/explorer/provider.tsx, packages/web/app/src/components/target/history/errors-and-changes.tsx, packages/web/app/src/components/target/insights/Filters.tsx, packages/web/app/src/components/target/insights/List.tsx, packages/web/app/src/components/target/insights/Stats.tsx, packages/web/app/src/components/ui/calendar.tsx, packages/web/app/src/components/ui/date-range-picker.tsx, packages/web/app/src/lib/date-math.spec.ts, packages/web/app/src/lib/date-math.ts, packages/web/app/src/lib/hooks/use-date-range-controller.ts, packages/web/app/src/lib/hooks/use-local-storage.ts, pnpm-lock.yaml
Closes https://github.com/kamilkisiela/graphql-hive/issues/3178
Closes https://github.com/kamilkisiela/graphql-hive/issues/3836
=> feat: granular date filtering in explorer

packages/services/api/src/modules/operations/providers/operations-manager.ts, packages/services/api/src/modules/operations/providers/operations-reader.ts, packages/services/api/src/modules/operations/resolvers.ts
Filtering insights by Clients will filter all page sections except the Clients section.
=> Apply clients filter to Insight's Clients section

package.json, patches/slonik@30.4.4.patch, pnpm-lock.yaml
Error: read ETIMEDOUT (db connection) causes uncaught exception that leads to teardown of a process due to lack of pool.on('error') handler in Slonik.
=> Patch slonik and add pool.on(error) handler

packages/services/api/src/modules/integrations/providers/github-integration-manager.ts
Make `isOctokitRequestError` checking less strict (`instanceof` is too strict as there could be many versions of the package).
=> Inform users that their Github organization has IP allow list enabled

packages/services/api/src/modules/billing/module.graphql.ts, packages/services/api/src/modules/billing/resolvers.ts, packages/web/app/pages/[organizationId]/view/manage-subscription.tsx, packages/web/app/pages/[organizationId]/view/subscription.tsx, packages/web/app/src/components/organization/billing/BillingPaymentMethod.tsx
=> Bug fixes for subscription management page

.changeset/eleven-queens-share.md, integration-tests/tests/api/artifacts-cdn.spec.ts, packages/libraries/client/src/apollo.ts, packages/libraries/client/src/gateways.ts, packages/libraries/client/src/internal/utils.ts, packages/libraries/core/src/hash.ts, packages/libraries/external-composition/src/index.ts, packages/migrations/src/actions/2023.01.17T10.46.28.import-legacy-s3-keys-to-database.ts, packages/services/api/src/modules/organization/providers/organization-manager.ts, packages/services/api/src/modules/schema/providers/schema-helper.ts, packages/services/api/src/modules/schema/providers/schema-publisher.ts, packages/services/api/src/modules/schema/resolvers.ts, packages/services/api/src/modules/shared/providers/crypto.ts, packages/services/api/src/shared/helpers.ts, packages/services/api/src/shared/schema.ts, packages/services/cdn-worker/tests/cdn.spec.ts, packages/services/schema/src/cache.ts, packages/services/schema/src/index.ts, packages/services/schema/src/orchestrators.ts, packages/services/tokens/src/api.ts, packages/services/usage-ingestor/src/processor.ts, packages/services/usage/src/buffer.ts, packages/services/usage/src/usage.ts, packages/services/webhooks/src/jobs.ts
Using graphql client with cloudflare workers and nodejs_compat, a lot of errors due to the node crypto import prevents building without patching core and client.
This PR adds a node specifier to the crypto imports.
This change has no side effects and shouldn't require a checklist.
=> chore: use node import specifier for crypto

deployment/services/schema.ts, packages/services/schema/src/index.ts, packages/services/schema/src/orchestrators.ts
In case of unexpected errors, store composition result for a short time (it's one minute in production), instead of 24h.
I changed the prefix from `schema-service` to `schema-service-v2` to nuke the Redis cache.
I also reduced the long time from 24h to 12h (Redis storage should decrease).
=> Use short TTL for composition result when unexpected error is detected

.eslintrc.cjs
> 'divide-y-[1px]' could be replaced by 'divide-y-DEFAULT'
I believe I prefer `divide-y-[1px]` over `divide-y-DEFAULT` :))
=> Disable tailwindcss/no-unnecessary-arbitrary-value rule

integration-tests/tests/api/schema/composition-federation-2.spec.ts, integration-tests/tests/api/schema/delete.spec.ts, integration-tests/tests/api/schema/external-composition.spec.ts, integration-tests/tests/api/schema/publish.spec.ts, integration-tests/tests/models/federation.spec.ts, packages/services/api/src/modules/schema/providers/models/composite.ts, packages/services/api/src/modules/schema/providers/models/single.ts, packages/services/api/src/modules/schema/providers/registry-checks.ts, packages/services/api/src/modules/schema/providers/schema-manager.ts, packages/services/api/src/modules/schema/providers/schema-publisher.ts, packages/services/storage/src/index.ts, packages/web/app/src/components/project/settings/external-composition.tsx, packages/web/app/src/components/project/settings/native-composition.tsx
Every new project will use native composition by default.
It's possible to opt-out in project settings.
--
It's also no longer required to update organization's `compareToPreviousComposableVersion` feature flag as it no longer has any effect when native composition is detected.
=> Enable Native Composition by default for newly created projects

packages/services/api/src/modules/policy/module.graphql.ts, packages/services/api/src/modules/policy/providers/schema-policy.provider.ts, packages/services/api/src/modules/policy/resolvers.ts, packages/web/app/pages/[organizationId]/[projectId]/view/policy.tsx
When a user has `project.settings` access but not `organization.settings`, Policy page fails to load as its GraphQL query lacks permissions to read schema policy of an organization (`Organization.schemaPolicy` needs `organization.settings`).
To fix it, I added `Project.parentSchemaPolicy` field that resolves the same value, but expects `project.settings` access.
=> Fix Policy view for Project

packages/web/app/src/components/target/explorer/filter.tsx
We don't aggregate data hourly or minutely for schema coordinates, so no data to display for Last X hours.
=> Limit date range filter of Explorer to days

.github/workflows/prettier.yaml
Sometimes I make changes directly from github.com and I don't want to do checkout the branch and run prettier on my machine.
With this workflow, we can trigger `prettier --write + git commit + git push <branch>`
=> Github Workflow to run prettier --write and commit to a branch

packages/migrations/src/clickhouse-actions/008-daily-operations-log.ts, packages/migrations/src/clickhouse.ts, packages/migrations/src/scripts/008-cloud.ts
Make it possible to quickly count operations reported by organization X from last N days without dealing with targets.
=> Add daily aggregation of requests per organization

packages/web/docs/src/pages/docs/integrations/apollo-server.mdx
Emphasize that both headers must be present in order for Apollo Server to pass this information to Hive.
I was not able to have metadata about clients show up in Hive. It turns out I missed the `and` in the previous sentence. I just want to emphasize this fact more.
N/A
N/A
=> Update Apollo Server integrations docs

packages/services/schema/src/lib/federation-tag-extraction.spec.ts, packages/services/schema/src/lib/federation-tag-extraction.ts, packages/services/schema/src/orchestrators.ts
The `applyTagFilterOnSubgraphs` logic was not handling the case where the `include` field was an empty Set. It only checked if the `include` field was `undefined` or `null`. This caused all fields to be inaccessible.
Instead of `null | Set<string>` I refactored it to just accept `Set<string>` and check for its size.
=> fix: empty "include" made all fields inaccessible

docker/docker-compose.community.yml
I mean... it's lightweight, consumes less resources, faster startup times and no need to spin up two containers.
=> Use redpanda instead of Kafka+Zookeeper in community docker compose file

packages/web/app/src/components/ui/date-range-picker.tsx
Task: #4229  
Enhance DateRangePicker to dynamically suggest time presets while respecting valid time units specified by the user.
https://github.com/kamilkisiela/graphql-hive/assets/37614975/faee8145-23dd-45a4-9b55-5311cd560a2d
The list of suggestions based on the `dynamicPresets` prop.
=> new feature: date ranger filter suggest custom number interval

packages/web/app/pages/[organizationId]/[projectId]/[targetId]/settings.tsx, packages/web/app/pages/[organizationId]/[projectId]/view/policy.tsx, packages/web/app/pages/[organizationId]/[projectId]/view/settings.tsx, packages/web/app/pages/[organizationId]/view/policy.tsx, packages/web/app/pages/[organizationId]/view/settings.tsx, packages/web/app/src/components/user/settings.tsx
Related to #4651 
Better user experience after save - got toast feedback
Added to:
- On save Profile settings
- On save Organization Schema Policy
- On save Organization Name
- On save Project Schema Policy
- On save Project Name
- On save Target Name
- On save GraphQL Endpoint URL
- On save Conditional Breaking Changes
- On save Extend Your Schema
https://github.com/kamilkisiela/graphql-hive/assets/37614975/e5a0767f-1eb5-4c4e-a22c-3dea069fe96b
=> Toast on save for better user feedback

packages/web/app/src/components/ui/date-range-picker.tsx
Problem: I want to quickly pick "Last 30 days", but because the list is super long I need to scroll and find it.
Reducing the number of options helps to quickly switch between date ranges, without scrolling.
Having `last 5 minutes` next to `last 10 minutes` and to `last 15 minutes` is too granular and in my opinion really not needed.
I feel like showing:
```
Last 5 minutes
Last 10 minutes
Last 15 minutes
Last 30 minutes
Last 1 hour
Last 3 hours
Last 6 hours
Last 12 hours
Last 24 hours
Last 2 days
Last 3 days
Last 7 days
Last 14 days
Last 30 days
Last 60 days
Last 90 days
Last 6 months
Last 1 year
```
is A BIT too much :D
The PR displays only:
```
Last 30 minutes
Last 1 hour
Last 1 day
Last 7 days
Last 14 days
Last 30 days
Last 90 days
Last 6 months
Last 1 year
```
=> Reduce the number of presets in date range picker

.eslintrc.cjs, packages/services/api/src/modules/operations/providers/operations-reader.ts, packages/services/api/src/modules/operations/providers/sql.ts, packages/web/app/src/pages/target-explorer-deprecated.tsx, packages/web/app/src/pages/target-explorer-unused.tsx, packages/web/app/src/pages/target-insights-client.tsx, packages/web/app/src/pages/target-insights-coordinate.tsx
- Bring https://github.com/kamilkisiela/graphql-hive/pull/4481 to live
- Use `clients_{minutely,hourly}`, `coordinates_{minutely,hourly}` tables
- Reuse ClickHouse SELECT statements by making the table name dynamic.
> [!CAUTION]
> Merge 30 days after #4481 is deployed to production.
=> Reuse ClickHouse SELECT statements

.eslintrc.cjs, packages/services/api/src/modules/auth/module.graphql.ts, packages/services/api/src/modules/auth/resolvers.ts, packages/web/app/src/components/admin/AdminStats.tsx, packages/web/app/src/components/layouts/project.tsx, packages/web/app/src/components/layouts/target-selector.tsx, packages/web/app/src/components/layouts/target.tsx, packages/web/app/src/components/organization/Permissions.tsx, packages/web/app/src/components/organization/members/list.tsx, packages/web/app/src/components/organization/members/migration.tsx, packages/web/app/src/components/v2/modals/change-permissions.tsx, packages/web/app/src/components/v2/modals/transfer-organization-ownership.tsx, packages/web/app/src/lib/access/organization.ts, packages/web/app/src/lib/access/target.ts, packages/web/app/src/lib/urql-cache.ts, packages/web/app/src/lib/urql.ts, packages/web/app/src/pages/auth.tsx, packages/web/app/src/pages/organization-policy.tsx, packages/web/app/src/pages/organization-transfer.tsx, packages/web/app/src/pages/project-policy.tsx, packages/web/app/src/pages/target-laboratory.tsx, packages/web/app/src/pages/target-settings.tsx, packages/web/app/src/router.tsx, pnpm-lock.yaml, rules/graphql-require-selection.cjs, rules/index.cjs
Urql's normalized cached depends on `__typename` and `id` fields. The `id` is not unique as it really is just `User.id`.
This PR adds `temporaryFixId` field that is globally unique. It fixes an issue where cache entry of `Member:id` is being overwritten by other instances of `Member`, because of lack of uniqueness.
Next PR will actually fix it and remove the workaround.
=> Temporary fix - Member.id is not globally unique

.vscode/settings.json
When you press `.` followed by `.` in a GraphQL template literal in vscode it causes some weird shit. https://github.com/0no-co/GraphQLSP/issues/268
^
=> chore: update editor config for sane fragment spread writing

codegen.mts, packages/services/api/src/modules/schema/module.graphql.mappers.ts, packages/services/api/src/shared/mappers.ts
Relates to https://github.com/kamilkisiela/graphql-hive/issues/4741
This PR moves `schema` module related mappers to live next to `module.graphql.ts` file. This move follows the convention of Server Preset, making it easier to make the switch
This PR only affects types so it doesn't have any runtime impact. This first PR is intentionally small to help me understand the process end-to-end and detect issues quicker. Future PRs may be bigger.
=> Move `schema` mappers to `schema` module

packages/migrations/src/clickhouse-actions/009-ttl-1-year.ts, packages/migrations/src/clickhouse.ts, packages/migrations/src/environment.ts, packages/migrations/src/index.ts
Adds a migration (Cloud only) to store rows of daily agg views for a full year.
=> Keep daily aggregation rows for 1 year

integration-tests/testkit/flow.ts, integration-tests/testkit/seed.ts, integration-tests/tests/api/target/usage.spec.ts, packages/services/rate-limit/src/limiter.ts, packages/services/usage/src/index.ts
Adds a test to ensure proper propagation of organization's data retention period.
Fixes the missing target id -> organization id lookup table, which caused the system to use the default 30 days for TTL.
Related #4830
=> Ensure correct data retention propagation

packages/services/rate-limit/src/limiter.ts, packages/services/usage/src/index.ts
Log errors whenever we hit a scenario when default data retention period is used for a usage report.
=> Capture a logic path that leads to default TTL

packages/web/app/src/pages/target-settings.tsx
The value was hardcoded and selecting a day range higher than 30 days was impossible.
This uses the remote value instead.
=> fix: breaking change day retention picker

packages/web/app/src/components/ui/docs-note.tsx
=> fix lost whitespace in `<DocsLink />` component

package.json
We should not require having Helm installed for running `pnpm typecheck`.
Excludes `@hive/deployment` from the typecheck.
=> chore: filter deployment from typecheck

packages/web/app/src/components/target/settings/schema-contracts.tsx
Every time prettier runs, the amount of \ doubles
```css
after:content-['\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\200b']
```
=> Fix constantly growing \200b backslash escaping

packages/web/app/src/components/layouts/target.tsx, packages/web/app/src/components/ui/form.tsx, packages/web/app/src/components/ui/page-content-layout.tsx, packages/web/app/src/components/ui/use-toast.ts, packages/web/app/src/index.css, packages/web/app/src/pages/target-history.tsx, packages/web/app/src/pages/target-laboratory.tsx
nothing happens if an operation is not saved
previous experience is:
https://github.com/kamilkisiela/graphql-hive/assets/7361780/cb42498f-c343-464f-816a-0a0b8a57e70a
=> [laboratory] hide `Share Operation` GraphiQL toolbar button if operation is not yet saved

package.json, packages/web/app/src/components/layouts/target.tsx, packages/web/app/src/components/ui/form.tsx, packages/web/app/src/components/ui/page-content-layout.tsx, packages/web/app/src/components/ui/use-toast.ts, packages/web/app/src/index.css, packages/web/app/src/pages/target-history.tsx, packages/web/app/src/pages/target-laboratory.tsx, patches/graphiql@3.3.0.patch, pnpm-lock.yaml
https://github.com/kamilkisiela/graphql-hive/assets/7361780/a42a25f8-014d-46d3-9bc6-2a1a3b9bb885
=> [laboratory] remove `Merge fragments into query`, `Copy query` toolbar buttons, move `Prettify query` to end

packages/services/usage-common/src/raw.ts, packages/services/usage/__tests__/usage.spec.ts, packages/services/usage/src/usage.ts
Every time a report was too big and split into two or more reports, the organization id was missing, causing an operation count in the Subscription page to be slightly off.
Every other page that shows usage info, uses different tables, so not affected at all.
=> fix: keep organization id when splitting the report

.changeset/good-hairs-deliver.md, .changeset/selfish-shoes-pump.md, .changeset/tidy-worms-add.md, packages/libraries/apollo/src/index.ts, packages/libraries/apollo/tests/apollo.spec.ts, packages/libraries/cli/package.json, packages/libraries/cli/src/base-command.ts, packages/libraries/cli/src/commands/artifact/fetch.ts, packages/libraries/core/package.json, packages/libraries/core/src/client/gateways.ts, packages/libraries/core/src/client/http-client.ts, packages/libraries/core/src/index.ts, packages/libraries/core/src/version.ts, packages/libraries/core/tests/gateways.spec.ts, packages/libraries/yoga/package.json, pnpm-lock.yaml
- Adds retry logic to http client of `@graphql-hive/core`.
- Reuse the retry logic of core's http client in `@graphql-hive/apollo` and `@graphql-hive/yoga`
- Adds a retry to a GET request done by the `artifact:fetch` CLI command
=> Shared HTTP client with retries

codegen.mts, package.json, pnpm-lock.yaml
Server preset v0.10 has built-in `schema-ast` support. So, this PR uses Server Preset instead of `schema-ast` to merge schema
=> Bump server preset to v0.10 and remove `schema-ast` plugin

scripts/serializers/cli-output.ts
Our integration tests verify that the web app's URLs in the CLI output are correct. Previously, we used a hardcoded port number, but this PR makes it dynamic, allowing any port number to be accepted.
=> integration-tests: dynamic port handling for web app URL verification

packages/web/app/src/components/v2/modals/transfer-organization-ownership.tsx
```graphql
type Member {
user: User!
}
```
We sometimes used Member, sometimes User. The lack of type safety in Combobox led to a bug.
=> Fix organization transfer form

packages/web/app/src/server/index.ts
> Allows credentials to be used in requests
> We ran into an issue after updating Hive, our cors preflight request got redirected to our SSO page due to missing cookies. This should fix that and allow us to update
Continues #5189
=> Configures the Access-Control-Allow-Credentials CORS header

deployment/services/proxy.ts, deployment/utils/reverse-proxy.ts, pnpm-lock.yaml
This change is using the Local config for rate-limit: https://projectcontour.io/docs/1.29/config/rate-limiting/#local-rate-limiting
We might want to use the Global config with a proper service in the future. 
This PR also enabled sticky sessions for Contour (requests for the same user session will be routed to the same container), we can safely use the Local option at the moment.
=> Apply rate-limit config to `auth-api` routes, using Contour

packages/services/api/package.json, packages/services/schema/package.json, pnpm-lock.yaml
Unknown types are now always reported as GraphQLError (previously in some logic paths, it was an
exception).
=> chore: update @theguild/federation-composition dependency to v0.12.1

cypress/e2e/app.cy.ts, cypress/support/commands.ts, docker/configs/oidc-server-mock/users-config.json, integration-tests/tests/api/oidc-integrations/crud.spec.ts, packages/migrations/src/actions/2024.07.16T13-44-00.oidc-only-access.ts, packages/migrations/src/run-pg-migrations.ts, packages/services/api/src/modules/oidc-integrations/module.graphql.ts, packages/services/api/src/modules/oidc-integrations/providers/oidc-integrations.provider.ts, packages/services/api/src/modules/oidc-integrations/resolvers.ts, packages/services/api/src/modules/organization/providers/organization-manager.ts, packages/services/api/src/modules/shared/providers/storage.ts, packages/services/api/src/shared/entities.ts, packages/services/storage/src/db/types.ts, packages/services/storage/src/index.ts, packages/web/app/package.json, packages/web/app/src/components/organization/settings/oidc-integration-section.tsx, packages/web/app/src/components/ui/separator.tsx, packages/web/app/src/lib/hooks/use-clipboard.ts, packages/web/app/src/pages/organization-join.tsx, packages/web/docs/src/pages/docs/management/organizations.mdx, packages/web/docs/src/pages/docs/management/sso-oidc-provider.mdx, pnpm-lock.yaml
When enabled (default):
- existing non-OIDC members keep their access (non-OIDC members can be removed)
- non-OIDC members can't join an organization
I will write a product update in a separate PR, otherwise it would be deployed before the feature lands in prod.
=> Allow to limit organization access to OIDC accounts only

.github/workflows/release-alpha.yaml
Same reason as in #5246
The snapshot release pipeline is broken.
=> Pin node to v22.4 in release-alpha.yaml

docker/docker-compose.dev.yml
After applying the constraints from https://github.com/kamilkisiela/graphql-hive/pull/5177 I constantly see ClickHouse crashing and running OOM locally.
Just bumps the constraints to a value that works for me. 1gb seems to be not enough. I still encountered a lot of crashes.
=> chore: allow more memory for clickhouse

.github/workflows/build-and-dockerize.yaml
Let's start uploading the persisted documents to r2, so we can access them from within our deployment pipeline for publishing them to Hive. This is a pre-requisite for https://github.com/kamilkisiela/graphql-hive/pull/4866
−
=> feat: upload persisted documents from app to R2

.github/workflows/graphql-app-document-check.yaml, .github/workflows/pr.yaml, .gitignore, codegen.mts
Prerequisite for using app deployments on Hive app in a safe way.
App deployments require that the documents that will be published to an app deployment are valid against the latest valid schema version within Hive.
This also affects our Hive app. If we try publishing a GraphQL document during the deployment that uses a field not yet available in the Hive schema, the deployment process would fail.
A PR branch should use the `hive operations:check` command to ensure that merging a PR would not break the persisted document upload.
For contributors to Hive, this will now require people to split up changes that alter both the GraphQL API schema and app documents into separate pull requests.
=> chore: app operation check command

integration-tests/tests/api/app-deployments.spec.ts, packages/services/api/src/modules/app-deployments/module.graphql.ts, packages/services/api/src/modules/app-deployments/providers/app-deployments.ts, packages/services/api/src/modules/app-deployments/resolvers/Mutation/activateAppDeployment.ts
Publishing an app deployment that is already active should not fail by default for unblocking rollbacks within CD pipelines.
=> feat: skip app publish if app is active

.changeset/bright-lobsters-smell.md, integration-tests/testkit/cli.ts, integration-tests/tests/cli/dev.spec.ts, packages/libraries/cli/package.json, packages/libraries/cli/src/commands/dev.ts, packages/services/api/src/modules/schema/module.graphql.ts, packages/web/docs/src/pages/docs/api-reference/cli.mdx, pnpm-lock.yaml
Closes #5113
Changes the default behavior of `hive dev` command. Now schema composition is done locally, without substituting subgraphs available in the registry.
I added `--remote` flag to the `hive dev` command to mimic the previous behavior.
The `$ hive dev` command was marked as "work in progress" (stated in the command description).
That's why I'm are not considering this a breaking change, but a minor change.
**_Before:_**
The `hive dev` command would substitute subgraphs available in the registry with their local counterparts, performing schema composition over the network according to your project's configuration.
**_After:_**
The `hive dev` command will now perform schema composition locally, without substituting subgraphs available in the registry. This is the default behavior. …
=> Perform local schema composition in the hive dev command

.github/workflows/build-and-dockerize.yaml, deployment/index.ts, deployment/package.json, deployment/services/app.ts, deployment/utils/publish-graphql-schema.ts, packages/services/server/src/graphql-handler.ts, pnpm-lock.yaml
It is not recommended that the GraphQL schema be published from the actual service. Instead, we want to do it within the CD pipeline.
- Upload schema.graphql to R2
- Use CLI docker container for publishing schema after API has been deployed
- Stop publishing schema from within the service
Internal deployment counter-part: https://github.com/the-guild-org/graphql-hive-deployment/pull/1413
=> chore: publish graphql schema as pulumni action

.github/workflows/dockerize-cli.yaml, .github/workflows/release-alpha.yaml, .github/workflows/release-stable.yaml, docker/cli.dockerfile, docker/docker.hcl
Having docker images for alpha releases is nice and we want to use them within our pulumi deployment script for pending features.
This publishes a docker image with the same tag as the snapshot release listed version.
```
docker run ghcr.io/kamilkisiela/graphql-hive/cli:0.39.0-alpha-20240724164620-5e8722409ceed454769143c20c0b52bbd2fa50b4 \
--version
@graphql-hive/cli/0.39.0-alpha-20240724164620-5e8722409ceed454769143c20c0b52bbd2fa50b4 linux-arm64 node-v22.4.1
```
~~Problem here is that `--version` shows the wrong version. I think we should change the docker step to use `npm install --global @graphql-hive/cli@version`.~~ Fixed since we now `npm install` the version within the image.
=> chore: publish CLI docker images for alpha versions 

packages/libraries/cli/bin/dev, packages/libraries/cli/bin/dev.cmd, packages/libraries/cli/bin/run, packages/libraries/cli/bin/run.cmd, packages/libraries/cli/package.json
It's sub sub sub dependency and from a CLI perspective, it's really not relevant.
=> Hide punycode deprecation warning in CLI

.changeset/wild-horses-swim.md, packages/libraries/apollo/src/version.ts, packages/libraries/core/src/client/http-client.ts, packages/libraries/core/src/version.ts, packages/libraries/core/tests/http-client.spec.ts, packages/libraries/core/tests/reporting.spec.ts, packages/libraries/core/tests/usage.spec.ts, packages/libraries/envelop/src/version.ts, packages/libraries/yoga/src/version.ts, packages/libraries/yoga/tests/yoga.spec.ts
Fixed a logging issue where both initiated requests and successful responses were being recorded. This was causing the logs to be filled with unnecessary information and affected `hive artifact:fetch --artifact` command.
=> fix: do not log initiated requests and successful responses

.eslintrc.cjs, .vscode/settings.json, packages/web/app/src/components/target/settings/schema-contracts.tsx, packages/web/app/src/components/ui/calendar.tsx, packages/web/app/src/components/ui/checkbox.tsx, packages/web/app/src/components/ui/command.tsx, packages/web/app/src/components/ui/dropdown-menu.tsx, packages/web/app/src/components/ui/radio-group.tsx, packages/web/app/src/components/ui/spinner.tsx, packages/web/app/src/components/ui/switch.tsx, packages/web/app/src/stories/schema-filter.stories.tsx
I noticed [VSCode Tailwind Intellisense](https://marketplace.visualstudio.com/items?itemName=bradlc.vscode-tailwindcss) doesn't adorn and autocomplete inside `cn` and `cva` function calls, so I updated the config to let it know about all the functions that concat class names in the project.
Also added `cn` to the list of callees for the Tailwind ESLint.
`cva` and `clsx` were included by default ([eslint-plugin-tailwindcss/util/settings.js#L24](https://github.com/francoismassart/eslint-plugin-tailwindcss/blob/c05d17c3849d347981a9f397d0141daac7f5fbee/lib/util/settings.js#L24)).
=> Configure VSCode Tailwind extension to work in cva and cn args

.eslintrc.cjs, packages/web/app/src/components/organization/members/common.tsx
The `cmdk` library has an issue with `Item` element containing double quotes or new lines in its children. The new version of `cmdk` contains a fix, but after upgrading, it introduces another issue related to the service filter in /:org/:project/:target view (opening a Command throws an exception).
=> Fix Member Role selector

packages/services/api/src/modules/operations/providers/operations-reader.ts, packages/services/api/src/modules/shared/providers/http-client.ts
Moves the where condition to the inner query. Reduces both memory and latency by 8 times. We got a few requests with 504s.
=> Optimize get_top_operations_for_types query

packages/web/docs/src/components/ecosystem-management.tsx, packages/web/docs/src/components/info-card.tsx, packages/web/docs/src/components/landing-page.tsx
I fixed the missing border radius on cards earlier today, but I added it to _all the cards_ instead of just the 3 that needed it.
This PR moves the className, so now the cards that need to be rounded are still rounded and the cards that need to have a straight border have a straight border.
=> Move the rounded border class to a proper place

packages/services/api/src/modules/operations/providers/operations-reader.ts, packages/services/api/src/shared/helpers.ts
We are hitting some limits where ClickHouse rejects the SQL query because the HTTP query string becomes too long due to many parameters (aka schema coordinates) being passed. 
```
Poco::Exception. Code: 1000, e.code() = 0, HTML Form Exception: Field value too long (version 24.5.1.22926 (official build))
```
This introduces a maximum batch size per batch within the `batchBy` helper function. With that we will be sending more queries in total, however, we will not exceed the limit.
Note: This fix is based on the amount of passed schema coordinates. However, someone could still have a single schema coordinate that is hundreds of characters long which could still cause this issue.
The 100% correct solution would be keeping track of the length of the query string (query + parameters) and then …
=> feat: batch group maximum sizes

.changeset/healthy-pears-look.md, packages/libraries/apollo/tests/apollo.spec.ts, packages/libraries/core/src/client/agent.ts, packages/libraries/yoga/tests/yoga.spec.ts, pnpm-lock.yaml
Usage reports were previously only sent when the app was disposed or when the maximum batch size was reached.
With this fix, they are also sent at regular intervals (as they were before the regression).
=> fix: usage reports are sent at set intervals

integration-tests/tests/api/app-deployments.spec.ts, packages/libraries/apollo/tests/persisted-documents.spec.ts, packages/libraries/core/src/client/persisted-documents.ts, packages/libraries/yoga/tests/persisted-documents.spec.ts, packages/services/usage/src/usage-processor-2.ts, packages/web/app/src/env/frontend.ts, packages/web/docs/src/pages/docs/features/app-deployments.mdx, packages/web/docs/src/pages/docs/specs/usage-reports.md
https://github.com/graphql/graphql-over-http/pull/296
=> feat: adjust persisted document id format for specification

.changeset/chilly-donkeys-pay.md, packages/libraries/cli/README.md, packages/libraries/cli/src/commands/app/create.ts, packages/libraries/cli/src/commands/app/publish.ts
CLI implementation for app deployments. Split out to avoid cluttering `main` with these changes once we merge the PR that introduces the API changes.
See https://github.com/kamilkisiela/graphql-hive/pull/4746
=> feat: app deployments CLI

packages/web/docs/package.json, packages/web/docs/src/components/ecosystem-management.tsx, packages/web/docs/src/components/landing-page.tsx, packages/web/docs/src/components/team-section.tsx, pnpm-lock.yaml
Laid out the new team section.
Work in progress:
- Integrating it with a CMS like Notion would be an overkill probably, right? Can keep it in code or a CSV file in repo.
=> Team section

packages/services/cdn-worker/src/aws.ts
pass timeout at the correct location (https://github.com/kamilkisiela/graphql-hive/commit/3100043bb1b22fc0ec988aba7eca5b96c6f17888)
=> fix: always pass timeout

packages/web/app/src/components/target/laboratory/create-collection-modal.tsx, packages/web/app/src/components/target/laboratory/delete-operation-modal.tsx, packages/web/app/src/pages/target-laboratory.tsx, packages/web/app/src/stories/delete-operation-modal.stories.tsx
- Align design for all delete modals
- Added component to Storybook
- Added `toast` for better user experience
- Added toggle state for modal in the target lab
=> (3) Drop v2: Delete Operation Modal

.changeset/fresh-walls-push.md, packages/libraries/apollo/tests/persisted-documents.spec.ts, packages/libraries/core/src/client/client.ts, packages/libraries/core/src/client/persisted-documents.ts, packages/libraries/yoga/tests/persisted-documents.spec.ts
Deduplicate persisted document lookups from the registry for reducing the amount of concurrent HTTP
requests.
=> feat: deduplicate persisted document resolution requests

deployment/grafana-dashboards/Container-Logs.json
Show just the messages part of the container logs in collapsed view and on expanded view shows everything
**Collapsed View**
**Expanded view**
=> feat: make container logs grafana more readable

packages/services/api/src/modules/shared/providers/mutex.ts
this will stringify the object properly
=> fix: lock acq log message

.changeset/flat-dragons-share.md, packages/libraries/cli/src/base-command.ts, packages/libraries/cli/src/commands/app/create.ts, packages/libraries/cli/src/commands/app/publish.ts, packages/libraries/cli/src/commands/dev.ts, packages/libraries/cli/src/commands/operations/check.ts, packages/libraries/cli/src/commands/schema/check.ts, packages/libraries/cli/src/commands/schema/delete.ts, packages/libraries/cli/src/commands/schema/fetch.ts, packages/libraries/cli/src/commands/schema/publish.ts, packages/libraries/cli/src/commands/whoami.ts, packages/services/api/src/modules/schema/module.graphql.ts, packages/services/api/src/modules/schema/providers/schema-publisher.ts, packages/services/api/src/modules/shared/__tests__/mutex.spec.ts, packages/services/api/src/modules/shared/providers/mutex.ts
Use a lock acquire timeout smaller than the gateway HTTP timeout and retry requests from CLI in case lock acquiring failures.
```
try to acquire lock
--- not acquired after 30 seconds ----> send response to CLI to retry
--- acquired --> global timeout of lock for 90 seconds; extend lock every few seconds + run action
```
That way we can prevent requests from the CLI reach the envoy timeout of 60 seconds - after the lock is acquired the actual schema publish usually takes around 5-15 seconds, so even in the worst-case scenario if the lock is acquired after 29 seconds, the total request time would not get close to 60 seconds.
The 90 seconds is a hard limit to avoid a resource being locked forever (such as in the case of the bug we encountered yesterday). After this one is exceeded we force …
=> fix: retry lock and avoid gateway timeout

packages/web/docs/src/components/feature-tabs.tsx, packages/web/docs/src/components/landing-page.tsx
https://github.com/user-attachments/assets/9443ccb6-d7c0-4d02-a3c3-4736f3bb0cf4
I'm not proud of this code, but I'm not a fan of importing 2 Radix alternative components and hiding them based on the viewport.
I styled the tabs to be a dropdown select on mobile viewports so we don't have a duplicate state management. (And we ship less JavaScript).
=> Mobile feature tabs dropdown

packages/web/docs/src/components/ecosystem-management.module.css, packages/web/docs/src/components/ecosystem-management.tsx, packages/web/docs/src/components/tools-and-libraries-cards.tsx
https://github.com/user-attachments/assets/247097f6-fd26-418b-8e39-b68c81b911b9
The ecosystem chart is now nice on mobiles, and we're almost ready to ship 🚢 
Used container queries to change CSS vars and text styles.
I considered using the Tailwind plugin https://github.com/tailwindlabs/tailwindcss-container-queries,
but I mostly wanted to change custom properties, not the styles, so that wouldn't make it more convenient.
=> Make ecosystem chart responsive

packages/web/docs/src/components/community-section.tsx, packages/web/docs/src/components/feature-tabs.tsx
We now always display the options in order.
We also close the dropdown when the current option is clicked, what wasn't working before.
=> Update feature dropdown to pin to current

integration-tests/tests/api/schema/check.spec.ts, integration-tests/tests/api/schema/publish.spec.ts, packages/services/api/src/modules/schema/providers/models/composite-legacy.ts, packages/services/api/src/modules/schema/providers/models/composite.ts, packages/services/api/src/modules/schema/providers/models/shared.ts, packages/services/api/src/modules/schema/providers/models/single-legacy.ts, packages/services/api/src/modules/schema/providers/models/single.ts, packages/services/api/src/modules/schema/providers/registry-checks.ts, packages/services/api/src/modules/schema/providers/schema-helper.ts, packages/services/api/src/modules/schema/providers/schema-publisher.ts
Using the latest composable version to produce a checksum can lead to a problem where publishing a new version is ignored, due to unchanged input schema, even though it actually leads to fixing the composition state of the latest version.
This PR uses latest version to produce a checksum (to detect identical versions and return early and avoid doing unnecessary work), and instead of using all subgraphs, it's using the relevant subgraph only.
=> Use latest version in checksum check

packages/services/cdn-worker/src/artifact-storage-reader.ts
Closes https://github.com/kamilkisiela/graphql-hive/issues/5503
Right now we have the requests taking forever if there is degradation on underlying storage. This will ensure we stop the request so worker is not indefinitely running.
=> feat: introduce timeout to s3 read requests

packages/web/docs/src/pages/docs/api-reference/cli.mdx
=> docs: fix link for hive json reference

integration-tests/tests/usage-reporting/usage-reporting-format-2.spec.ts, packages/services/usage/src/usage-processor-1.ts, packages/services/usage/src/usage-processor-2.ts
=> fix: validate operation body

deployment/utils/cloudflare.ts, packages/services/cdn-worker/src/analytics.ts, packages/services/cdn-worker/src/artifact-handler.ts, packages/services/cdn-worker/src/artifact-storage-reader.ts, packages/services/cdn-worker/src/aws.ts, packages/services/cdn-worker/src/dev.ts, packages/services/cdn-worker/src/index.ts, packages/services/cdn-worker/src/key-validation.ts, packages/services/cdn-worker/tests/cdn.spec.ts, packages/services/server/src/index.ts
Requests being made to R2 keep hanging for long periods and cause problems in our production setup for a minimal amount of traffic.
- Make sure these long-running requests are aborted and retried
- Track analytics (duration, status code, error) for every single request made to R2
- Avoid resigned URLs and unnecessary requests to R2. Previously by redirecting, we lost all control and insights about the actual requests being performed to the bucket. Now we always proxy the R2 object through the CF worker.
=> feat: skip presigned url step + analytics

.eslintrc.cjs, deployment/index.ts, deployment/services/cf-cdn.ts, deployment/utils/cloudflare.ts, packages/services/cdn-worker/package.json, packages/services/cdn-worker/src/analytics.ts, packages/services/cdn-worker/src/artifact-storage-reader.ts, packages/services/cdn-worker/src/aws.ts, packages/services/cdn-worker/src/dev.ts, packages/services/cdn-worker/src/index.ts, packages/services/cdn-worker/tests/cdn.spec.ts, packages/services/server/src/index.ts, pnpm-lock.yaml
Follow up for https://github.com/kamilkisiela/graphql-hive/pull/5542.
We are experiencing unreliabilities with R2, where requests hang for long time, even after attempting retries.
This is causing a small amount of requests to the CDN to fail. As a countermeasure, we already introduced writing artifacts to a new S3 bucket in a different region and another cloud provider (see https://github.com/kamilkisiela/graphql-hive/pull/5538).
We synced over the state from the other bucket, so both buckets are now the source of truth of the CDN state.
In this PR we want to use the new bucket (AWS S3) as a fallback in case the first bucket (CF R2) fails to serve a response.
This introduces the new bucket to the CDN worker and changes the business logic for first attempting a single read from R2 without …
=> feat: CDN request retry race from multiple S3 buckets

packages/services/api/src/modules/schema/lib/federation-super-graph.ts
I have noticed fields provided by interfaces have the wrong subgraph associated with them in Hive's explorer.
Interfaces are being marked as resolved by the wrong subgraph in Hive. Although very poorly documented in the federation spec, there is a "usedOverridden" argument inside the "join__field" in these cases. Ignore any join__field directives with this argument.
=> Account for usedOverridden arg in extractSuperGraphInformation

packages/services/cdn-worker/src/aws.ts, packages/services/cdn-worker/src/index.ts
No point of reporting it to Sentry and it's not a fatal error.
=> Downgrade log level of an error when retrying an S3 call

packages/services/cdn-worker/src/index.ts
Adds `preflight` to handles all OPTIONS and preflight requests.
Adds `corsify` to add the appropriate CORS headers to any Response.
=> Add CORS headers to CDN Worker

packages/services/cdn-worker/src/artifact-handler.ts, packages/services/cdn-worker/src/artifact-storage-reader.ts, packages/services/cdn-worker/src/handler.ts, packages/services/cdn-worker/tests/cdn.spec.ts
`await response.text()` and `fetch('...', { signal })` does not like each other.
=> Read response body closer to the fetch call

.github/workflows/pr-rust.yaml, docker/router.dockerfile
Reverts kamilkisiela/graphql-hive#5457
=> Revert "chore(deps): update rust docker tag to v1.80"

packages/web/docs/src/components/page.tsx
My previous fix didn't work because I forgot about `global` here.
This should stop the chat bubble overlapping with the cookies "Accept" button.
=> Add missing `global` attribute to `style jsx` fixing Chat position

packages/web/app/src/components/target/insights/Fallback.tsx, packages/web/app/src/components/target/insights/Filters.tsx, packages/web/app/src/components/target/insights/List.tsx, packages/web/app/src/components/target/insights/Stats.tsx, packages/web/app/src/lib/hooks/use-date-range-controller.ts, packages/web/app/src/lib/hooks/use-search-params-filters.ts, packages/web/app/src/lib/object.spec.ts, packages/web/app/src/lib/object.ts, packages/web/app/src/pages/target-insights-client.tsx, packages/web/app/src/pages/target-insights-operation.tsx, packages/web/app/src/pages/target-insights.tsx
At Toast, every team has a weekly metric review meeting where teams go through their dashboards and metrics for their services and SPAs. Teams have been using Hive Insights for client metrics. As teams go through a spreadsheet with all dashboard links, it has been a bit annoying to have to set the filters every time.
This PR adds the clients and operations filters to the search params (same done already for the date presets).
- Created a hook to manage any search params filter.
- Changed clients and operations filters to use `useSearchParamsFilter` instead of `useState`.
- Fixed `useDateRangeController` to not remove current search params when the user changes it.
- Changed Fallback component to display a more generic message as there might not be stats for a given combination of filters …
=> feat: Track clients & operations filters using search params

packages/web/docs/src/pages/docs/api-reference/gateway-config.mdx, packages/web/docs/src/pages/docs/gateway/subscriptions.mdx
Currently, there is no real explanation about how `transportEntries` works.
This PR adds explanation about `transportEntries` behaviour in the context of subscriptions.
It also show how to propagate headers when using WebSocket subscriptions.
=> [docs] Add docuementation for  and WS headers propagation

packages/services/webhooks/src/jobs.ts
In logs we saw HTTP 400 but not the actual reason of 400. So this will log an error even for us to track
Context: https://guild-oss.slack.com/archives/C01E8ATBQGN/p1725619720474049
=> feat: improve error handling for webhook broker

integration-tests/tests/api/schema/check.spec.ts, integration-tests/tests/api/schema/publish.spec.ts, packages/services/schema/src/orchestrators.ts
A customer reported that publishing app deployments failed with an unexpected error. After some digging, it turns out the customer published an invalid GraphQL schema.
This PR adds a test to reproduce the issue and fixes the publish of single schemas to do all necessary additional validations.
=> fix: fully validate published graphql schema for single project

packages/services/api/src/modules/organization/providers/organization-manager.ts, packages/web/app/src/pages/auth.tsx, packages/web/app/src/pages/organization-transfer.tsx, packages/web/app/src/router.tsx
Multiple users reported, that transferring an organization is not possible as the link leads to a 404 page on the web app.
The route embedded in the email and the route definition on the web app did not match. This PR changes the app route path definition and adds small improvements to the UI.
=> fix: correct route on app for transfer organization

packages/web/app/src/components/target/explorer/filter.tsx
Closes https://github.com/kamilkisiela/graphql-hive/issues/5398
We need to query the latest valid schema version instead of the latest schema version.
=> fix: schema type filter when latest schema version is broken

packages/web/app/src/pages/auth-oidc.tsx, packages/web/app/src/pages/auth-sso.tsx
When people log in with OIDC, they can briefly see a "oidc" login failed message before they get redirected to their provider.
https://github.com/user-attachments/assets/1fe37337-a440-450d-acec-d76c0ae4dae0
This error was caused by react query. This issue is resolved by simply returning a dummy value from the mutate function. As a bonus, we also auto-focus the input field!
Closes https://github.com/kamilkisiela/graphql-hive/issues/5536
=> fix: oidc login failed message before redirect

packages/web/app/src/pages/auth-sign-in.tsx, packages/web/app/src/pages/auth-sign-up.tsx
When visiting the login/sign up page, we automatically focus the first input field.
When a sign up/sign in fails, we automatically focus the first input field.
This makes editing invalid values a bit more convenient.
https://github.com/user-attachments/assets/f6874d4e-8764-4db3-8585-90ad333f0c5b
=> feat: auto-focus form input when visiting login and sign up page

packages/web/app/src/components/organization/support.tsx
Make the descriptions bit more descriptive based on the SLA we have for Free/Pro accounts
=> fix: Improve support priority descriptions

.changeset/config.json, .github/workflows/release-docker.yaml, .github/workflows/release-stable.yaml, .github/workflows/typescript-typecheck.yaml, README.md, deployment/CHANGELOG.md, deployment/package.json, package.json, packages/services/server/turbo.json, packages/web/docs/turbo.json, pnpm-lock.yaml, turbo.json
Related document: https://www.notion.so/theguildoss/Publishing-new-version-of-Hive-11ab6b71848a80078762ec951188be8e?pvs=4
#2995 
1. `pnpm changeset` 
2. Select `hive`
3. Pick a level
4. Describe changes
5. Merge a Pull Request to release a new version
All changes will be visible under `hive@` prefix ([an example](https://github.com/kamilkisiela/graphql-hive/releases?q=%40graphql-hive%2Fyoga&expanded=true)), but also in `deployment/changelog.md`.
In order to use `changesets` for publishing hive's docker images with proper version tag, it has to be part of the "packages" (of the workspace).
Using root package.json was not an option due to [this issue](https://github.com/changesets/changesets/issues/1137#issuecomment-2312752530). The next good candidate was `deployment` directory.
According …
=> Versioning of docker images

.github/workflows/main.yaml
Instead of using `latest` for every merged commit, use it only when a new stable version is released.
=> Use `latest` tag only on stable docker releases

docker/cli.dockerfile, docker/migrations.dockerfile, docker/services.dockerfile
Github Container Registry supports:
- org.opencontainers.image.source ✅ 
- org.opencontainers.image.description ✅ 
- org.opencontainers.image.licenses - the PR adds this label and MIT as a value
=> Add MIT license to docker labels

packages/libraries/cli/package.json, packages/web/docs/src/components/landing-page.tsx, pnpm-lock.yaml
Moving to docs is two clicks currently, this change makes them accessible in one.
=> Change View Pricing link to Documentation

packages/web/docs/public/install.sh
Fixes #5737 
I wasn't sure if there were other `aarch*` strings that we need to account for.
If the only options are `aarch64` & `aarch64` then we can simplify more.
=> aarch64 -> arm64

codegen.mts, integration-tests/tests/api/artifacts-cdn.spec.ts, integration-tests/tests/api/target/usage.spec.ts
to remove these warnings https://guild-oss.slack.com/archives/C01E8ATBQGN/p1729585730974249
```sh
❯ Generate to ./integration-tests/testkit/gql/
✔ Load GraphQL schemas
✔ Load GraphQL documents
⠼ Generate
[client-preset] the following anonymous operation is skipped: 
{
__schema {
types {
name
fields {
name
}
}
}
}
[client-preset] the following anonymous operation is skipped: 
query {
a
}
[client-preset] the following anonymous operation is skipped: 
query {
b
}
[client-preset] the following anonymous operation is skipped: 
subscription {
a
}
[client-preset] the following anonymous operation is skipped: 
query {
a
}
[client-preset] the following anonymous operation is skipped: 
query {
a
}
[client-preset] the following anonymous operation is skipped: 
query {
a
}
✔ Parse Configuration
✔ …
```
=> clean warnings from codegen `the following anonymous operation is skipped:`

packages/web/docs/src/pages/docs/gateway/deployment/docker.mdx, packages/web/docs/src/pages/docs/gateway/index.mdx, packages/web/docs/src/pages/docs/gateway/persisted-documents.mdx, packages/web/docs/src/pages/docs/gateway/usage-reporting.mdx, packages/web/docs/src/pages/docs/get-started/apollo-federation.mdx
https://github.com/graphql-hive/gateway
Also, the workdir in the Docker image has been moved from `/serve` to `/gateway`. Not a breaking change at the moment because [`/serve` is symlinked to `/gateway`](https://github.com/graphql-hive/gateway/blob/048eec06630a0d4859a334f25a8b20d423e2718d/packages/gateway/Dockerfile#L23-L25).
=> Hive Gateway has been moved to ghcr.io/graphql-hive/gateway

package.json, pnpm-lock.yaml
This package is no longer used as we removed it from codegen config in https://github.com/graphql-hive/platform/pull/5827
=> Remove unused @graphql-codegen/graphql-modules-preset

packages/web/app/src/pages/target-settings.tsx
Selecting targets was broken due to incorrect form field name.
=> Fix Conditional Breaking Changes form

package.json, pnpm-lock.yaml
https://github.com/graphql-hive/platform/pull/5785 broke auto-restarting services upon file changes (this has been reported as well here: https://github.com/egoist/tsup/issues/1245).
Reverting to version `8.3.0` resolves this issue.
=> chore: revert tsup

packages/services/api/src/modules/operations/lib/pick-table-by-provider.ts, packages/web/app/src/lib/hooks/use-date-range-controller.spec.ts, packages/web/app/src/lib/hooks/use-date-range-controller.ts
date-fns's `startOfHour` and `endOfHour` caused time range to be incorrect in the context of how clickhouse data is aggregated (`startOfHour(UTC)`, ` startOfDay(UTC)` and `startOfMinute(UTC)`).
Showing data from `Oct 11, 11:30 UTC` would lead to empty result for that day (in case of daily aggregation).
=> Handle UTC +5:30 and similar timezones

packages/web/docs/src/components/landing-page.tsx
Hiding theme switcher on landing page as it doesn't work there anyway.
=> Hide theme switcher on landing page

integration-tests/testkit/seed.ts, integration-tests/tests/api/target/crud.spec.ts
Test for https://github.com/graphql-hive/platform/pull/5899
This just ensures that a organization member can create a target.
=> test: organization member can create a target

.github/workflows/release-stable.yaml
it's broken, we can't publish to Crates because we are using `git = "..."` for some deps
=> comment out cargo release flow

configs/cargo/Cargo.lock, packages/libraries/router/Cargo.toml, packages/libraries/router/src/graphql.rs
This should unlock the `crate publish` workflow and allow us to publish the Hive apollo-router plugin to Crates.io
=> Use stable versions of Rust crates

packages/web/docs/src/components/ecosystem-management/index.tsx, packages/web/docs/src/components/feature-tabs.tsx, packages/web/docs/src/components/frequently-asked-questions/index.tsx
Tabs, FAQ and the diagram content did not have mounted DOM elements.
The only sacrifice is the animation in FAQ, but honestly, I prefer it without it, as you click and wait a second to read what's in there.
=> Make content of landing page visible to crawlers

.changeset/tricky-ravens-share.md, .github/workflows/release-stable.yaml, packages/libraries/router/Cargo.toml, packages/libraries/router/package.json, packages/libraries/router/sync-cargo-file.sh
This PR integrates the `changeset version` script with the Crate publishing. 
When a changeset is created and merged to the fake-`package.json`, it will also update the Crates.toml file with the version number. 
Later, merging the changeset PR into  `main` will trigger a workflow to cut a release to Crates.io.
=> improve Crate publish flow

packages/web/app/src/components/ui/accordion.tsx
It is slow and laggy. We don't need it.
https://github.com/user-attachments/assets/9d392abe-5138-4941-9a19-c84ba77a4639
###
This modifies the shadcn components, which we never want to do. But I guess in this case it is fine.
=> feat: remove the transition for accordions

.changeset/great-needles-guess.md, .changeset/short-candles-clap.md, packages/services/api/package.json, packages/services/api/src/modules/integrations/providers/github-integration-manager.ts, pnpm-lock.yaml
Currently, the requests to Github API are not retried in case of failures. This PR adds retries.
Uses Octokit's defaults
```
retryAfterBaseValue: 1000,
doNotRetry: [400, 401, 403, 404, 422, 451],
retries: 3,
```
In case of 5XX errors, user is now informed about Github API struggling to resolve the request. We also point the user to visit  github's status page.
=> Retry calls to Github (check-runs) and inform user about Github API having issues

.changeset/warm-peas-melt.md, packages/web/docs/public/apollo-router-download.sh, packages/web/docs/src/pages/docs/other-integrations/apollo-router.mdx, packages/web/docs/src/pages/product-updates/2024-11-19-apollo-router-hive-versioning.mdx
Closes https://github.com/graphql-hive/console/issues/3314
=> product update and docs for apollo-router custom build versioning

packages/web/docs/public/install.sh
Closes https://github.com/graphql-hive/console/issues/3292 
The `/usr/local/lib` might not exists, especially if the OS is new and tools like `brew` are not installed yet. 
This ensures that the dir exists before trying to create/update/delete files in it. The `-p` will silently ignore if the dir already exists
=> Fix missing `/usr/local/lib` in Hive CLI install script

packages/web/app/index.html
It may be confusing for Google to see graphql-hive.com and the-guild.dev/graphql/hive, that's one reason. We also don't need that page to be indexed, it has 0 relevant content.
=> Prevent indexing app.graphql-hive.com

packages/web/docs/src/pages/docs/management/organizations.mdx
There were hard to find. I removed the image (it was a bit confusing to see the check-run there, I think there should be an image of the github integration section), but we can always bring it back.
I made the instructions "pop" a bit more. Instead of using a single sentence, it's now an indexed list.
=> Improve Github Integration instructions

packages/web/docs/src/pages/docs/gateway/deployment/index.mdx, packages/web/docs/src/pages/docs/gateway/deployment/node-frameworks/express.mdx, packages/web/docs/src/pages/docs/gateway/deployment/node-frameworks/fastify.mdx, packages/web/docs/src/pages/docs/gateway/deployment/node-frameworks/hapi.mdx, packages/web/docs/src/pages/docs/gateway/deployment/node-frameworks/index.mdx, packages/web/docs/src/pages/docs/gateway/deployment/node-frameworks/koa.mdx, packages/web/docs/src/pages/docs/gateway/deployment/node-frameworks/nextjs.mdx, packages/web/docs/src/pages/docs/gateway/deployment/node-frameworks/sveltekit.mdx, packages/web/docs/src/pages/docs/gateway/deployment/node-frameworks/uwebsockets.mdx, packages/web/docs/src/pages/docs/gateway/deployment/runtimes/bun.mdx, packages/web/docs/src/pages/docs/gateway/deployment/runtimes/deno.mdx, packages/web/docs/src/pages/docs/gateway/deployment/runtimes/index.mdx, packages/web/docs/src/pages/docs/gateway/deployment/runtimes/nodejs.mdx, packages/web/docs/src/pages/docs/gateway/deployment/serverless/aws-lambda.mdx, packages/web/docs/src/pages/docs/gateway/deployment/serverless/azure-functions.mdx, packages/web/docs/src/pages/docs/gateway/deployment/serverless/cloudflare-workers.mdx, packages/web/docs/src/pages/docs/gateway/deployment/serverless/index.mdx, packages/web/docs/src/pages/docs/gateway/other-features/performance/index.mdx
The index of Hive Gateway re-exports stuff that is Node-centric, like the [CLI stuff](https://github.com/graphql-hive/gateway/blob/ae84d49f71a72c331f66ff81cea092a791ddc019/packages/gateway/src/index.ts#L1) and various [CLI built-in plugins](https://github.com/graphql-hive/gateway/blob/ae84d49f71a72c331f66ff81cea092a791ddc019/packages/gateway/src/index.ts#L7-L15).
Because of that, the `createGatewayRuntime` from `@graphql-hive/gateway` is not tailored for the edge. You have to run your edge workers in Node compat mode.
However, using `createGatewayRuntime` from `@graphql-hive/gateway-runtime` works without any Node shims or compat modes. It should be the recommended way of running the Hive Gateway on the edge.
At the moment, all other alternatives of fixing the index exports are breaking …
=> Recommend @graphql-hive/gateway-runtime for programmatic usage

.changeset/good-actors-pull.md, packages/services/api/src/modules/integrations/resolvers/Organization.ts
Some of our users contacted us saying they could not find the controls for managing Slack and GitHub integrations.
The resolvers for `Organization.viewerCanModifyGitHubIntegration` and `Organization.viewerCanModifySlackIntegration` were implemented faulty within https://github.com/graphql-hive/console/pull/5860. This resulted in users within organizations that did not previously have a GitHub/Slack integration being locked out from managing or adding one in the first place. This did slip our radar as the organizations we used on staging already had such integrations.
Adjusts the implementation of the `Organization.viewerCanModifyGitHubIntegration` and `Organization.viewerCanModifySlackIntegration` resolvers, so they do not resolve to `false` in case no integration exists for that …
=> fix: allow organizations without slack or github integrations to manage integrations

packages/services/schema/src/lib/federation-tag-extraction.ts
Spotted by @hasparus [here](https://guild-oss.slack.com/archives/C07DYCW4NUD/p1733242685490739).
This block should return early to avoid unnecessary traversals and loops when not needed. Because not returning early here is just a slight performance improvement, this caused no issues before.
=> fix: add missing return statement for early return block

deployment/services/db-migrations.ts, packages/migrations/src/clickhouse-actions/002-add-hash-to-clients_daily.ts, packages/migrations/src/clickhouse-actions/003-add-client-name-to-operations-tables.ts, packages/migrations/src/clickhouse-actions/004-version-2.ts, packages/migrations/src/clickhouse-actions/006-monthly-operations-log.ts, packages/migrations/src/clickhouse-actions/007-james-bond-aggregates-hourly-and-minutely.ts, packages/migrations/src/clickhouse-actions/008-daily-operations-log.ts, packages/migrations/src/clickhouse-actions/009-ttl-1-year.ts, packages/migrations/src/clickhouse.ts, packages/migrations/src/environment.ts, packages/migrations/src/index.ts
Treat `dev` and `staging` ClickHose instances as we treat `self-hosted` Hive and perform the same migrations. This allows to nuke them and start from scratch.
=> Run certain migrations only in production

packages/web/docs/src/components/federation-page.tsx
The path to Hive is missing (it's there, but near the footer), I also thought about adding a secondary CTA button where people could ask us questions.
=> Point people from /federation to Hive and Crisp

packages/web/docs/src/pages/docs/gateway/defer-stream.mdx
We have `See more` link at the end that points to Yoga, where we tell people how to configure Yoga and run queries via cURL or GraphiQL.  It's a bit weird given the gateway talks to subgraphs, so those instructions makes no sense.
I copied part of Yoga docs to show example queries and expected behavior.
=> Showcase `@defer` and `@stream` in docs/gateway/defer-stream

deployment/index.ts, deployment/utils/pod-builder.ts, deployment/utils/publish-app-deployment.ts, deployment/utils/publish-graphql-schema.ts
Closes https://github.com/graphql-hive/deployment/issues/1425 
Deployments on staging and dev often fail because the app deployment publishes times out due to click house being in rest mode.
This change will send a dummy query (`SELECT 1`) to the clickhouse instance on dev and staging to make sure it responds in time for the app deployment publish.
=> chore: wake up clickhouse before publishing app deployment

integration-tests/docker-compose.integration.yaml
`vectorized/redpanda` was deprecated and now it's gone
=> Use redpandadata/redpanda in integration tests

configs/cargo/Cargo.lock
Closes https://github.com/graphql-hive/console/security/dependabot/237 
```
cargo update hickory-proto
cargo update url
```
```
Updating hickory-proto v0.24.1 -> v0.24.2
Removing idna v0.4.0
...
Updating url v2.5.2 -> v2.5.4
Updating idna v0.5.0 -> v1.0.3
```
=> Fix `idna` nested dependency cve

packages/web/app/package.json, packages/web/app/src/server/dev.ts, packages/web/app/src/server/index.ts, pnpm-lock.yaml
I moved us to `tsx`.
It's tested, it works, no need to use latest and greatest.
```
tsx watch --clear-screen=false --exclude \"./**/*.mjs\" src/server/dev.ts
```
`--clear-screen=false` - because it's annoying when things disappear, especially when something does not work and you're debugging.
`--exclude "./**/*.mjs"` - because Vite or something related to Vite complies the config file to `.mjs` and the watch mode freaks out.
`src/server/dev.ts` - because this way we can fully control environment variables and use our good old and reliable `dotenv`.
=> Fix the watch mode in web/app

.github/workflows/dockerize-cli.yaml, .github/workflows/release-alpha.yaml, .github/workflows/release-stable.yaml
This change propagates `publishLatest` to the dockerize action of the CLI. When executed from `main`, it will pass `true`, and then `BUILD_STABLE` will be set to `1`. The Docker HCL file will then tag the image as `latest` in addition to the versioned number.
Closes https://github.com/graphql-hive/console/issues/6102
=> Added `latest` tag to CLI release flow when published from main

packages/web/app/src/pages/organization-settings.tsx
Notice that buttons are not aligned on production. See images.
Before (Prod)
After
=> Align `GitHub Integration` buttons UI

.changeset/unlucky-pianos-hide.md, packages/libraries/cli/package.json, packages/services/api/package.json, packages/services/schema/package.json, pnpm-lock.yaml
Fix a missing `@join__field` on a query field where `@override` is used, but not in all subgraphs.
=> Update @theguild/federation-composition to v0.14.2

.changeset/nice-birds-mate.md, packages/services/usage/src/index.ts
Instead of passing `(target=%s)` over and over again, we now have a context aware logger instance.
This PR adds also a log message with errors when a report decoding is not successful.
=> Use structured logging and log validation errors in usage service

.changeset/pretty-planes-jog.md, packages/services/usage/__tests__/usage-processor-2-validation.spec.ts, packages/services/usage/src/usage-processor-2.ts
To make life easier for Ruby and other integrations, I made all optional fields accept `null` in the Usage Report v2 format.
```js
{
...
"metadata": null // was rejected, now it's accepted
}
{
...
"metadata": undefined // was accepted, still is
}
{
...
// missing "metadata" was accepted, still is
}
```
=> Make optional properties optional or nullable in usage report v2

.changeset/proud-news-invite.md, .changeset/rotten-islands-joke.md, configs/cargo/Cargo.lock, packages/libraries/router/Cargo.toml, packages/libraries/router/README.md, packages/libraries/router/router.yaml, packages/libraries/router/src/agent.rs, packages/libraries/router/src/graphql.rs, packages/libraries/router/src/lib.rs, packages/libraries/router/src/main.rs, packages/libraries/router/src/persisted_documents.rs, packages/libraries/router/src/registry.rs, packages/libraries/router/src/usage.rs, packages/services/usage/usage-report-v2.schema.json, packages/web/docs/src/components/usage-reports-json-schema.tsx, packages/web/docs/src/pages/docs/other-integrations/apollo-router.mdx, packages/web/docs/src/pages/docs/schema-registry/app-deployments.mdx, packages/web/docs/src/pages/docs/specs/usage-reports.mdx, packages/web/docs/src/pages/product-updates/2024-11-20-hive-plugin-apollo-router-crate.mdx, packages/web/docs/src/pages/product-updates/2024-12-16-apollo-router-app-deployments/index.mdx
closes https://github.com/graphql-hive/platform/issues/5498
=> feat(apollo-router-plugin): persisted operations (app deployments) plugin with Hive, update usage to API-Version v2

packages/web/docs/src/components/navigation-menu/index.tsx
We forgot to add `/partners`.
Root cause will be fixed when we migrate to route groups, and we'll just put the page next to the others in a directory.
=> Add /partners to landing pages list

.changeset/modern-trees-begin.md, packages/web/app/src/lib/billing/stripe.tsx
It affected e2e tests and self-hosters.
=> fix: prevent stripe.js from loading automatically

packages/web/docs/src/pages/docs/gateway/deployment/runtimes/bun.mdx, packages/web/docs/src/pages/docs/gateway/index.mdx
Hive GW CLI is fully compatible with Bun just like Node.js.
So this PR does
- Mention Bun as a compatible runtime for CLI
- Recommend to use CLI on Bun instead of programmatic API
Note: This doesn't recommend using Bun over Node. It recommends CLI over programmatic API for Bun. Because previously for Bun runtime, only programmatic API was recommended. Now we mention that CLI is compatible with Bun so if you want to use Bun, you can use CLI directly.
=> For Bun integration, Recommend Hive GW CLI

package.json, packages/web/app/package.json, packages/web/app/preflight-worker-embed.html, packages/web/app/src/preflight-worker-embed.ts, packages/web/app/src/server/index.ts, packages/web/app/vite.config.ts, patches/@fastify__vite.patch, pnpm-lock.yaml
Decorates fastify request object with `viteHtmlFile` to determine the html file.
With those changes, the preflight-worker-embed and the app itself both have hot reloading working, logging etc.
I tried to keep it as simple as possible.
=> Prepare Vite and Fastify for more than one entry point

packages/services/storage/src/tokens.ts, packages/web/docs/src/pages/docs/gateway/index.mdx, packages/web/docs/src/pages/docs/gateway/supergraph-proxy-source.mdx
Mention the default polling interval "10 seconds" in the docs
=> [Gateway] Mention default polling interval in the docs

packages/web/docs/src/pages/docs/gateway/usage-reporting.mdx
It is hard to find out that you can use Hive Client options in `reporting` section.
This PR adds a reference to there.
=> [Gateway] Refer to the Hive Client docs in the usage reporting section

deployment/services/usage.ts
Right now the way it is working in production one pod keeps growing memory forever. This way we restrict pod budget so we don't grow infinitely. I am hoping that it will instead scale pods out when we hit limits.
=> limit memory on usage service

.changeset/little-hats-smile.md, packages/migrations/src/actions/2024.12.24T00-00-00.improve-version-index-2.ts, packages/migrations/src/run-pg-migrations.ts
Seems like the `schema_version_changes` table is also missing an index for querying by `schema_version_id` field. 
```sql
SELECT
"change_type" as "type",
"meta",
"severity_level" as "severityLevel",
"is_safe_based_on_usage" as "isSafeBasedOnUsage"
FROM
"schema_version_changes"
WHERE
"schema_version_id" = '2145210e-7762-4d2d-9f21-74a364054123';
```
And the plan: 
```
Gather  (cost=1000.00..260174.97 rows=523 width=113)
Workers Planned: 2
->  Parallel Seq Scan on schema_version_changes  (cost=0.00..259122.67 rows=218 width=113)
Filter: (schema_version_id = '2145210e-7762-4d2d-9f21-74a364054123'::uuid)
```
This should eliminate the parallel seq scan and just use the index instead.
=> feat(performance): added missing index for `getSchemaChangesForVersion` 

packages/web/docs/src/pages/docs/gateway/other-features/_meta.ts, packages/web/docs/src/pages/docs/gateway/other-features/upstream-reliability.mdx
Documentation for new upstream retry and timeout feature https://github.com/graphql-hive/gateway/pull/322
=> docs: add documentation for upstream reliability (retry + timeout)

packages/libraries/yoga/tests/yoga.spec.ts, pnpm-lock.yaml
sometimes is needs a few extra `ms` to process. Affected https://github.com/graphql-hive/console/actions/runs/12491206933/job/34856910544?pr=6168
=> fix flakey yoga unit test

.changeset/tame-apes-impress.md, package.json, patches/oclif.patch, pnpm-lock.yaml
Prints a list of files of the script directory and a file path to the included node binary.
=> Extend debug information of the CLI

packages/web/app/src/pages/target-explorer-unused.tsx
#5870 
I would like to see the total unused fields so I can see if my team is improving over time with cleaning-up their unused fields/types. If you do not see added value then let me know. 
Affects the web app only as it is only display changes.
This is how I made it look:
Only display changes which should not affect the security of the system in any way.
=> Show total unused fields

integration-tests/tests/api/audit-logs/audit-log-record.spec.ts, packages/services/api/src/modules/audit-logs/providers/audit-log-recorder.ts, packages/services/api/src/modules/audit-logs/providers/audit-logs-manager.ts, packages/services/api/src/modules/audit-logs/providers/audit-logs-types.ts, packages/services/api/src/modules/audit-logs/resolvers/Mutation/exportOrganizationAuditLog.ts, packages/services/api/src/modules/operations/providers/sql.ts, packages/services/api/src/modules/policy/providers/schema-policy.provider.ts, packages/web/app/src/pages/organization-settings.tsx
Bug introduced in https://github.com/graphql-hive/console/pull/5530
- Properly escape `JSON.stringify({ foo: JSON.stringify({ foo: true }) })` when inserting into clickhouse
- Also fixes the wrong usage of `organization.id` as `organizationSlug`...
=> fix: escape double quotes for clickhouse queries

packages/web/docs/src/pages/docs/gateway/other-features/performance/index.mdx
=> fix serverless deploy link

.changeset/flat-planes-hunt.md, packages/web/app/src/lib/preflight-sandbox/preflight-script-worker.ts, packages/web/app/src/lib/preflight-sandbox/preflight-worker-embed.ts, packages/web/app/src/lib/preflight-sandbox/shared-types.ts, packages/web/docs/src/pages/docs/dashboard/laboratory/preflight-scripts.mdx
```js
const emal = await lab.prompt('Enter email', /* 'default@email.here' */);
```
The `lab.prompt` function sends a message from the Worker to the Client.
The Client executes real `prompt(...)`.
Client sends a message to the Worker with the response.
Worker resolves a promise.
If something goes wrong and promise is never resolved, the Worker hits its 30s execution limit and is terminated.
=> Adds lab.prompt to Preflight Script

packages/services/api/src/modules/audit-logs/providers/audit-logs-types.ts
Fixes https://github.com/graphql-hive/console/issues/6243
=> Fix `integrationId` value validation in `ORGANIZATION_UPDATED_INTEGRATION` audit log event

deployment/services/database-cleanup.ts
```diff
- api: postgresConnectionString
+ postgres:connectionString
```
`api:postgresConnectionString` was never a thing.
=> Fix pg connection string in the database cleanup job

packages/web/app/src/lib/hooks/laboratory/use-operation-collections-plugin.tsx
This seems like a race-condition in the animation/scroll-to effect. I was not able to fully reproduce it locally 🤔  
Fixed https://github.com/graphql-hive/console/issues/6263
=> fix: `scrollIntoView` is not a function in lab page

.changeset/blue-actors-work.md, packages/services/api/src/modules/audit-logs/providers/audit-logs-types.ts, pnpm-lock.yaml
Fixes https://github.com/graphql-hive/console/issues/6264 
All of the IDs we store there as metadata, are external IDs, and it is not a `uuid` format so it fails during Zod validation.
=> Remove `uuid` validation from some audit log events metadata

packages/web/app/src/components/organization/Permissions.tsx
This page shows a react warning because it prints a list of elements that are missing a `key` attribute. This can cause elements to rerender inefficiently.
Removes the unnecessary empty element from a component so that the root element is keyed.
=> Fix permissions page list rendering

packages/services/api/src/modules/schema/providers/schema-manager.ts, packages/services/api/src/modules/shared/providers/storage.ts, packages/services/api/src/shared/entities.ts, packages/services/storage/src/index.ts
This reverts commit c273883bf3be7615e89358b56b28419355caa6c8.
We no longer have legacy users within our database after https://github.com/graphql-hive/console/pull/6066.
We had to revert this change earlier in https://github.com/graphql-hive/console/pull/6064.
We can now ship this change as there are no longer any users without a supertokens user id within our database.
=> Revert "Revert "refactor: decode user in storage" (#6064)"

integration-tests/tests/api/policy/policy-access.spec.ts, packages/services/api/src/modules/policy/providers/schema-policy.provider.ts, packages/services/storage/src/db/types.ts, packages/web/app/src/components/layouts/organization.tsx, packages/web/app/src/components/layouts/project.tsx, packages/web/app/src/components/policy/policy-list-item.tsx, packages/web/app/src/components/policy/policy-settings.tsx, packages/web/app/src/pages/organization-policy.tsx, packages/web/app/src/pages/project-policy.tsx
Closes https://github.com/graphql-hive/console/issues/5861
Adds read access to linting configuration.
I reused the organization:describe and project:describe permissions to determine if the user has access to read the policy.
For the implementation, I overloaded onSave to indicate whether or not this is readonly. If onSave is undefined, then this is considered readonly and all settings will be disabled.
I'm open to adding a separate attribute instead of that's preferred.
=> fix(policy): added a new read access for schema policy linting

.prettierignore
Progresses toward: https://github.com/graphql-hive/console/pull/6122
Vitest supports snapshot files like "foo.json". Regardless of the file type, prettier should always ignore snapshot files.
=> chore(prettier): ignore snapshot files

.changeset/young-peas-battle.md, .eslintrc.cjs, cypress/e2e/laboratory-collections.cy.ts, cypress/e2e/laboratory-preflight-script.cy.ts, cypress/support/testkit.ts, packages/web/app/src/components/target/laboratory/create-collection-modal.tsx, packages/web/app/src/components/target/laboratory/create-operation-modal.tsx, packages/web/app/src/components/target/laboratory/delete-collection-modal.tsx, packages/web/app/src/components/target/laboratory/delete-operation-modal.tsx, packages/web/app/src/components/target/laboratory/edit-operation-modal.tsx, packages/web/app/src/lib/hooks/laboratory/use-operation-collections-plugin.tsx, packages/web/app/src/pages/target-laboratory.tsx, patches/@graphiql__react.patch, pnpm-lock.yaml
**Fixes** 
When opening a new tab or selecting one of the saved operations a wrong query was populated. It was always the default query or the one that's active. Meaning, you couldn't select and see the saved operation :)
When saving the operation, the submit button of the form was always disabled, even when the state of the form was valid.
**e2e tests**
Added tests for CRUD of collections and their operations.
The scenario where a user visits a shared link to an operation is also now tested.
=> Fix editor state and operation handling in Laboratory + e2e tests

packages/libraries/cli/package.json
progresses #6122 
Integration tests run against the _built_ packages. This PR introduces a watch script for CLI to make it easy to work on CLI and integration tests at the same time.
Also, this PR updates the build script to use the idiomatic `--clean` flag. It will remove the output directories according to what is configured in the `tsconfig.json`. This keeps config DRY. Our current approach uses `rm -rf` duplicating config about which dir is for the TS output.
=> chore(cli): idiomatic build script with watch

.changeset/asd-asd-asd.md, packages/migrations/src/actions/2025.01.09T00-00-00.legacy-member-scopes.ts, packages/migrations/src/run-pg-migrations.ts, packages/migrations/test/2025.01.09T00-00-00.legacy-member-scopes.test.ts, packages/migrations/test/root.ts
This migration is going to create a new role for each group of members that have the same scopes but no role assigned.
Users won't be affected by this change, as they will still have the same scopes.
The role will be named `Auto Role {counter}`.
The counter will be reset for each organization.
The script will create 1 or 2 roles for 97% of organizations that haven't complete the migration.
Completes https://the-guild.dev/graphql/hive/product-updates/2023-12-05-member-roles
=> Assign custom roles to members without a role

packages/web/app/src/components/target/settings/cdn-access-tokens.tsx, packages/web/app/src/pages/target-settings.tsx
There is still some access checks happening using the legacy scopes that we need to remove for https://github.com/graphql-hive/console/pull/6231
=> refactor: remove usage of scopes for CDN access tokens

packages/libraries/cli/src/base-command.ts, packages/libraries/cli/src/commands/app/create.ts, packages/libraries/cli/src/commands/config/delete.ts, packages/libraries/cli/src/commands/config/reset.ts, packages/libraries/cli/src/commands/config/set.ts, packages/libraries/cli/src/commands/dev.ts, packages/libraries/cli/src/commands/introspect.ts, packages/libraries/cli/src/commands/operations/check.ts, packages/libraries/cli/src/commands/schema/check.ts, packages/libraries/cli/src/commands/schema/delete.ts, packages/libraries/cli/src/commands/schema/fetch.ts, packages/libraries/cli/src/commands/schema/publish.ts
Progresses #6122
New methods are coming for constructing output types. This refactor
clarifies the difference between loggeres and data constructors.
=> refactor(cli): explicit BaseCommand log method names

integration-tests/docker-compose.integration.yaml, integration-tests/tests/api/rate-limit/emails.spec.ts, packages/services/usage/package.json, packages/services/usage/src/environment.ts, packages/services/usage/src/index.ts, packages/services/usage/src/metrics.ts, packages/services/usage/src/rate-limit.ts, pnpm-lock.yaml
Replace the caching + deduplication of rate-limit RPC with lru-cache.fetch that has deduplication built-in (like we have in the tokens services).
I also added a timeout of 5s to rate-limit RPCs, to avoid waiting for it infinitely. The fallback values are: do not rate limit, data retention of 1 year anyway.
Latency of requests to the tokens service is measured already.
=> Measure latency of RPC to rate-limit service and duration of report parsing

packages/services/usage/package.json, packages/services/usage/src/metrics.ts, packages/services/usage/src/tokens.ts, packages/services/usage/src/usage-processor-1.ts, pnpm-lock.yaml
- Drops TTL for operation body validation cache, increases the capacity (from 5000 to 20_000 as we store now short strings) and uses a new cache key (`sha256(operation)`)
- Replaces current deduplication logic with built-in of LRU-cache
=> Move from tiny-lru to lru-cache in the usage service

packages/services/storage/src/schema-change-model.ts
Fixed a bug introduced in https://github.com/graphql-hive/console/pull/6254
`ConditionalBreakingChangeMetadata` is stored in the `SchemaCheckModel` as a JSON column. Without defaulting this, saved check records fail the zod validation. Rather than migrate all past checks, set a default.
Another option is to make this nullable, but for simplicity when dealing with any breaking change data in our codebase, I prefer defaulting. That limits the amount of null checking or extra cases we have to handle elsewhere.
=> Add defaults for new columns to ConditionalBreakingChangeMetadataModel

.changeset/popular-pumpkins-grab.md, .github/workflows/main.yaml, .github/workflows/release-stable.yaml
=> Use `hive` pkg version for published Docker images

.changeset/few-mice-buy.md, cypress/e2e/app.cy.ts, cypress/support/commands.ts, packages/migrations/src/actions/2025.01.13T10-08-00.default-role.ts, packages/migrations/src/run-pg-migrations.ts, packages/services/api/src/modules/oidc-integrations/module.graphql.ts, packages/services/api/src/modules/oidc-integrations/providers/oidc-integrations.provider.ts, packages/services/api/src/modules/oidc-integrations/resolvers/Mutation/updateOIDCDefaultMemberRole.ts, packages/services/api/src/modules/oidc-integrations/resolvers/OIDCIntegration.ts, packages/services/api/src/modules/organization/providers/organization-manager.ts, packages/services/api/src/modules/shared/providers/storage.ts, packages/services/api/src/shared/entities.ts, packages/services/storage/src/db/types.ts, packages/services/storage/src/index.ts, packages/web/app/src/components/organization/members/common.tsx, packages/web/app/src/components/organization/members/list.tsx, packages/web/app/src/components/organization/members/roles.tsx, packages/web/app/src/components/organization/settings/oidc-integration-section.tsx
Closes #6346
This feature is only relevant to organizations with OIDC enabled.
Every new OIDC users is added to the organization with the default role.
If a default role has not been yet configured, the `Viewer` system role is used instead.
Default role has `default` badge and instructions how to change it
Actual setting
=> Customizable default member role for OIDC users

.github/workflows/on-mdx-change.yaml, packages/web/docs/package.json, packages/web/docs/src/pages/docs/api-reference/client.mdx, packages/web/docs/src/pages/docs/gateway/other-features/custom-plugins.mdx, packages/web/docs/src/pages/product-updates/2024-02-06-schema-contracts-for-federation.mdx
Uri gave me a pass to go on a refactor spree :) so I've split out `validate-mdx-links.yaml` from that big Nextra 4 PR to a new shared workflow.
This PR adds it here on a trigger _in PRs where MDX or pages change_ and fixes the broken and the outdated links.
- Broken: We had broken links in [gateway/other-features/custom-plugins](https://the-guild.dev/graphql/hive/docs/gateway/other-features/custom-plugins).
- Outdated: Some of the links were valid, but linking to an old route that was moved and had a rewrite still supporting it. I don't think it's worth to add rewrite handling to that validation script, because it makes sense to keep the links tidy and up to date anyway.
This is how it looks when it finds something:
=> Validate MDX links

packages/web/docs/src/pages/product-updates/2024-11-19-apollo-router-hive-versioning.mdx
Extracted out from #6089. (It looks like I'm farming PRs for a Hacktoberfest T-Shirt :D)
****
=> Fix 'MacOS' casing to 'macOS' in Apollo Router Hive Versioning

packages/web/docs/src/deps.d.ts, packages/web/docs/tailwind.config.ts, packages/web/docs/tsconfig.json
I'm extracting this out from #6089 to make it smaller and easier to review.
I don't see a reason for not checking for errors in config files. Gives us better autocomplete and in the case of Tailwind, it ensures we don't mess up styles by accident.
=> Start typechecking docs/tailwind.config.ts, add `flattenColorPalette` types

.changeset/good-countries-punch.md, packages/libraries/cli/package.json, packages/services/api/package.json, packages/services/schema/package.json, pnpm-lock.yaml
The `transformSupergraphToPublicSchema` removes now `@policy`, `@requiresScopes` and `@authenticated`.
The public schema shouldn't have them.
=> Update federation composition to 0.14.3

packages/web/docs/src/components/landing-page.tsx
Instead of a plain anchor to an "external" URL, we'll now render a Next.js Link.
=> Make the ecosystem link relative by passing `isHive`

packages/web/docs/src/components/landing-page.tsx
This PR:
- tweaks the mobile styles of "What is GraphQL Federation?" section,
- adds a highlight and arch decoration, and makes the inner margins (and by extension: height) the same as in "Get Started Today!" section
- changes the background of this section to a gradient between `#003834` and `#00342C` (yes, it's almost the same color).
=> Add a highlight and arch decoration & mobile tweaks

pnpm-lock.yaml
Closes https://github.com/graphql-hive/console/security/dependabot/240
=> Update nested dependency `katex` to address CVE

.changeset/stupid-candles-arrive.md, packages/web/app/src/lib/preflight-sandbox/graphiql-plugin.tsx, packages/web/app/src/lib/preflight-sandbox/lab-api-declaration.ts
"Teaches" the Script Editor that `lab` exists. Simple and useful for Preflight Script users.
=> Add typings for global.lab to Monaco Editor

.changeset/short-donkeys-live.md, packages/services/api/src/modules/operations/module.graphql.mappers.ts, packages/services/api/src/modules/operations/module.graphql.ts, packages/services/api/src/modules/operations/providers/operations-manager.ts, packages/services/api/src/modules/operations/providers/operations-reader.ts, packages/services/api/src/modules/operations/resolvers/ClientStats.ts, packages/services/api/src/modules/operations/resolvers/DurationValues.ts, packages/services/api/src/modules/operations/resolvers/OperationsStats.ts, packages/services/api/src/modules/operations/resolvers/SchemaCoordinateStats.ts, packages/web/app/src/components/target/insights/List.tsx, packages/web/app/src/components/v2/sortable.tsx
Impact equals to the total time spent on this operation in the selected period in seconds.
It helps assess which operations contribute the most to overall latency.
```
Impact = Requests * avg/1000
```
The result of that formula is formatted number:
```
1                = 1
1.5              = 1.5
10               = 10
10.5             = 11
100              = 100
554              = 554
1000             = 1K
1240             = 1.2K
10000            = 10K
10712            = 11K
100000           = 100K
321120.15        = 321K
1000000          = 1M
10000000         = 10M
100000000        = 100M
1000000000       = 1B
3123400000       = 3.1B
10000000000      = 10B
100000000000     = 100B
1000000000000    = 1T
10000000000000   = 10T
100000000000000  = 100T
```
A time unit could be used instead, …
=> Show Impact metric in the Operations list on the Insights page.

packages/web/docs/src/pages/docs/self-hosting/get-started.mdx
=> Make self-hosting/get-started.mdx up to date

package.json
This change will run `pnpm build:libraries` as part of the changeset version script, leading to updated `version.ts` file in the `Upcoming Release Changes` PRs.
=> Fix for version files changed locally during build

packages/libraries/cli/package.json, packages/libraries/cli/src/commands/introspect.ts, packages/libraries/cli/src/commands/schema/fetch.ts, packages/libraries/cli/src/helpers/errors.ts, packages/libraries/cli/src/hooks/command-not-found.ts, packages/web/docs/src/components/cli-errors.tsx, packages/web/docs/src/pages/docs/api-reference/cli.mdx
Documentation for https://github.com/graphql-hive/console/issues/207
Adds an errors section to the CLI documentation with an error name, code, example command that could trigger this error, example message output from that command, and a suggested fix.
https://3ef1450f.hive-landing-page.pages.dev/docs/api-reference/cli#errors for a demo
=> fix: add CLI error code docs; fix a few error messages

packages/migrations/tools/db-connection-string.cjs
https://github.com/graphql-hive/console/pull/6123 broke the `pnpm start` script locally.
Attempt loading environment variables using dotenv.
=> fix: load environment variables

packages/web/docs/src/components/pricing.tsx
This was incorrect:
We're using `step` instead of `Math.round` because it's not pay-for-usage rounded up to a million, you select a tier.
=> Add `step=1` to Pricing slider

scripts/seed-local-env.ts
Local development federated schema seed currently produces an invalid supergraph
```
FEDERATION=1 TOKEN="***" pnpm seed
```
This adds the necessary imports so that the federated directives are understood by the native schema composer and a valid federated supergraph is produced.
=> dev: fix local federated schema seeds

packages/web/docs/src/pages/docs/gateway/deployment/_meta.ts, packages/web/docs/src/pages/docs/gateway/deployment/resources-requirements.mdx, packages/web/docs/src/pages/docs/gateway/deployment/resources.mdx, pnpm-lock.yaml
Closes https://github.com/graphql-hive/gateway/issues/505
=> docs(gateway): added a new page with resources info

packages/web/docs/src/app/case-studies/(posts)/layout.tsx, packages/web/docs/src/app/case-studies/case-studies-styles.css
The yellow block now stops on the same level as the article text.
=> Stop overflowing the upsell block on top of the footer

.changeset/small-readers-melt.md, packages/services/usage/__tests__/usage-processor-2-validation.spec.ts, packages/services/usage/src/usage-processor-2.ts, packages/web/docs/src/content/specs/usage-reports.mdx
https://github.com/graphql-hive/console/issues/6468
- Improves the errors returned from the usage endpoint for an invalid JSON body.
- Updates the documentation to give an example of the response JSON body and expected status codes
=> improve errors for usage processor 2 format

.changeset/three-stingrays-do.md, packages/libraries/yoga/src/index.ts, packages/libraries/yoga/tests/yoga.spec.ts
We did not report the client info for responses handled by the response cache.
Fixes the client info extraction for response cache results and adds a test for it.
=> fix: missing client info with response cache

packages/services/cdn-worker/src/analytics.ts, packages/services/cdn-worker/src/artifact-storage-reader.ts, packages/services/cdn-worker/src/aws.ts
Cloudflare analytics only allows [collecting a total of 25 data points per request](https://developers.cloudflare.com/analytics/analytics-engine/limits/). Any additional calls will throw an error (`Analytics Engine write limit exceeded.`). 
**Note:** This adds a simple try/catch statement to prevent this error. We should probably keep track of the calls anyways and then log that we are skipping them.
Fixes https://github.com/graphql-hive/console/issues/6479 
Ref CONSOLE-1006
=> fix(cdn-worker): improve logging and ignore analytics engine errors

packages/services/api/src/modules/schema/providers/schema-publisher.ts
Introduces metrics `registry_publish_unexpected_error_count` and `registry_check_unexpected_error_count` for having a metric that shows us if we are having any unexpected errors aka potential outage of a third party service.
=> track error count for unexpected errors during schema publish/check

packages/web/docs/src/content/gateway/deployment/node-frameworks/nextjs.mdx
Fixes #6453
Examples should be copy-pasteable and not include changes that don't work or lack context.
=> Correct Hive Gateway Next.js example

packages/services/server/src/supertokens.ts, packages/services/server/src/supertokens/oidc-provider.ts
Logs here did not contain a request id, by using the logger from the request, will make debugging more simple.
=> use logger from request for request id reference

.changeset/gentle-badgers-itch.md, packages/libraries/core/src/client/http-client.ts, packages/libraries/core/tests/gateways.spec.ts, packages/libraries/core/tests/http-client.spec.ts, packages/libraries/core/tests/reporting.spec.ts, packages/libraries/core/tests/supergraph.spec.ts, packages/libraries/core/tests/test-utils.ts, packages/libraries/core/tests/usage.spec.ts
If a request from a customer fails, we have to dig into our logs to find the affected request. Instead, we should specify the request-id on the CLI/library level and log it so a customer can easily share it with us.
The main reason for this was the CLI, but it is useful for all our SDKs.
Instead of setting a request id on our gateway entry level, we can already start setting the request-id on the SDK/CLI level. This allows users to share the request id with us even if we fail to send a proper response due to unexpected errors.
Closes https://github.com/graphql-hive/console/issues/6487
=> include request id header in http-client

packages/services/api/src/modules/auth/lib/authz.ts, packages/services/api/src/modules/auth/lib/supertokens-strategy.ts, packages/services/api/src/modules/auth/lib/target-access-token-strategy.ts, packages/services/server/src/index.ts
I noticed that we are not logging the request-id for the new authorization layer logic.
Not sure if this is the best way to implement it, to be honest. I first tried to move this logic to a `graphql-modules` provider, but figured out that they cannot return a `Promise`.
=> feat: add request id to auth logs

.changeset/strange-shrimps-battle.md, integration-tests/testkit/cli.ts, integration-tests/tests/cli/schema.spec.ts, packages/libraries/cli/src/commands/schema/check.ts, packages/services/api/src/modules/schema/providers/schema-publisher.ts
We are kind of omitting important information here to display to the user by applying an unnecessary optimization.
=> fix: handle missing service error for federation project schema checks

packages/libraries/core/tests/usage.spec.ts
=> Fix flaky unit test in lib/core/usage.spec.ts

.changeset/tame-poets-flash.md, .changeset/tame-poets-slash.md, packages/libraries/cli/package.json, packages/services/api/package.json, packages/services/schema/package.json, pnpm-lock.yaml
https://github.com/the-guild-org/federation/releases/tag/v0.14.4
=> Update @theguild/federation-composition to 0.14.4

packages/web/docs/src/app/gateway/gateway-feature-tabs.tsx, packages/web/docs/src/components/feature-tabs.tsx
Since this is probably a one-off, and we already have a new design for this section, media queries seem like a good solution.
=> Fix cutoff tab text by providing a ReactNode

packages/web/docs/src/app/docs/[[...mdxPath]]/page.tsx, packages/web/docs/src/app/federation/page.tsx, packages/web/docs/src/app/gateway/page.tsx, packages/web/docs/src/app/layout.tsx, packages/web/docs/src/app/partners/page.tsx, packages/web/docs/src/app/product-updates/(posts)/layout.tsx
I updated `og:url` and `canonical` to work properly, but this should really be fixed upstream so we don't have to remember about it, because doing it in each page and layout is a bit error prone.
=> Fix og:url (this should work out of the box later)

configs/cargo/Cargo.lock, package.json, packages/libraries/external-composition/package.json, packages/services/broker-worker/package.json, packages/services/cdn-worker/package.json, packages/web/app/package.json, pnpm-lock.yaml
Closes https://github.com/graphql-hive/console/security/dependabot/257 
Closes https://github.com/graphql-hive/console/security/dependabot/259
=> chore(security): clean cves

.changeset/olive-walls-build.md, packages/services/cdn-worker/src/aws.ts, packages/services/cdn-worker/src/index.ts
Reading the response body (res.text()) after a fetch timeout can lead to an AbortError, making retries impossible. This change ensures the body is read immediately after the response is received, allowing it to be included in the retry logic.
By decoupling the response body from AbortSignal.timeout(), we prevent unexpected failures when the body is accessed later due to application logic delays. While this slightly increases memory usage, it ensures reliability when handling AWS S3 responses.
Closes CONSOLE-1064
=> Ensure response body is read before timeout to avoid abort errors

packages/libraries/core/tests/usage.spec.ts
I ran it 10 times locally before my change and it broke once
After the change, I ran it 30 times and did not get any failures
=> Fix flaky test: sendImmediately should not stop the schedule

packages/web/app/src/pages/target-explorer-deprecated.tsx
This is a bug I discovered when testing metadata.
When there is no usage, the deprecated schema view does not render. I assume this is because the deprecated view was based on the unused schema view. But for the deprecated schema, it doesnt make any sense to care about usage.
Removes the conditional check on usage for the deprecated schema view.
=> fix: show deprecated schema in explorer when there is no usage reported

.changeset/three-gifts-battle.md, packages/migrations/src/clickhouse-actions/012-coordinates-typename-index.ts, packages/migrations/src/clickhouse.ts
Improves the performance of the queries that filter the rows by the type's name.
For example, when looking for `Member.*` coordinates we eliminate the need to scan the whole table, by leveraging the `idx_typename` index. We filter rows by the first part of the coordinate field (`substringIndex(coordinate, '.', 1)`).
It helps ClickHouse to make 10% of the original work :)
Some numbers. Big queries that took 8-17s are now around 2s.
=> Adds bloom filter index to coordinates agg views

packages/web/app/src/components/target/explorer/filter.tsx, packages/web/app/src/components/v2/autocomplete.tsx
Currently to clear the type selection, the user must either go back in their history, must edit the url, or must re-navigate to the explorer. I think it's much more intuitive to offer a way to clear the selection in the dropdown component.
Adds a "X" to clear the type selection and retains the field search param between type selections.
=> fix: allow clearing explorer type selection

configs/cargo/Cargo.lock, packages/libraries/router/Cargo.toml, packages/libraries/router/src/persisted_documents.rs
The Apollo Federation Router was released in version 2 with some incompatible changes: https://github.com/apollographql/router/releases/tag/v2.0.0
This PR updates the different hive plugins to be compatible with the new version of the router.
It does not change the version. I don't know what will be your policy here.
=> update hive-apollo-router-plugin to be compatible with apollo-router v2

.changeset/gentle-camels-burn.md, .changeset/tidy-camels-double.md, configs/cargo/Cargo.lock, packages/libraries/router/Cargo.toml, packages/libraries/router/src/graphql.rs, packages/libraries/router/src/persisted_documents.rs, packages/libraries/router/src/usage.rs
Completes CONSOLE-1081
Continue the work from https://github.com/graphql-hive/console/pull/6535
=> fix(apollo-router-hive-plugin): update apollo-router to v2

packages/web/docs/src/components/ecosystem-management/index.tsx
This is using absolute positioning, because the position differs among breakpoints and we had a deadline :)
It's usually not a problem, but we didn't test it on mobiles after changing the texts of buttons, so we had a slight cutoff.
This tiny change makes the long buttons fit nicely on small, medium and large screen sizes.
We could consider rewriting it to overlapping named grid areas, but I'm not sure 100% if this would prevent the any layout bugs next time we change the buttons or add more of them.
=> Fix Ecosystem Management absolute positioning bug

packages/web/docs/src/content/get-started/apollo-federation.mdx
Checks dont take a URL -- only publish does
Fixes the examples in our apollo-federation documentation so that they are valid commands.
=> docs: fix example schema:check commands in apollo-federation docs

integration-tests/tests/api/oidc-integrations/crud.spec.ts, integration-tests/tests/api/organization/members.spec.ts, packages/services/api/src/modules/oidc-integrations/providers/oidc-integrations.provider.ts, packages/services/api/src/modules/organization/providers/organization-manager.ts, packages/services/api/src/modules/organization/resolvers/Organization.ts
https://linear.app/the-guild/issue/CONSOLE-1097/dashboard-membermodify-permission-error
The dashboard shows an error page when having `member:describe` but not `member:modify` permissions.
=> fix: members page with member:modify

packages/web/app/src/pages/target-explorer-deprecated.tsx, packages/web/app/src/pages/target-explorer-type.tsx, packages/web/app/src/pages/target-explorer.tsx
Small bug on the metadata filter where when metadata is all removed from a subgraph, an empty array is returned from the API which causes the filter to still show even though it's empty.
This correctly hides the metadata filter on the explorer if there are no values in the metadata returned.
=> fix: show meta filter on explorer only if there is meta

.changeset/honest-apples-tap.md, docker/shared/entrypoint.sh
For us (and potentially self-hosters) to take a heap snapshot of running processes.
```
$ ps aux
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
node         1  5.5  6.1 787252 247004 ?       Ssl  16:43   0:02 node --heapsnapshot-signal=SIGUSR1 index.js
$ kill -USR1 1
$ ls
Heap.20190718.133405.15554.0.001.heapsnapshot 
```
=> Write a heap dump to a disk when SIGUSR1 signal is received

deployment/index.ts, deployment/services/observability.ts, deployment/utils/observability.ts
In https://github.com/graphql-hive/console/pull/6351 we changed some of the resources configurations for otel-collector.
This PR adjusts it back for staging/dev, because they don't such such high amount of cpu/memory.
=> fix(deployment): adjust the resources needed for otel-collector in each env

packages/web/docs/src/components/pricing/pricing-slider.tsx, packages/web/docs/src/components/slider.tsx
We previously had a comma in the slider indicator tooltip.
In the updated design it was moved up.
Added the number of operations to the "how many you need?" label.
Forgive me the messy CSS, but I didn't want to overcomplicate it with a library, and the fact that we already had a CSS var for `--ops` made transitions pretty trivial. Tried to limit the jittering of the text, which is also why we're using `tabular-nums` variant of the font with reduced letter spacing to compensate.
=> pricing operations in label

packages/services/api/src/modules/schema/providers/schema-version-helper.ts, packages/services/schema/package.json, packages/services/schema/src/orchestrators.ts, pnpm-lock.yaml
Follow-up https://github.com/graphql-hive/console/pull/6586 to apply the merging logic to the schema that's written to db.
Proof it works when the post-fix (#6586) is disabled - https://github.com/graphql-hive/console/actions/runs/13705781167
=> Prevent compositeSchemaSdl from having type extensions

.changeset/wet-panthers-notice.md, integration-tests/tests/api/schema/unused.spec.ts, packages/services/api/package.json, packages/services/api/src/modules/schema/providers/schema-version-helper.ts, packages/services/schema/package.json, packages/services/schema/src/orchestrators.ts, pnpm-lock.yaml
The logic that converts SDL into a GraphQL schema representation was ignoring fields from type extensions. Since this representation is what gets fed into the resolvers, those fields were never rendered as unused parts of the schema in the app. It only affected monolithic schemas (`single` projects).
I used `@graphql-tools/merge` to merge type extensions into their base types. Now, type extensions aren't left behind.
=> Ensure type extension fields are properly considered in unused schema detection

.changeset/itchy-grapes-do.md, packages/web/app/src/pages/target-insights-operation.tsx
Resolves https://github.com/graphql-hive/console/issues/5582
=> fix: show insight not found instead of loading

packages/web/docs/src/content/gateway/logging-and-error-handling.mdx
To enable JSON logging, it should be `LOG_FORMAT=json` not `LOG_LEVEL=json`
=> Fix log format environment variable name

packages/web/docs/next.config.js
NestJS docs have been added so we no longer need a redirection
=> docs(gateway): remove NestJS to Nodejs redirection

packages/web/docs/src/content/api-reference/gateway-cli.mdx, packages/web/docs/src/content/gateway/usage-reporting.mdx, packages/web/docs/src/content/get-started/apollo-federation.mdx
Merge after https://github.com/graphql-hive/gateway/pull/809
=> docs: use --hive-usage-* variants for the gateway usage reporting

.changeset/sixty-chicken-swim.md, deployment/index.ts, deployment/services/graphql.ts, deployment/utils/publish-app-deployment.ts, deployment/utils/publish-graphql-schema.ts, deployment/utils/service-deployment.ts, packages/services/server/README.md, packages/services/server/src/environment.ts, packages/services/server/src/graphql-handler.ts, packages/services/server/src/index.ts
Changes the deployment configuration to use organization access tokens instead of target access tokens.
Small cleanup of environment variables.
Requires https://github.com/graphql-hive/deployment/pull/1439
=> feat(deployment): use organization access tokens

packages/web/docs/src/app/_meta.ts
I inadvertently added "Hive Gateway" to sidebar, causing a duplicate React key error, because I forgot about adding it to `_meta.ts` as `hidden`, and Nextra added it automatically based on the directory structure.
We already have "Gateway" entry in the sidebar that goes to the part of docs about Hive Gateway.
Linking from docs back to landing page feels off, overtly salesy, so this PR removes the newest `href=/gateway` entry.
=> Remove duplicate "Gateway" item in sidebar

.changeset/tiny-glasses-talk.md, packages/libraries/core/src/client/client.ts, packages/libraries/core/src/client/types.ts, packages/libraries/core/src/client/usage.ts, packages/libraries/core/tests/usage.spec.ts
This adds a bit more context when using any combinations of the `target` and `token` config option.
Not sure if it is really needed, but it could potentially help people figure out what is wrong with their configuration.
=> feat(sdk): better handling of token info and usage configuration

packages/web/docs/src/app/product-updates/(posts)/2025-03-20-dangerous-change-approval/page.mdx
Product update for https://github.com/graphql-hive/console/pull/6626
Self explanatory.
=> Add product update for dangerous change approvals

integration-tests/testkit/flow.ts, integration-tests/tests/api/policy/policy-access.spec.ts, packages/services/api/src/modules/project/module.graphql.ts, packages/services/api/src/modules/project/providers/project-manager.ts, packages/services/api/src/modules/project/resolvers/Query/project.ts, packages/services/api/src/modules/shared/providers/id-translator.ts, packages/services/api/src/modules/shared/providers/storage.ts, packages/services/storage/src/index.ts, packages/web/app/src/components/project/settings/external-composition.tsx, packages/web/app/src/components/project/settings/native-composition.tsx, packages/web/app/src/pages/project-alerts.tsx, packages/web/app/src/pages/project-policy.tsx, packages/web/app/src/pages/project-settings.tsx, packages/web/app/src/pages/target-checks-single.tsx, packages/web/app/src/pages/target-history-version.tsx, packages/web/app/src/pages/target-settings.tsx, packages/web/app/src/pages/target.tsx
- Changes `Query.project` to use our new patterns for resolving a resource.
- Adds the basic `Project` type and `Query.project` to the public GraphQL API.
=> feat(api): refactor Query.project + expose via public API

.changeset/silent-stingrays-visit.md, packages/web/app/src/components/ui/user-menu.tsx
Current link shows:
This corrects the link so that it's valid.
=> fix: correct the schedule a meeting cal link

deployment/services/environment.ts, deployment/services/proxy.ts
Adjust the proxy configuration to redirect
```
https://api.graphql-hive.com/graphql
https://api.dev.graphql-hive.com/graphql
https://api.staging.graphql-hive.com/graphql
```
to `graphql-api/graphql-public`
=> feat(deployment): add public graphql api route

packages/web/docs/src/content/gateway/monitoring-tracing.mdx
`client` property takes options not the client itself
=> docs(gateway): fix statsd configuration

packages/services/api/src/modules/shared/module.graphql.ts, packages/services/server/src/public-graphql-handler.ts
The `@oneOf` directive was stripped out of the public API definitions, as it was not retained in the federation composition.
=> fix: retain `@oneOf` in public api

packages/web/docs/src/app/layout.tsx
Fixed the link. We now go to the new blog in the Hive website.
=> Update the link to go to Hive blog

.changeset/chilly-bobcats-smile.md, packages/web/app/src/components/ui/resource-details.tsx
This is something @dotansimha brought to my attention. The icon previously showed a cursor pointer on hover, making you think you needed to click. However, clicking causes the tooltip to hide.
This reduces to hover delay to 0 so the tooltip shows instantly on hover, and adjusts the cursor to be the default look.
=> Improve resource id tooltip interaction

packages/services/server/src/use-armor.ts
Follow up for https://github.com/graphql-hive/console/pull/6686
Setting `flattenFragments` to `false` makes the query depth limit plugin behave the same as our `graphql-inspector validate` command.
- https://github.com/graphql-hive/graphql-inspector/issues/2878
=> fix: adjust query depth

.changeset/rotten-roses-sip.md, packages/libraries/cli/src/commands/schema/check.ts, packages/libraries/cli/src/commands/schema/delete.ts, packages/libraries/cli/src/commands/schema/fetch.ts, packages/libraries/cli/src/helpers/schema.ts, packages/services/api/src/modules/schema/module.graphql.ts, packages/services/api/src/modules/schema/resolvers/SchemaChange.ts, packages/web/app/src/components/target/history/errors-and-changes.tsx, packages/web/app/src/pages/target-checks-single.tsx, packages/web/app/src/pages/target-history-version.tsx
`CriticalityLevel` does not follow our specified conventions.
- Enum types should end with `Type`
- Enum type fields should be in upper snake case
`SeverityLevelType` replaces `CriticalityLevel` and follows the specified criteria.
This PR also adjusts both CLI and our App to use these new fields.
=> feat(api): add `SeverityLevelType`

integration-tests/tests/cli/__snapshots__/schema.spec.ts.snap, integration-tests/tests/cli/schema.spec.ts
Tests https://github.com/graphql-hive/console/pull/6694
I wrote this test and ran before the fix PR:
Then ran against latest:
=> test: retain service on next schema if url if not in input

codegen.mts, deployment/utils/publish-app-deployment.ts, deployment/utils/publish-graphql-schema.ts, package.json, packages/services/api/src/modules/shared/module.graphql.ts, packages/services/api/src/modules/shared/resolvers/Subscription/_.ts, packages/services/server/src/public-graphql-schema.ts, patches/@graphql-codegen__schema-ast.patch, pnpm-lock.yaml
We want to transform the `the-guild/graphql-hive` project on hive into a federation project so we can leverage contracts for getting schema diffs. This requires a few adjustments so the GraphQL schema is accepted by our API.
**Note:** After merging this PR additional database edits are needed. I tested these steps on `dev`.
1. Find the latest schema version in our database
2. Add a service name (`graphql`) and service url on the database record
3. Make sure native composition is enabled for the project
=> chore: make graphql schema ready for hive federation project 

.changeset/brave-snails-design.md, packages/services/api/src/modules/alerts/providers/adapters/slack.ts, packages/services/api/src/modules/schema/providers/registry-checks.ts
When investigating other sentry errors, I noticed that the "channel_not_found" was coming up relatively frequently. This error is due to the channel not existing and is not an error on our end that is worth tracking.
I've adjusted the error level to be a warning, which makes more sense, and have improved the logs to include some details about the error. Currently, the error logs only show `"msg":"Failed to send Slack notification ..."`
=> Slack error logs

packages/services/api/src/modules/schema/providers/registry-checks.ts
Someone managed to publish an empty service url to a federation project, which resulted in a runtime exception as `""` is treated as falsy by default.
=> fix(api): improve emtpy value assertion

deployment/grafana-dashboards/redis.json, deployment/services/redis.ts, deployment/utils/observability.ts, deployment/utils/redis.ts
=> fix: added Grafana metrics for Redis instance

deployment/utils/redis.ts
Recent outage of webhooks caused by redis filling up and emitting an unhandled error because of maxmemory set here https://github.com/graphql-hive/console/pull/6737
Currently, the maxmemory policy is `noeviction` which is causing memory to fill up past its limit.
=> Add maxmemory policy volatile-ttl

packages/libraries/router/README.md, packages/web/docs/src/content/other-integrations/apollo-router.mdx, pnpm-lock.yaml
=> fix(docs): updated usage example of apollo-router plugin as a rs lib

packages/services/schema/src/composition-scheduler.ts, packages/services/schema/src/composition-worker.ts
If the worker thread throws an uncaught exception, the worker thread stops receiving messages and `postMessage` from the main thread will hang.
This is because when the worker thread calls process.exit, it does not report the error to the main process
To resolve this, we should not capture this error and should instead allow the main thread to capture and handle the error.
=> Exit the worker thread correctly instead of hanging

packages/web/docs/src/content/specs/usage-reports.mdx
The default body size 15MB: https://github.com/graphql-hive/console/blob/70bc7a862a20a65550ccdafbd1fac6950955e3c4/packages/services/service-common/src/fastify.ts#L21 , and we do no override it for usage service.
=> fix(docs): update max body size for usage service

.changeset/tender-flowers-refuse.md, packages/services/usage/src/fallback-queue.ts, packages/services/usage/src/usage.ts
The short form is that when we push the the fallback producer queue, our buffer is never set back to the `Ready` status.
And the pod is killed after the grace period -- `terminationGracePeriodSeconds: 60,`
The most recent case when this happend looked like this:
which supports this theory.
This change addresses the readiness logic to make sure after the fallback queue is processed, that the state is changed back to Ready.
The one thing I am not entirely sure about is why the memory shows such a dramatic spike. All other metrics make sense (503s, kafka latency ... ).
=> Reduce retry counts; adjust usage producer fallback logic

.changeset/gorgeous-news-report.md, deployment/services/usage.ts, packages/services/usage/src/buffer.ts, packages/services/usage/src/fallback-queue.ts, packages/services/usage/src/index.ts, packages/services/usage/src/usage.ts
We've been investigating an issue with the usage producer where the memory spikes and the service may or may not crash or remain with high memory. 
The fallback/retry logic was adjusted here https://github.com/graphql-hive/console/pull/6755
This PR reduces the failure threshold for readiness with usage service.
We know that there's a window where requests can continue to be made to the usage service after it's flagged as unhealthy. I had incorrectly thought previously, that these messages were being send to kafka via our producer in the normal (non-fallback) flow, even though the service was unhealthy. _However_, inside the endpoint's handler, we check readiness of the usage client and if it's unhealthy, return a 503.
To reduce the number of 503s, we should be more aggressive with the …
=> Reduce usage service readiness threshold

.changeset/weak-crabs-approve.md, integration-tests/tests/api/target/usage.spec.ts, integration-tests/tests/cli/__snapshots__/schema.spec.ts.snap, integration-tests/tests/cli/schema.spec.ts, packages/libraries/cli/src/helpers/errors.ts
https://linear.app/the-guild/issue/CONSOLE-1098/cli-add-optional-flag-to-exit-with-1-if-composition-fails
We got a report that composition failures were not exiting with code(1) on error.
OCLIF was not being passed the exit code. This fixes the exitcode passing so that we can control what the exit code is based on the error we throw.
After fix:
```
➜  cli git:(main) ✗ pnpm start dev \
--registry.accessToken "25eb3969ecfca640645d6f50e7ef9bc2" \
--target "82804777-0061-49d0-8bb0-201668f079d4" \
--service reviews --url http://localhost:3001/graphql --schema examples/federation.reviews.graphql \
--service products --url http://localhost:3002/graphql --schema examples/federation.products.graphql
> @graphql-hive/cli@0.49.1 start /Users/jdolle/guild/console/packages/libraries/cli
> ./bin/dev dev …
```
=> Specify oclif exitcode in cli errors

packages/services/api/src/modules/support/providers/support-manager.ts
https://linear.app/the-guild/issue/CONSOLE-1232/support-ticket-failed-with-internal-server-error
A customer was unable to submit a support ticket and retried 3x. Each time failing the user lookup.
The current URL is to get a list of users, but is not searching that list. We should be using: https://developer.zendesk.com/api-reference/ticketing/users/users/#search-users
And this returns a list of users that match. And on the off chance that users have an email that is a partial match to another email in our system, we should find the email in the returned list instead of checking the first.
=> fix: support ticket user lookup

.changeset/fifty-deers-shake.md, packages/services/schema/src/api.ts, packages/services/schema/src/lib/__tests__/federation-tag-extraction.spec.ts, packages/services/schema/src/lib/__tests__/reachable-type-filter.spec.ts, packages/services/schema/src/lib/federation-tag-extraction.ts
https://linear.app/the-guild/issue/CONSOLE-1239/adjust-contract-logic-to-allow-empty-mutations
Contract behavior is to remove types that have all inaccessible fields. However, currently all root types are kept. This causes issues because per graphql, only the Query type needs to be defined in a schema.
This change adjusts the contracts logic so that only the root query type is kept no matter what.
=> Contract root types

integration-tests/tests/api/schema/external-composition.spec.ts
Make sure no schema version is created for external composition errors
=> chore: ensure no schema version is created for external composition error

.changeset/fluffy-rice-build.md, packages/migrations/src/actions/2025.05.14T00-00-00.cascade-deletion-indices-2.ts, packages/migrations/src/run-pg-migrations.ts, pnpm-lock.yaml
Large organizations are hitting timeouts when trying to delete their organization.
One such call ran for over 10min.
To address this performance issue and to allow organizations to self-serve, I've added an index for every foreign key that uses cascading deletes.
This should significantly improve the speed of this operation because when a delete is cascading, it must find those records in the table to perform the delete. Without an index, it must scan through all records.
=> Add pg indexes to help with org delete

.changeset/nine-timers-complain.md, packages/migrations/src/actions/2025.05.15T00-00-00.redundant-indices.ts, packages/migrations/src/run-pg-migrations.ts
As part of finding missing indices for cascading deletes, I discovered some btree indices that are already covered by multi column btree indices.
This removes these single column btree indices in favor of letting pg use the multi column. This should have no performance impact and reduce pg footprint.
=> Remove redundant indices

.changeset/wild-walls-pump.md, packages/web/app/src/components/ui/date-range-picker.tsx
The date selector is slightly unclear. The calendar buttons are not obvious that they are buttons because the background is so faint. And its title indicates it can select time, not just date.
Before:
After:
=> Adjust date selector ui

packages/services/api/src/modules/schema/providers/schema-publisher.ts
We never log the schema check id - making it hard to find the request id from the schema check id in order to see all the logs of the schema check flow.
=> feat: log schema check id

packages/web/app/src/pages/target-settings.tsx
We previously used a different character for token masking. The function I added standardizes it by replacing all non-alphanumeric characters with bullet points (•) to ensure consistent formatting.
I also added font-mono class to better display the token alias. Previously at some point of the string the line was broken and some characters were displayed higher than the rest.
| Before | After |
|--------|-------|
| ![Screenshot 2025-05-16 at 09 03 53](https://github.com/user-attachments/assets/bede245c-e53c-404a-abbb-119622020960) | ![Screenshot 2025-05-16 at 09 03 41](https://github.com/user-attachments/assets/b9150b87-33ca-4681-bc89-56fb8742a16f) |
=> fix: normalize token alias display with consistent masking symbols

integration-tests/testkit/flow.ts, integration-tests/testkit/graphql.ts, integration-tests/testkit/seed.ts, integration-tests/tests/api/app-deployments.spec.ts, integration-tests/tests/api/legacy-auth.spec.ts, integration-tests/tests/api/organization/get-started.spec.ts, integration-tests/tests/api/rate-limit/emails.spec.ts, integration-tests/tests/api/schema/unused.spec.ts, integration-tests/tests/api/target/usage.spec.ts, integration-tests/tests/api/tokens.spec.ts
Integration tests currently contain a lot of `waitFor` calls which are static wait periods to ensure certain async operations are processed. To avoid excessively flaky tests, the wait period must exceed what is typically necessary. This time adds up.
A `pollFor` testkit function was recently added. This PR makes use of, and enhances that function, to improve test consistency and speed.
`tests/api/target/usage.spec.ts` was especially impacted by this change. Locally, the time to run these tests went from 87s to 26s.
=> tests: Use pollFor logic instead of static wait times in integration tests

packages/web/docs/src/content/self-hosting/get-started.mdx
Was looking at the self-hosted docs and found a link which didn't work as expected.
Fixed the link by replacing it with the new URL
=> Fix broken link

packages/services/api/src/modules/commerce/resolvers/Organization.ts, packages/services/commerce/src/stripe-billing/index.ts
We recently had an issue where a customer was unable to update their payment information even though they have an active subscription.
This adds logs to help us better understand if the missing payment method case is happening. And it updates the payment method call to use stripe's recommended "List Customer Payment Methods" api
=> Add logs for active subscriptions that are missing payment methods

.changeset/olive-ghosts-shout.md, packages/services/api/src/modules/collection/module.graphql.ts, packages/services/api/src/modules/collection/resolvers/Target.ts, packages/web/app/src/lib/preflight/graphiql-plugin.tsx
We show the edit preflight script button and allow editing it even though user does not have the permissions and the http call to save the updates will fail.
=> fix: only show edit perflight script button if user has permissions

packages/web/docs/src/content/other-integrations/apollo-gateway.mdx
Update apollo-gateway example and pass `server` correctly (see https://www.apollographql.com/docs/apollo-server/api/standalone)
=> docs(apollo-gateway): fix `startStandaloneServer` usage

packages/services/commerce/src/stripe-billing/index.ts
The condition doesn't make any sense, it's overriding the email to the one we have on record. Since subscription's main email is managed externally on Stripe, we don't really need to hold it on our end, or update it at all. A follow up PR can even remove this column from the database, as I don't this it's being used. 
Users are able to update their billing email using the Stripe magic link. 
Fixes CONSOLE-1308
=> fix(commerce): avoid overriding email when updating subscription

integration-tests/tests/schema/contracts.spec.ts, packages/services/schema/src/lib/federation-tag-extraction.ts
https://linear.app/the-guild/issue/CONSOLE-1322/investigate-errors-with-public-contract-field-tagging
External fields cannot have `@tag` or `@inaccessible` added to them. Currently, "include" contracts require a `@tag` to avoid adding an `@inaccessible` directive. So an "include" contract cannot have external field unless it's marked with the tag in the non-external subgraph.
This fixes this case by not running the contract logic on external fields. The accessibility lies with the non-externalized definition.
=> fix: dont touch external fields or objects in contract logic

packages/web/docs/src/content/graphql-api/target-management.mdx
Delete target is public but is missing from our docs.
Adds doc with example operation
=> docs: Add delete target docs

packages/web/docs/src/app/blog/(posts)/graphql-codemod-use-case-migrating-from-apollo-client-generated-hooks-to-client-preset/page.mdx
This PR adds a new blog post for using GraphQL codemod to migrate to Client Preset
=> Add GraphQL Codemod blog post

packages/web/docs/src/content/gateway/logging-and-error-handling.mdx
If I see your published packages correctly, @graphql-hive/winston has only been published as an alpha version and was succeeded by @graphql-hive/logger-winston
=> docs: update to logger-winston

.changeset/swift-parents-divide.md, packages/libraries/cli/src/base-command.ts, packages/web/docs/src/content/gateway/other-features/security/demand-control.mdx
If the hive.json is used but a specific key is not provided, then the Config.get logic returns null, not undefined.
`packages/libraries/cli/src/helpers/config.ts`
This causes the fallback logic to not run and the value to be set to null in this case.
This change checks for null and undefined before falling back to the defaultValue.
=> Hive json default

.changeset/late-rules-fail.md, packages/services/api/src/modules/organization/resolvers/Organization.ts, packages/web/app/src/components/organization/members/resource-selector.tsx, packages/web/app/src/components/organization/settings/access-tokens/create-access-token-sheet-content.tsx, packages/web/docs/src/content/gateway/logging-and-error-handling.mdx, packages/web/docs/src/content/gateway/other-features/security/demand-control.mdx, pnpm-lock.yaml
https://github.com/graphql-hive/console/issues/6920
Fixes the toggling between services and app deployments to address the select / all buttons.
=> fix: correct selecting "all" app deployments when creating an access token

.changeset/happy-wasps-vanish.md, packages/libraries/router/src/registry.rs
```
use std::env;
fn main() {
let file_name = env::temp_dir()
.with_file_name("supergraph-schema.graphql")
.to_string_lossy()
.to_string();
assert_eq!(file_name, "/tmp/supergraph-schema.graphql")
}
```
results in:
```
thread 'main' panicked at src/main.rs:9:5:
assertion `left == right` failed
left: "/supergraph-schema.graphql"
right: "/tmp/supergraph-schema.graphql"
```
If the file is written to root, it is problematic when configuring the container to run as non-root user
Concat filename to temp directory
=> fix: ensure file is written in temp dir

scripts/generate-changelog.js
The current implementation of `generate-changelog.js` calls `Date.toLocaleString()` with `undefined` as the first parameter. This generates locale-dependent results, which can be non-ISO-8601-compliant and therefore error in the usages. This was generated in my case:
```ts
export const latestChangelog = [
{
"date": "2025년 9월 15일",
"href": "https://the-guild.dev/graphql/hive/product-updates/2025-09-15-unused-deprecated-schema-graphql-api",
"title": "Find unused Types and deprecated Fields via the Hive Console API",
"description": "You can now automate finding deprecated fields and unused schema parts via the Hive Console GraphQL API."
},
{
"date": "2025년 9월 3일",
"href": "https://the-guild.dev/graphql/hive/product-updates/2025-09-03-schema-proposals",
"title": "Schema Proposals Preview", …
```
=> fix: use consistent format for changelog dates

.changeset/full-moments-sleep.md, .changeset/moody-radios-switch.md, packages/web/app/src/components/target/insights/Filters.tsx, packages/web/app/src/components/target/insights/List.tsx, packages/web/app/src/lib/urql.ts, packages/web/app/src/pages/target-insights.tsx, scripts/seed-local-env.ts
https://linear.app/the-guild/issue/CONSOLE-1359/investigate-case-sensitivity-bug-in-hive-insights-tab
We received a report of filtering not behaving correctly on the operations list view.
This passes the list of operations to the query so that the requested list includes only those operations. This is to avoid over fetching and having to filter client side.
And I've adjusted the dropdown for the operation list on insights so that it shows the number of requests for the selected clients filter, and the total count.
If we like this, then we can apply the same logic to the client dropdown so that each accurately reflects what will be shown once filtered.
=> pass selected operations filter to query for pagination; add operation counts by selected client

.changeset/bitter-goats-bow.md, packages/libraries/cli/src/commands/app/create.ts
https://linear.app/the-guild/issue/CONSOLE-1378/hive-cli-appcreate-retries-and-never-exits-on-its-own
Investigating this shows that perhaps app:create is working but is taking a long time due to a large number of documents.
This change adds a progress log so that in these cases, users can see why this command is taking so long and roughly estimate the remaining time.
=> add progress log to cli app:create command

packages/web/docs/src/app/blog/(posts)/public-graphql-schema-federation-contracts/page.mdx
=> Refine language for clarity in blog post

.changeset/stale-mice-push.md, packages/web/app/src/components/target/explorer/filter.tsx, packages/web/app/src/components/target/explorer/provider.tsx
If you try typing in the current input, it will kick your cursor to the end of the input text. This is because it has an issue with rerendering that element which causes the input text state to get lost.
This fixes the re-rendering in several places by using callbacks/memos -- making the page more efficient and fixing the problem behavior.
=> fix: explorer field filter input cursor reset

.changeset/wild-bags-know.md, packages/services/api/src/modules/operations/providers/operations-manager.ts, packages/services/api/src/modules/operations/providers/operations-reader.ts, packages/services/api/src/modules/schema/resolvers/DeprecatedSchemaExplorer.ts, packages/services/api/src/modules/schema/resolvers/SchemaExplorer.ts, packages/services/api/src/modules/schema/resolvers/SchemaVersion.ts, packages/services/api/src/modules/schema/utils.ts
Some big GraphQL schemas exhaust resources via the deprecated schema explorer GraphQL types and fields.
Add memoization for the type stats lookup, to prevent allocating a lot of objects.
=> fix: oom for deprecated schema explorer

packages/web/app/src/pages/target-laboratory.tsx, packages/web/docs/next.config.js
recent docs change adjusted paths
Fixes https://github.com/the-guild-org/website/issues/1864
Locally these redirects worked as they were. It's unclear why production behavior is different.
=> docs: fix missing docs redirects

packages/web/docs/src/content/gateway/deployment/node-frameworks/express.mdx
Docs to describe https://github.com/graphql-hive/gateway/pull/1148
=> docs(express.mdx): describe renderGraphiQL option usage

.changeset/six-socks-turn.md, packages/web/app/src/lib/billing/stripe.tsx
https://github.com/graphql-hive/console/issues/6635
Update to show a message if stripe is blocked
just return some text if stripe is blocked - just tested launching the block in a loadable page
=> update stripe to show a message if it's blocked
