graphql-hive/console

packages/web/app/pages/[orgId]/[projectId]/[targetId]/history.tsx
=> Version ID was missing in diff view

packages/web/app/pages/[orgId]/[projectId]/[targetId]/history.tsx, packages/web/app/pages/[orgId]/[projectId]/[targetId]/index.tsx, packages/web/app/src/graphql/query.target-latest-schema.graphql
fixes https://github.com/kamilkisiela/graphql-hive/issues/67
=> fix pagination on versions page

packages/web/app/pages/[orgId]/subscription/manage.tsx, packages/web/app/src/components/organization/billing/BillingPlanPicker.tsx
https://tortilla-hq.slack.com/archives/C01E8ATBQGN/p1653418017922249?thread_ts=1653413551.768489&cid=C01E8ATBQGN
=> fix subscription styles on mobile

packages/web/app/pages/[orgId]/subscription/manage.tsx, packages/web/app/src/components/organization/billing/Billing.tsx, packages/web/app/src/components/organization/billing/PlanSummary.tsx, packages/web/app/src/graphql/fragments.graphql
Closes https://github.com/kamilkisiela/graphql-hive/issues/95
=> Show the correct retention for Subscription

packages/web/app/pages/[orgId]/[projectId]/[targetId]/index.tsx
=> Hide MarkAsValid button for people without access

packages/web/app/src/components/admin/AdminStats.tsx
Reverts kamilkisiela/graphql-hive#108
=> Revert "Added rate-limit and subscription plan to admin stats"

packages/services/storage/src/index.ts
=> Batch Storage.getOrganizationMembers calls

packages/web/app/src/components/v2/dropdown.tsx, packages/web/app/src/components/v2/header.tsx, packages/web/app/src/components/v2/icon.tsx
=> remove similar icons from header dropdown

packages/web/app/package.json, packages/web/app/pages/_app.tsx, packages/web/app/pages/_document.tsx, packages/web/app/pages/index.tsx, packages/web/app/src/components/auth/AuthProvider.tsx, packages/web/app/src/components/common/GlobalStyles.tsx, packages/web/app/src/components/layouts/organization.tsx, packages/web/app/src/constants.ts, packages/web/app/src/lib/gtag.ts, yarn.lock
fixes https://github.com/kamilkisiela/graphql-hive/issues/101
Becuase we make redirect in `pages/index.ts` in `getServerSideProps()` - `localStorage` is not available on server.
So I installed `js-cookie` to set the last visited org on the client and `cookies` package to retrieve cookie value on the server.
It's working pretty well.
=> 2. save last visited organization in cookies

integration-tests/fixtures/federation-init.graphql, integration-tests/testkit/flow.ts, integration-tests/tests/cli/schema.spec.ts, packages/services/api/src/modules/schema/providers/schema-publisher.ts, packages/services/cdn-worker/src/handler.ts, packages/services/schema/src/orchestrators.ts
=> Fix missing service url in supergraph

.eslintrc.cjs, packages/services/rate-limit/src/index.ts, packages/services/usage-estimator/src/index.ts
https://tortilla-hq.slack.com/archives/C01E8ATBQGN/p1655664774169639
=> forbid `stop` global variable

packages/web/docs/pages/features/monitoring.mdx, packages/web/docs/pages/features/publish-schema.mdx, packages/web/docs/pages/specs/integrations.md
https://github.com/charlypoly/graphql-ruby-hive
----
=> doc: Graphql Ruby integration

.changeset/strong-pandas-brake.md, integration-tests/docker-compose.yml, integration-tests/dockest.ts, integration-tests/testkit/flow.ts, integration-tests/tests/api/schema/publish.spec.ts, integration-tests/tests/api/target/usage.spec.ts, package.json, packages/libraries/cli/src/commands/schema/publish.graphql, packages/libraries/cli/src/commands/schema/publish.ts, packages/libraries/client/src/version.ts, packages/services/api/src/modules/schema/module.graphql.ts, packages/services/api/src/modules/schema/providers/schema-manager.ts, packages/services/api/src/modules/schema/providers/schema-publisher.ts, packages/services/api/src/modules/schema/resolvers.ts, packages/services/api/src/modules/shared/providers/storage.ts, packages/services/storage/src/index.ts, yarn.lock
Reverts kamilkisiela/graphql-hive#153
=> Revert "Simplify the schema publishing logic"

integration-tests/docker-compose.yml, integration-tests/package.json, integration-tests/testkit/dockest.ts, packages/services/storage/docker-compose.yml, packages/services/usage-ingestor/package.json, packages/services/usage/package.json, yarn.lock
No more issues with kafka and zookeeper
=> Improve integration-tests setup

packages/libraries/client/src/internal/reporting.ts, packages/libraries/client/src/internal/types.ts, packages/libraries/client/src/internal/usage.ts, packages/libraries/client/src/internal/utils.ts
This should give better feedback to people, because based on issues like SENTRY-2632938996, GraphQL's validation is limiting us.
=> Show warnings in Client when commit, author or token are missing

packages/services/api/src/modules/schema/module.graphql.ts, packages/services/api/src/modules/schema/providers/schema-publisher.ts, packages/services/api/src/modules/schema/providers/schema-validator.ts
=> Indicate an initial version in Mutation.schemaCheck

.changeset/nice-geese-learn.md, integration-tests/fixtures/missing-type.graphql, integration-tests/tests/cli/schema.spec.ts, packages/libraries/cli/src/commands/schema/check.graphql, packages/libraries/cli/src/commands/schema/check.ts
=> Add message about empty schema registry in schema:check

deployment/index.ts, deployment/package.json, deployment/services/tokens.ts, deployment/services/usage-ingestor.ts, deployment/services/webhooks.ts, package.json, packages/libraries/cli/src/base-command.ts, packages/services/service-common/package.json, packages/services/service-common/src/heartbeats.ts, packages/services/service-common/src/helpers.ts, packages/services/service-common/src/index.ts, packages/services/tokens/src/index.ts, packages/services/usage-ingestor/src/index.ts, packages/services/webhooks/src/index.ts, yarn.lock
Support BetterUptime Heartbeats
=> Add heartbeats to tokens, webhooks and usage-ingestor services

packages/web/app/pages/manage/index.tsx, packages/web/app/src/components/target/operations/List.tsx, packages/web/app/src/components/v2/sub-header.tsx, packages/web/app/src/lib/urql-cache.ts, packages/web/app/src/lib/urql.ts, packages/web/app/tsconfig.json
one step closer to https://github.com/kamilkisiela/graphql-hive/issues/63
=> feat: strict function types

packages/services/tokens/src/index.ts, packages/services/usage-ingestor/src/index.ts, packages/services/webhooks/src/index.ts
To match the env var of deployment code
=> Rename HEARTBEATS_ENDPOINT to HEARTBEAT_ENDPOINT

packages/web/app/src/components/common/activities/common.tsx, packages/web/app/src/components/v2/activities.tsx, packages/web/app/src/graphql/query.organization-activities.graphql, packages/web/app/src/graphql/query.project-activities.graphql, packages/web/app/src/graphql/query.target-activities.graphql
Fixes #191
I don't know why it's different for Urql, but it fixes the issue...
=> Fix missing user in activities

integration-tests/testkit/flow.ts, integration-tests/tests/api/persisted-operations/publish.spec.ts, integration-tests/tests/api/project/create.spec.ts, integration-tests/tests/api/schema/check.spec.ts, integration-tests/tests/api/schema/publish.spec.ts, integration-tests/tests/api/schema/sync.spec.ts, integration-tests/tests/api/target/tokens.spec.ts, integration-tests/tests/api/target/usage.spec.ts, integration-tests/tests/cli/schema.spec.ts, packages/services/api/src/modules/project/module.graphql.ts, packages/services/api/src/modules/project/resolvers.ts, packages/web/app/src/components/v2/modals/create-project.tsx, packages/web/app/src/graphql/mutation.create-project.graphql
=> Create production, staging and development targets by default for new projects

integration-tests/tests/cli/schema.spec.ts, packages/libraries/cli/src/commands/schema/publish.graphql, packages/libraries/cli/src/commands/schema/publish.ts
linkToWebsite has to be deployed first
=> Disable linkToWebsite in CLI

packages/web/app/src/components/common/GraphQLSDLBlock.tsx
**Before**
**After**
Closes #211
=> fix: make editor full width

packages/web/app/src/components/organization/Permissions.tsx
=> Fix missing scopes when generating a token

packages/web/app/public/robots.txt, packages/web/landing-page/pages/index.tsx
It should be better from SEO perspective.
=> Adjust title and description of the landing page

.changeset/hip-carrots-dream.md, packages/libraries/cli/package.json, packages/services/api/package.json, yarn.lock
=> Update GraphQL Inspector to 3.2.0

packages/services/police-worker/src/index.ts
=> WAF: block only when x-api-token and authorization headers are missing

integration-tests/testkit/flow.ts, integration-tests/tests/api/organization/get-started.spec.ts, integration-tests/tests/api/organization/members.spec.ts, packages/services/api/src/modules/organization/providers/organization-manager.ts, packages/web/app/pages/[orgId]/members.tsx
=> One-time invitation link

docs/DEVELOPMENT.md
The currently required steps for running Hive locally with your own Auth0 app.
A bit nasty, but it's what it takes to get to a working state from a fresh clone!
This stuff is going away soon anyways once migrated to super tokens.
=> docs: add auth0 app docs

.changeset/many-wasps-count.md, .prettierignore, codegen.yml, jest.config.js, packages/libraries/client/src/client.ts, packages/libraries/client/src/internal/agent.ts, packages/libraries/client/src/internal/reporting.ts, packages/libraries/client/tests/reporting.spec.ts
=> Show error messages in the client when publishing the schema

packages/web/app/src/components/layouts/project.tsx, packages/web/app/src/components/layouts/target.tsx, packages/web/app/src/components/v2/header.tsx
=> Switching between projects/targets does not always work

.github/workflows/ci.yaml, integration-tests/docker-compose.yml, integration-tests/testkit/clickhouse.ts, integration-tests/tests/api/target/usage.spec.ts, packages/services/api/src/modules/operations/providers/operations-reader.ts, packages/services/storage/migrations/clickhouse.ts, packages/services/usage-common/src/processed.ts, packages/services/usage-ingestor/__tests__/serializer.spec.ts, packages/services/usage-ingestor/src/ingestor.ts, packages/services/usage-ingestor/src/processor.ts, packages/services/usage-ingestor/src/serializer.ts, packages/services/usage-ingestor/src/writer.ts
=> Implement new ClickHouse DB structure

Cargo.lock, packages/libraries/router/CHANGELOG.md, packages/libraries/router/Cargo.toml, packages/libraries/router/src/agent.rs, packages/libraries/router/src/graphql.rs, packages/libraries/router/src/usage.rs, packages/web/docs/pages/features/monitoring.mdx
Until https://github.com/graphql-rust/graphql-parser/pull/67 is merged in some form
=> Fix Rust build

.changeset/shiny-rats-rule.md, packages/libraries/client/src/internal/usage.ts
=> Avoid marking the same type as used twice

.vscode/terminals.json, packages/services/api/src/modules/operations/providers/operations-reader.ts, packages/web/app/pages/[orgId]/members.tsx
=> Add "Copy Invite Link" button to invitations

packages/services/api/src/modules/schema/providers/schema-publisher.ts, packages/services/api/src/modules/schema/resolvers.ts, packages/services/server/src/graphql-handler.ts
=> No longer detect the SchemaPublishMissingServiceError

deployment/services/app.ts, packages/services/emails/src/index.ts, packages/services/rate-limit/src/index.ts, packages/services/schema/src/index.ts, packages/services/server/src/graphql-handler.ts, packages/services/server/src/index.ts, packages/services/stripe-billing/src/index.ts, packages/services/tokens/src/index.ts, packages/services/usage-estimator/src/index.ts, packages/services/usage-ingestor/src/index.ts, packages/services/usage/src/index.ts, packages/services/webhooks/src/index.ts, packages/web/app/sentry.config.ts
=> Sentry on staging

packages/libraries/router/CHANGELOG.md, packages/libraries/router/src/graphql.rs
=> Don't panic on scalars used as variable types

.github/workflows/cd.yaml, .github/workflows/ci.yaml
=> ci: use node-version-file

deployment/services/supertokens.ts, integration-tests/docker-compose.yml, packages/services/storage/docker-compose.yml
This version logs `INFO` and higher by default
=> Use SuperTokens v3.16 and make it dependent on PG

packages/web/app/pages/[orgId]/[projectId]/[targetId]/settings.tsx, packages/web/app/src/components/schema-editor.tsx
Fixes an issue with missing Suspense.fallback
=> Use dynamic instead of React.lazy

.changeset/cool-pugs-nail.md, packages/libraries/client/src/apollo.ts, packages/libraries/client/src/internal/types.ts, packages/libraries/client/src/internal/usage.ts, packages/libraries/client/src/internal/utils.ts, packages/libraries/client/tests/usage-collector.spec.ts
initial PR for https://github.com/kamilkisiela/graphql-hive/issues/369
=> collect input fields from variables

deployment/services/graphql.ts, integration-tests/docker-compose.yml, packages/services/api/src/create.ts, packages/services/api/src/modules/cdn/module.graphql.ts, packages/services/api/src/modules/cdn/providers/cdn.provider.ts, packages/services/api/src/modules/cdn/resolvers.ts, packages/services/server/README.md, packages/services/server/src/environment.ts, packages/services/server/src/index.ts, packages/web/app/src/components/layouts/target.tsx
Closes https://github.com/kamilkisiela/graphql-hive/issues/406
=> feat: optional CDN

packages/services/cdn-worker/src/handler.ts, packages/services/cdn-worker/tests/cdn.spec.ts
=> Content-Type: application/json in /schema and /metadata CDN endpoints

docker-compose.community.yml, packages/web/docs/pages/self-hosting/get-started.mdx, packages/web/docs/pages/self-hosting/meta.json
Closes https://github.com/kamilkisiela/graphql-hive/issues/312
=> docs: self hosting

deployment/services/supertokens.ts, integration-tests/docker-compose.yml, packages/services/storage/docker-compose.yml
closes https://github.com/kamilkisiela/graphql-hive/issues/418
=> feat: upgrade to supertokens core 4.1

packages/web/app/src/components/target/operations/Filters.tsx
=> Make search term lower case

.github/workflows/ci.yaml
=> Sanitize branch name to comply with Docker tag

integration-tests/docker-compose.yml, packages/services/storage/docker-compose.yml
Based on my experience (local env), integration tests run smoothly, 10 out of 10.
=> Update ClickHouse and Kafka images to latest

packages/web/app/src/components/target/operations/Stats.tsx, packages/web/app/src/graphql/query.duration-histogram.graphql
Let's bring it back when it's time
=> Remove duration histogram

deployment/index.ts, deployment/services/cloudflare-security.ts
=> Manage security headers through CloudFlare Transform Rule (for SaaS)

docker-compose.community.yml, packages/web/docs/pages/self-hosting/client-and-cli-configuration.mdx
Closes https://github.com/kamilkisiela/graphql-hive/issues/540
=> docs: self-hosted client and cli adjustments

integration-tests/package.json, packages/services/api/package.json, packages/services/cdn-worker/package.json, packages/services/emails/package.json, packages/services/rate-limit/package.json, packages/services/schema/package.json, packages/services/server/package.json, packages/services/stripe-billing/package.json, packages/services/tokens/package.json, packages/services/usage-estimator/package.json, packages/services/usage-ingestor/package.json, packages/services/usage/package.json, packages/services/webhooks/package.json, packages/web/app/package.json, pnpm-lock.yaml
Idea is to fix the lookup warnings in #476.
=> Use workspace:* for workspace packages

deployment/package.json
Fixes the failing job at https://github.com/kamilkisiela/graphql-hive/actions/runs/3366046992/jobs/5582138657.
=> @hive/deployment is a private package

packages/web/app/src/config/supertokens/frontend.ts
Prevents redirecting to other domains
=> Allow only local pages in redirectToPath

packages/services/emails/package.json, packages/services/schema/package.json, packages/services/server/package.json, packages/services/stripe-billing/package.json, packages/services/tokens/package.json, packages/services/usage-estimator/package.json, packages/services/usage/package.json, packages/services/webhooks/package.json
```diff
Error: OMG
-   at createServer (packages/services/tokens/dist/src-QJM4PQWU.js:204:9)
+   at createServer (/packages/services/service-common/src/fastify.ts:9:9)
```
=> Use source maps in dev

deployment/services/app.ts
Reverts kamilkisiela/graphql-hive#601
=> Revert "enable feature in deployment"

packages/web/app/pages/[orgId]/[projectId]/[targetId]/explorer.tsx, packages/web/app/pages/[orgId]/[projectId]/[targetId]/explorer/[typename].tsx, packages/web/app/pages/[orgId]/[projectId]/[targetId]/history.tsx, packages/web/app/pages/[orgId]/[projectId]/[targetId]/history/[versionId].tsx, packages/web/app/pages/[orgId]/[projectId]/[targetId]/index.tsx, packages/web/app/pages/[orgId]/[projectId]/[targetId]/laboratory.tsx, packages/web/app/pages/[orgId]/[projectId]/[targetId]/operations.tsx, packages/web/app/pages/[orgId]/[projectId]/[targetId]/settings.tsx, packages/web/app/pages/[orgId]/[projectId]/alerts.tsx, packages/web/app/pages/[orgId]/[projectId]/index.tsx, packages/web/app/pages/[orgId]/[projectId]/settings.tsx, packages/web/app/pages/[orgId]/index.tsx, packages/web/app/pages/[orgId]/members.tsx, packages/web/app/pages/[orgId]/settings.tsx, packages/web/app/pages/[orgId]/subscription/index.tsx, packages/web/app/pages/[orgId]/subscription/manage.tsx, packages/web/app/pages/index.tsx, packages/web/app/pages/join/[inviteCode].tsx, packages/web/app/pages/manage/index.tsx, packages/web/app/pages/settings.tsx, packages/web/app/src/components/authenticated-container.tsx, packages/web/app/src/lib/api/extract-access-token-from-request.ts, packages/web/app/src/lib/supertokens/guard.ts, packages/web/app/src/lib/supertokens/third-party-email-password-node-okta-provider.ts
We were bundling part of supertokens-node code to browser and it resulted in errors on Safari.
=> Split server-only and client-only code in authenticated-container.tsx

deployment/services/supertokens.ts, docker-compose.community.yml, integration-tests/docker-compose.app.yml, integration-tests/docker-compose.yml, packages/services/storage/docker-compose.yml
Closes https://github.com/kamilkisiela/graphql-hive/issues/615
=> update supertokens to 4.2

.changeset/clean-jeans-grab.md, .github/workflows/cd.yaml, package.json, packages/libraries/cli/README.md, packages/libraries/cli/package.json, patches/oclif@3.2.25.patch, pnpm-lock.yaml
=> npm-shrinkwrap, this time for real

packages/services/api/src/shared/sentry.ts, packages/services/server/src/index.ts
=> Do not capture GraphQLError exceptions

deployment/services/graphql.ts, deployment/services/schema.ts, deployment/services/usage-ingestor.ts, deployment/services/usage.ts, deployment/utils/cert-manager.ts, deployment/utils/redis.ts, deployment/utils/remote-artifact-as-service.ts, deployment/utils/reverse-proxy.ts, tsconfig.eslint.json
Closes https://github.com/the-guild-org/graphql-hive-deployment/issues/1344
=> Added missing PodDisruptionBudget, upgrade cert-manager to latest

.changeset/young-garlics-fail.md, packages/libraries/cli/src/base-command.ts, packages/libraries/client/src/apollo.ts, packages/libraries/client/src/client.ts, packages/libraries/client/src/envelop.ts, packages/libraries/client/src/gateways.ts, packages/libraries/client/src/internal/agent.ts, packages/libraries/client/tests/apollo.spec.ts, packages/libraries/router/src/agent.rs, packages/libraries/router/src/registry.rs
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/User-Agent
=> feat: add user-agent header to fetcher functions

packages/services/api/src/modules/alerts/providers/alerts-manager.ts
It should help us to detect duplicates (if any).
=> Log version id when sending schema change notification

docker-compose.community.yml
Makes sure the other services can actually connect via hostname
=> fix: broker network typo

packages/services/api/src/modules/admin/providers/admin-manager.ts
https://sentry.io/organizations/the-guild-z4/issues/3759874197/?project=5691450&query=is%3Aunresolved&referrer=issue-stream
=> feat: do not treat gtfo error as unexpected error

packages/services/api/src/modules/schema/resolvers.ts, packages/services/api/src/shared/schema.ts, packages/web/app/pages/[orgId]/[projectId]/[targetId]/history.tsx
=> Explain why comparison of versions failed

.changeset/five-kangaroos-divide.md, packages/libraries/client/src/internal/types.ts, packages/libraries/client/tests/enabled.spec.ts
=> Make the token optional when client is disabled

.github/workflows/website.yaml, packages/web/landing-page/.gitignore, packages/web/landing-page/next-sitemap.config.cjs, packages/web/landing-page/next.config.js, packages/web/landing-page/package.json, pnpm-lock.yaml
=> Move landing page to be under the unified domain the-guild.dev

.github/workflows/ci.yaml, docker.hcl, integration-tests/docker-compose.yml, integration-tests/tests/api/schema/composition-federation-2.spec.ts, package.json, packages/services/external-composition/federation-2/README.md, packages/services/external-composition/federation-2/package.json, packages/services/external-composition/federation-2/src/environment.ts, packages/services/external-composition/federation-2/src/index.ts, packages/services/external-composition/federation-2/tsconfig.json, pnpm-lock.yaml, pnpm-workspace.yaml
Adds a federation  2 composition service docker container for people that want to do a federation 2 project.
=> feat: federation 2 service container

packages/web/docs/package.json, packages/web/landing-page/package.json, packages/web/landing-page/src/pages/index.tsx, pnpm-lock.yaml
=> Fixes for landing page with next export and base path

.github/workflows/cd.yaml, .github/workflows/ci.yaml, .github/workflows/codeql-analysis.yml, codegen.yml, docker-compose.community.yml, integration-tests/docker-compose.app.yml, integration-tests/docker-compose.yml, packages/services/storage/docker-compose.yml
Reverts kamilkisiela/graphql-hive#738
It breaks docker compose files:
```
services.s3_provision_buckets.restart must be a string
```
@B2o5T
=> Revert "[🔧 ESLint] fixes for yaml with `yml/plain-scalar` rule"

deployment/index.ts, deployment/services/cloudflare-security.ts
Closes https://github.com/the-guild-org/graphql-hive-deployment/issues/1349
=> Ignore CSP and security headers for CDN endpoints

packages/services/external-composition/federation-2/src/index.ts
This is a small QoL improvement. It makes my IDE happy 😃
=> Assert that supergraphSdl is present in order to narrow type

packages/web/app/package.json, pnpm-lock.yaml
Reverts kamilkisiela/graphql-hive#793
=> Revert "Update dependency @urql/exchange-graphcache to v4.4.3"

packages/web/app/src/lib/supertokens/third-party-email-password-react-oidc-provider.ts
Closes https://github.com/kamilkisiela/graphql-hive/issues/806
=> fix: use delimiter that needs no encoding

integration-tests/tests/api/oidc-integrations/crud.spec.ts, packages/services/api/src/modules/oidc-integrations/module.graphql.ts, packages/services/api/src/modules/oidc-integrations/providers/oidc-integrations.provider.ts, packages/services/api/src/modules/oidc-integrations/resolvers.ts, packages/services/api/src/modules/shared/providers/storage.ts, packages/services/api/src/shared/entities.ts, packages/services/server/src/api.ts, packages/services/storage/migrations/actions/2022.12.20T09.20.36.oidc-columns.sql, packages/services/storage/migrations/actions/down/2022.12.20T09.20.36.oidc-columns.sql, packages/services/storage/src/index.ts, packages/web/app/src/components/organization/settings/oidc-integration-section.tsx, packages/web/app/src/lib/supertokens/third-party-email-password-node-oidc-provider.ts
Allows setting custom `tokenEndpoint`, `authorizationEndpoint` and `userinfoEndpoint` with backwards compatibility.
=> feat: more granular configuration of OIDC endpoints

.changeset/dirty-tools-yell.md, packages/libraries/client/src/gateways.ts, packages/libraries/client/tests/gateways.spec.ts, packages/services/cdn-worker/src/artifact-handler.ts
See https://github.com/kamilkisiela/graphql-hive/issues/777
Closes https://github.com/kamilkisiela/graphql-hive/issues/777
=> feat: use new services endpoint in SDK and add redirect for legacy endpoint

package.json, pnpm-lock.yaml, scripts/turborepo-cleanup.js
more lines added due recent pnpm https://github.com/kamilkisiela/graphql-hive/pull/919
=> remove fs-extra

.github/workflows/tests-integration.yaml, deployment/utils/reverse-proxy.ts
No breaking changes, it's just Go lang version upgrades, and Enovy patch version upgrade :)
=> Upgrade Contour to latest version

packages/services/api/src/modules/schema/providers/schema-publisher.ts
closes https://github.com/kamilkisiela/graphql-hive/issues/750
=> feat: include service name within the schema check

integration-tests/package.json, integration-tests/tests/api/artifacts-cdn.spec.ts, packages/libraries/client/README.md, packages/web/app/pages/api/auth/[[...path]].ts, packages/web/docs/src/pages/features/registry-usage.mdx, pnpm-lock.yaml
Related:
- https://github.com/kamilkisiela/graphql-hive/issues/905
=> feat: integration test apollo gateway + server compatibility

packages/web/docs/src/pages/features/sso-oidc-provider.mdx
Fixes a typo and adds spacing between images.
=> docs: fix typo and add spacing between images

packages/web/docs/src/pages/features/registry-usage.mdx
=> Fix type in Using Registry Doc Page

packages/web/app/package.json, pnpm-lock.yaml
Closes https://github.com/kamilkisiela/graphql-hive/issues/1075
Caused by https://github.com/kamilkisiela/graphql-hive/pull/1057
=> hotfix(app): added missing `tslib` to `app` dependencies

deployment/services/clickhouse.ts, deployment/services/usage-ingestor.ts, packages/services/usage-ingestor/README.md, packages/services/usage-ingestor/src/environment.ts, packages/services/usage-ingestor/src/index.ts, packages/services/usage-ingestor/src/ingestor.ts, packages/services/usage-ingestor/src/writer.ts
> Upholding Hive’s culture of openness and transparency, I come to you today with some difficult news. In an effort to adjust our GTM strategy and align our teams with future objectives, we have unfortunately had to make the challenging decision to decrease the size of our ClickHouse instances. This decision will impact 100% of the Altinity Cloud, and those affected have not been notified via personal and work email.
With gratitude
Kamil
=> Drop Altinity Cloud and switch to ClickHouse Cloud

packages/migrations/src/clickhouse.ts
Warm up ClickHouse instance.
This is needed because ClickHouse takes a while to start up when pausing after a period of inactivity is enabled (which is true for dev and staging)
=> Warm up ClickHouse instance before executin migrations

packages/web/app/pages/[orgId]/index.tsx, packages/web/app/src/components/layouts/organization.tsx, packages/web/app/src/components/layouts/project.tsx
=> Use /view prefix for links

docker-compose.community.yml
=> No more roarr from Slonik

deployment/utils/cloudflare.ts, packages/services/cdn-worker/package.json, packages/services/cdn-worker/src/analytics.ts, packages/services/cdn-worker/src/dev-polyfill.ts, packages/services/cdn-worker/src/index.ts, packages/services/cdn-worker/src/key-validation.ts, pnpm-lock.yaml
=> add and track new analytics method

packages/services/tokens/src/cache.ts
fixes https://github.com/kamilkisiela/graphql-hive/issues/1166
=> Avoid calling redis.del with empty array

docker/docker-compose.community.yml, packages/web/docs/src/pages/self-hosting/oidc-login.mdx
https://github.com/kamilkisiela/graphql-hive/issues/1160
This should make things more clear, for the meantime, before we do a bigger documentation overhaul.
=> docs: clarify difference between oidc login and origanization oidc login

packages/web/app/pages/_document.tsx
I hope it fixes SENTRY-3739590397
=> Add type attribute to <link /> (favicon)

integration-tests/tests/api/schema/publish.spec.ts, packages/services/api/src/modules/token/providers/token-storage.ts
=> Fix reporting of Invalid Token error to Sentry

packages/web/app/src/components/v2/activities.tsx
Seems like recent update of Urql broke some things
=> Fix runtime error in Activities

renovate.json
based on https://github.com/the-guild-org/shared-config/commit/a462fab616a020f17c6454f01f9c99af3dd10b0b
=> Renovate fixes and adjustments

.github/workflows/release-stable.yaml
Fix https://github.com/kamilkisiela/graphql-hive/actions/runs/4112317351/jobs/7097083911
=> Remove old always-auth flag

docker/docker-compose.dev.yml, packages/migrations/src/actions/2023.01.18T11.03.41.registry-v2.sql, packages/services/storage/src/db/types.ts
To speed up the migration and move on :)
=> Alter instead of creating a new table

packages/services/server/src/graphql-handler.ts, packages/services/server/src/index.ts
Fastify doesn't work well with custom stream. We will already drop Fastify and we don't use incremental delivery so it is fine to use `response.text` for now.
=> Use `response.text` instead of `response.body`

packages/services/schema/src/orchestrators.ts
Using typeDefs is designed for extensions
=> Use subschemas instead of typeDefs

packages/services/tokens/src/api.ts
=> Assert 32-chars long tokens before fetching

packages/services/schema/__tests__/cache.spec.ts, packages/services/schema/src/cache.ts, packages/services/schema/src/index.ts
Cache the result (success and failure) for some time and delete a few stupid things I wrote there
=> Simplify the caching part of the schema service

turbo.json
Closes https://github.com/kamilkisiela/graphql-hive/issues/1210
=> Fix local build issues

packages/web/app/src/components/common/DataWrapper.tsx, packages/web/app/src/components/target/operations/Filters.tsx
fixes https://github.com/kamilkisiela/graphql-hive/issues/1474
=> fix unclickable checkbox in operations view

deployment/services/supertokens.ts
=> bump supertokens

.github/workflows/main.yaml, .github/workflows/pr.yaml, .github/workflows/storybook.yaml, packages/web/app/.gitignore, packages/web/app/.storybook/main.js, packages/web/app/.storybook/preview.js, packages/web/app/package.json, packages/web/app/src/components/v2/callout.tsx, packages/web/app/src/stories/callout.stories.tsx, pnpm-lock.yaml
I believe it will help us improve the look of the components (at least me).
=> Welcome StoryBook

docs/DEVELOPMENT.md, packages/web/app/src/lib/docs-url.ts
closes https://github.com/kamilkisiela/graphql-hive/issues/1507 , also a tiny fix for local dev docs
=> fix for docs url handling

packages/web/app/pages/[orgId]/[projectId]/index.tsx, packages/web/app/pages/[orgId]/index.tsx, packages/web/app/pages/[orgId]/view/members.tsx, packages/web/app/public/styles.css, packages/web/app/src/components/layouts/organization.tsx, packages/web/app/src/components/layouts/project.tsx, packages/web/app/src/components/layouts/target.tsx, packages/web/app/src/components/v2/button.tsx, packages/web/app/src/components/v2/header.tsx
1. hide settings when don't have access to this page 
2. reduce animation
3. truncate
=> fixes for hive app

packages/services/api/src/modules/shared/providers/storage.ts, packages/services/server/src/index.ts, packages/services/storage/src/index.ts
This should restart the pod if it's unhealthy
=> Make PG connection check as part of readiness check

packages/web/app/pages/[orgId]/[projectId]/[targetId]/history.tsx, packages/web/app/public/styles.css
=> fix bug in history page

packages/web/app/src/components/v2/accordion.tsx, packages/web/app/src/components/v2/modals/create-access-token.tsx, packages/web/app/src/components/v2/radix-select.tsx
Closes https://github.com/kamilkisiela/graphql-hive/issues/959
=> Token creation preset

integration-tests/tests/api/artifacts-cdn.spec.ts, packages/services/api/src/modules/schema/providers/registry-checks.ts
Closes https://github.com/kamilkisiela/graphql-hive/issues/330#issuecomment-1439874399
=> Validate service URL in schema checks

configs/cargo/Cargo.lock, packages/libraries/router/Cargo.toml
=> Bump Apollo Router to v1.11.0

deployment/utils/botkube.ts, deployment/utils/observability.ts, deployment/utils/reverse-proxy.ts
=> Fix how Renovate identify dependencies inside code files

deployment/grafana-dashboards/Azure-Eventhub-Overview.json, deployment/grafana-dashboards/CDN-Usage.json, deployment/grafana-dashboards/ClickHouse-Latency.json, deployment/grafana-dashboards/Container-Logs.json, deployment/grafana-dashboards/Emails-Service.json, deployment/grafana-dashboards/Envoy-HTTP.json, deployment/grafana-dashboards/Hive-Schema-Registry.json, deployment/grafana-dashboards/Hive-Tokens.json, deployment/grafana-dashboards/Hive-Vitals.json, deployment/grafana-dashboards/NodeJS-Overview.json, deployment/grafana-dashboards/README.md, deployment/package.json, deployment/services/grafana.ts, deployment/services/observability.ts, pnpm-lock.yaml
=> Move Grafana dashboards to live in the repository as JSON files

deployment/services/bot-kube.ts, deployment/utils/botkube.ts
Requires https://github.com/the-guild-org/graphql-hive-deployment/pull/1375 
Also, enabled it for staging :)
=> update botkube to latest and fix configs

packages/web/app/pages/manage/index.tsx, packages/web/app/src/components/admin/AdminStats.tsx, packages/web/app/src/components/target/operations/List.tsx, packages/web/app/src/components/v2/index.ts, packages/web/app/src/components/v2/sortable.tsx, packages/web/app/src/components/v2/tooltip.tsx
fixes https://github.com/kamilkisiela/graphql-hive/issues/1597
=> bring back sorting for tables in operations view

deployment/package.json, deployment/services/cf-broker.ts, deployment/services/cf-cdn.ts, deployment/services/graphql.ts, deployment/services/police.ts, deployment/utils/cloudflare.ts, deployment/utils/police.ts, pnpm-lock.yaml
Reverts kamilkisiela/graphql-hive#1719
=> Revert "fix cf config flags"

docs/TESTING.md, integration-tests/local.sh, package.json
This simplify running integration tests locally, from the source code, to this:
```
pnpm integration:prepare
pnpm test:integration
```
=> Added a new script for preparing env for integration tests

packages/web/docs/src/pages/self-hosting/oidc-login.mdx
=> fix broken url in docs 

packages/web/app/pages/[orgId]/[projectId]/[targetId]/history.tsx
=> Fix the display of an error message on the history page

package.json, patches/workers-loki-logger@0.1.14.patch, pnpm-lock.yaml
The library we use defines the timestamp when the Logger is created and never changes it.
=> Fix timestamps in Workers Logger

integration-tests/package.json, integration-tests/testkit/cli.ts, integration-tests/testkit/flow.ts, integration-tests/testkit/seed.ts, integration-tests/tests/cli/schema.spec.ts, integration-tests/tests/models/stitching.spec.ts, package.json, packages/services/api/src/modules/schema/module.graphql.ts, packages/services/api/src/modules/schema/resolvers.ts, packages/services/api/src/shared/mappers.ts, patches/workers-loki-logger@0.1.14.patch, pnpm-lock.yaml
The History page receives no changes and no composition errors when comparing versions and it displays "it's your first composable versions" message. It shouldn't do that when a service url changes.
=> Display service url changes in UI when comparing versions

packages/services/server/src/graphql-handler.ts, packages/web/app/pages/api/proxy.ts
Reverts kamilkisiela/graphql-hive#1958
=> Revert "Do not consume responses but forward"

deployment/utils/observability.ts
Reverts kamilkisiela/graphql-hive#1996
There's an issue with logs.
=> Revert "chore(deps): update helm release vector to v0.21.0"

.github/workflows/website.yaml
@kamilkisiela as Algolia is not in use here, you can remove all ALGOLIA-related secrets
=> Algolia cleanup

docker/router.dockerfile
Less cache busting, shared cargo registry.
=> Improve Apollo Router docker file

.github/workflows/main-rust.yaml, .github/workflows/pr-rust.yaml
=> Skip Rust related CI when Rust is not touched

packages/web/docs/src/components/pricing.tsx
=> Use Custom instead of Unlimited in Enterprise plan

packages/web/docs/src/pages/docs/self-hosting/client-and-cli-configuration.mdx
An example code block is missing a comma
Just documentation update, no impact.
=> Add missing comma

packages/services/api/src/modules/schema/module.graphql.ts, packages/services/api/src/modules/schema/resolvers.ts, packages/web/app/pages/[orgId]/[projectId]/[targetId]/history.tsx, packages/web/app/src/graphql/query.compare.graphql
I kind of need this in prod in order to better debug whats wrong rn.
=> feat: allow comparison with legacy method via query parameter

docker/app.dockerfile, docker/migrations.dockerfile, docker/services.dockerfile, integration-tests/docker-compose.integration.yaml
Reverts kamilkisiela/graphql-hive#2107
=> Revert to Node18 

packages/services/api/package.json, packages/web/app/package.json, pnpm-lock.yaml
Reverts kamilkisiela/graphql-hive#2105
=> Revert "fix(deps): update dependency supertokens-node to v13.5.0"

packages/services/api/package.json, packages/services/api/src/modules/schema/resolvers.ts, pnpm-lock.yaml
closes https://github.com/kamilkisiela/graphql-hive/issues/2157
=> use stable stringify

packages/web/docs/src/pages/docs/get-started/apollo-federation.mdx, packages/web/docs/src/pages/docs/get-started/schema-stitching.mdx, packages/web/docs/src/pages/docs/get-started/single-project.mdx
Signed-off-by: TuvalSimha <tuval.simha@gmail.com>
=> Fix `--token` flag in docs

packages/migrations/src/actions/2023.05.08T12.23.45.clean-invalid-schema-version-changes.sql, packages/migrations/src/actions/down/2023.05.08T12.23.45.clean-invalid-schema-version-changes.sql
=> fix: clean database of broken records

packages/web/docs/src/pages/docs/integrations/envelop.mdx, packages/web/docs/src/pages/docs/integrations/graphql-yoga.mdx
Signed-off-by: TuvalSimha <tuval.simha@gmail.com>
=> Add import to `useHive` docs

packages/web/app/src/components/v2/modals/connect-schema.tsx, pnpm-lock.yaml
We only need to make the network call if the modal is opened. 
| Before | After |
| -------|------|
|![CleanShot 2023-05-10 at 11 09 53](https://github.com/kamilkisiela/graphql-hive/assets/44710980/aa9c8434-789b-4ce4-8f45-8418c6e444d9)| ![CleanShot 2023-05-10 at 11 09 27](https://github.com/kamilkisiela/graphql-hive/assets/44710980/8903ee34-7f0d-470b-a1e2-68997311b0b2) |
=> fix: only query the modal data when it is open

deployment/services/db-migrations.ts, packages/migrations/src/clickhouse-actions/001-initial.ts, packages/migrations/src/clickhouse-actions/002-add-hash-to-clients_daily.ts, packages/migrations/src/clickhouse.ts
Adds a `hash` column to the `ORDER BY` of `clients_daily`. Fixes an issue with partial data in client exclusion logic.
=> Add hash to sort key of clients_daily view

packages/services/api/src/modules/schema/module.graphql.ts
=> fix: use float instead of integer to work around max integer issue

codegen.cjs, packages/services/api/src/modules/operations/providers/clickhouse-client.ts, packages/services/api/src/modules/operations/providers/operations-manager.ts, packages/services/api/src/modules/operations/providers/operations-reader.ts, packages/services/api/src/modules/schema/module.graphql.ts, packages/services/api/src/modules/schema/resolvers.ts, packages/services/api/src/shared/helpers.ts, packages/services/api/src/shared/mappers.ts, packages/web/app/src/components/target/explorer/common.tsx, packages/web/app/src/components/v2/icon.tsx
Closes https://github.com/kamilkisiela/graphql-hive/issues/2050
Closes https://github.com/kamilkisiela/graphql-hive/issues/2050
=> feat: show clients that use a specific schema coordinate on the explorer view

packages/web/app/src/components/organization/Permissions.tsx, packages/web/app/src/components/v2/accordion.tsx, packages/web/app/src/components/v2/modal.tsx, packages/web/app/src/components/v2/modals/create-access-token.tsx, packages/web/app/src/components/v2/radix-select.tsx, packages/web/app/src/components/v2/tabs.tsx, packages/web/app/src/components/v2/tooltip.tsx
Some users complained about creating an access token failing. As a follow-up task we discussed improving the UI to show the exact permissions required and also show information why one cannot select a certain permission.
**Before**
**After**
=> feat: create access token form UX improvements

packages/services/api/src/modules/billing/module.graphql.ts, packages/services/api/src/modules/billing/providers/billing.provider.ts, packages/services/api/src/modules/billing/resolvers.ts, packages/services/api/src/modules/organization/providers/organization-manager.ts, packages/services/stripe-billing/src/api.ts, packages/web/app/pages/[orgId]/view/subscription/index.tsx, packages/web/app/pages/[orgId]/view/subscription/manage.tsx, packages/web/app/src/components/layouts/organization.tsx, packages/web/app/src/components/organization/billing/BillingPaymentMethod.tsx, packages/web/app/src/components/organization/billing/InvoicesList.tsx, packages/web/app/src/components/organization/billing/ProPlanBillingWarm.tsx, packages/web/app/src/graphql/fragments.graphql
This PR adds the following:
- Callout in case of a billing issue (for the Pro plan) when an invoice is rejected. 
- A direct link to Stripe billing dashboard (to manage payment method, Tax ID, billing email and so on) 
Closes https://github.com/the-guild-org/graphql-hive-deployment/issues/1376
=> Added a callout for Pro customers with billing issues, and added a link to Stripe Billing dashboard

.github/workflows/codeanalysis.yaml, sonar-project.properties
=> chore: analyse code with sonar

.changeset/spotty-llamas-buy.md, packages/libraries/cli/package.json, packages/libraries/cli/src/helpers/git.ts, pnpm-lock.yaml
=> Use lighter solution to get commit sha and author from git

packages/web/app/pages/[orgId]/[projectId]/[targetId]/laboratory.tsx
=> prevent page jump when selecting an collection item

packages/services/api/src/modules/integrations/providers/github-integration-manager.ts, packages/services/api/src/modules/schema/providers/config.ts, packages/services/api/src/modules/schema/providers/models/composite.ts, packages/services/api/src/modules/schema/providers/registry-checks.ts, packages/services/api/src/modules/schema/providers/schema-publisher.ts, packages/services/server/src/graphql-handler.ts, packages/services/server/src/index.ts, packages/web/app/pages/[orgId]/[projectId]/[targetId]/checks.tsx, packages/web/app/pages/[orgId]/[projectId]/[targetId]/checks/[schemaCheckId].ts, packages/web/app/src/components/layouts/target.tsx, packages/web/app/src/components/target/history/errors-and-changes.tsx, packages/web/app/src/lib/hooks/use-route-selector.ts
Follow up for https://github.com/kamilkisiela/graphql-hive/pull/2417
Closes https://github.com/kamilkisiela/graphql-hive/issues/333
=> feat: schema check ui

packages/services/api/src/modules/operations/providers/operations-reader.ts, packages/services/api/src/modules/operations/resolvers.ts
=> chore: improve types

packages/services/api/src/modules/operations/providers/operations-manager.ts, packages/services/api/src/modules/operations/providers/operations-reader.ts
=> Check existence of operations in more efficient way

packages/migrations/src/clickhouse-actions/003-add-client-name-to-operations-tables.ts, packages/migrations/src/clickhouse.ts, packages/migrations/src/scripts/003-cloud.ts
=> feat: add client names to operation tables

packages/services/storage/src/schema-change-model.ts, packages/web/app/src/components/target/history/errors-and-changes.tsx
=> fix: display safe changes (based on usage) in the schema check view

packages/services/api/src/modules/token/providers/token-storage.ts
=> Do not log HiveError in TokenStorage

packages/migrations/src/scripts/003-cloud.ts
=> fix: adjust script

packages/services/api/src/modules/operations/module.graphql.ts, packages/services/api/src/modules/operations/providers/operations-manager.ts, packages/services/api/src/modules/operations/providers/operations-reader.ts, packages/services/api/src/modules/operations/resolvers.ts, packages/services/api/src/shared/mappers.ts, packages/web/app/pages/[orgId]/[projectId]/[targetId]/operations.tsx, packages/web/app/src/components/target/operations/Filters.tsx, packages/web/app/src/components/target/operations/List.tsx, packages/web/app/src/components/target/operations/Stats.tsx, packages/web/app/src/graphql/query.operations-stats.graphql, scripts/seed-local-env.ts
Closes https://github.com/kamilkisiela/graphql-hive/issues/2441
Follow up for https://github.com/kamilkisiela/graphql-hive/pull/2512
=> filter operations by client name

packages/web/app/src/components/target/operations/Filters.tsx
=> Truncate options in the operations/clients filter

packages/web/app/src/components/ui/select.tsx
Closes https://github.com/kamilkisiela/graphql-hive/issues/2537
=> fix: add pointer cursor for select component

.changeset/polite-parents-mate.md, integration-tests/tests/api/policy/policy-check.spec.ts, packages/libraries/cli/src/commands/schema/check.graphql, packages/libraries/cli/src/commands/schema/check.ts, packages/services/api/src/modules/schema/module.graphql.ts, packages/services/api/src/modules/schema/providers/schema-manager.ts, packages/services/api/src/modules/schema/resolvers.ts, packages/services/api/src/modules/shared/providers/storage.ts, packages/services/storage/src/index.ts, packages/services/storage/src/schema-change-model.ts
=> feat: expose link to schema check in graphql schema

deployment/utils/observability.ts
=> Update Vector from 0.20.1 to 0.22.1

packages/services/schema/src/cache.ts
If there's something strange
In your neighborhood
Who you gonna call?
=> Link action to ghost error to help ghostbusters do their job

packages/web/app/src/components/target/explorer/super-graph-metadata.tsx
=> fix: overflow issue in explorer ui

.changeset/lazy-countries-brush.md, packages/libraries/client/src/internal/usage.ts
=> refactor: use getNamedTpe helper from graphql-js

packages/web/docs/src/pages/docs/features/schema-registry.mdx
We're missing a "link" between these two.
=> Mention Conditional Breaking Changes in features/schema-registry

package.json, patches/@theguild__components@4.6.5.patch, patches/nextra-theme-docs@2.7.0.patch, pnpm-lock.yaml
We don't have a search feature in documentation but we do show the global one of The Guild.
This PR disables the global search and enables local search for documentation (works also for the landing page).
=> docs: enable local search (disable The Guild search)

docs/DEVELOPMENT.md
=> docs: improve proxy instructions

docker/app.dockerfile, docker/cli.dockerfile, docker/migrations.dockerfile
=> Add ca certificates to base docker images (#2555)

packages/web/app/src/components/ui/dropdown-menu.tsx, packages/web/app/src/components/ui/user-menu.tsx
=> use cursor pointer

packages/web/docs/src/pages/docs/api-reference/cli.mdx
Closes https://github.com/kamilkisiela/graphql-hive/issues/2539
=> you can also provide commit and author when using the check command

integration-tests/testkit/auth.ts, packages/services/server/src/graphql-handler.ts
=> pin supertokens cdi version

docker/cli.dockerfile
=> bump cli node.js container version

deployment/services/database-cleanup.ts, deployment/utils/service-deployment.ts
The other image no longer work as it has no ARM.
We also had to use custom SQL as Azure does not allow dropping schemas.
=> use postgres image for database cleanup job

.github/workflows/build-and-dockerize.yaml, docker/cli.dockerfile, docker/services.dockerfile, packages/libraries/cli/.dockerignore
Use `scope=$GITHUB_REF-${target}` to avoid overwriting cache of each docker container.
=> Fix caching of docker bake

.github/workflows/tests-integration.yaml
=> No need to cache nextjs in integration tests

deployment/services/supertokens.ts, docker/docker-compose.community.yml, docker/docker-compose.dev.yml
=> upgrade supertokens to 5.0

deployment/services/supertokens.ts, docker/docker-compose.community.yml, docker/docker-compose.dev.yml
This requires some manual steps for deployment. See the [`supertokens-core` changelog for 6.0.0](https://github.com/supertokens/supertokens-core/blob/master/CHANGELOG.md#600---2023-06-02) that imply **downtime**.
We need to scale the super tokens service replica count to 0. 
E.g. if you are using kubernetes `kubectl scale deploy --replicas=0 supertokens-XXXXXX`
<details>
<summary>
Execute some SQL
</summary>
```sql
-- General Tables
CREATE TABLE IF NOT EXISTS supertokens_apps  (
app_id VARCHAR(64) NOT NULL DEFAULT 'public',
created_at_time BIGINT,
CONSTRAINT supertokens_apps_pkey PRIMARY KEY(app_id)
);
INSERT INTO supertokens_apps (app_id, created_at_time) 
VALUES ('public', 0) ON CONFLICT DO NOTHING;
------------------------------------------------------------
CREATE TABLE IF NOT EXISTS …
```
=> upgrade supertokens core to v6

integration-tests/testkit/auth.ts, packages/services/server/src/graphql-handler.ts
=> use supertoken cdi version 3.0

renovate.json
Too many open PRs with almost zero benefit.
=> Set renovate.prConcurrentLimit to 10

packages/web/app/pages/_document.tsx
=> load environment during get initial props

packages/web/app/src/components/organization/Permissions.tsx
=> Update access scopes after selecting a different member

package.json, pnpm-lock.yaml
=> bump lockfile version and pnpm version

packages/services/api/src/modules/operations/providers/operations-reader.ts
=> Improve performance of reading operation body

packages/web/app/pages/auth/[[...path]].tsx, packages/web/app/src/config/supertokens/frontend.ts
=> fix broken supertokens email confirmation UI

packages/web/app/src/components/ui/query-error.tsx
=> Sign-out button in Oops, something went wrong view

packages/services/api/src/modules/schema/resolvers.ts
=> fix: swallow error for SchemaCoordinateUsage.usedByClients field

.changeset/spotty-panthers-accept.md, packages/libraries/cli/README.md, packages/libraries/cli/src/commands/introspect.ts, packages/libraries/cli/src/helpers/schema.ts
```bash
hive introspect https://example.com/graphql
hive introspect https://example.com/graphql --header "Key:Value"
hive introspect https://example.com/graphql --write schema.graphql
hive introspect "./src/**/*.graphql"
```
=> Adds introspect command

packages/services/storage/src/index.ts
=> fix: `base_schema` is optional

packages/services/server/src/api.ts, packages/web/app/pages/auth/[[...path]].tsx, packages/web/app/src/lib/supertokens/can-handle-route-server-side.ts, packages/web/app/src/lib/supertokens/third-party-email-password-node-oidc-provider.ts
=> fix: improve handling of auth routes

packages/services/api/src/modules/operations/providers/operations-reader.ts
It processed 27x less rows than the previous version.
It's 30x faster.
It consumes 36x less memory (~8MB).
It obviously depends on the amount of original data, but I tested it on a multiple datasets and the ratio is always similar.
=> Make get_hashes_for_schema_coordinates more efficient

packages/web/app/pages/[orgId]/[projectId]/[targetId]/checks.tsx, packages/web/app/pages/[orgId]/[projectId]/[targetId]/history.tsx, packages/web/app/pages/[orgId]/[projectId]/[targetId]/laboratory.tsx, packages/web/app/pages/[orgId]/[projectId]/[targetId]/settings.tsx, packages/web/app/pages/[orgId]/[projectId]/view/settings.tsx, packages/web/app/pages/[orgId]/index.tsx, packages/web/app/pages/[orgId]/view/manage-subscription.tsx, packages/web/app/pages/[orgId]/view/settings.tsx, packages/web/app/pages/[orgId]/view/subscription.tsx, packages/web/app/src/components/layouts/organization.tsx, packages/web/app/src/components/layouts/project.tsx, packages/web/app/src/components/layouts/target.tsx, packages/web/app/src/components/target/explorer/common.tsx, packages/web/app/src/components/target/explorer/super-graph-metadata.tsx, packages/web/app/src/components/ui/user-menu.tsx, packages/web/app/src/components/v2/activities.tsx, packages/web/app/src/components/v2/modals/connect-schema.tsx
[GRAPHQL-HIVE-150](https://the-guild-z4.sentry.io/issues/4284684640/)
=> use href string interpolation

packages/web/docs/src/pages/_meta.json
=> add status link to the landing page

.github/workflows/main.yaml
=> Temporarily disable auto-deployment to staging

packages/web/app/pages/[organizationId]/[projectId]/[targetId]/index.tsx, packages/web/app/src/components/target/explorer/super-graph-metadata.tsx, packages/web/app/src/components/v2/graphql-block.tsx
- brings back ability to filter subgraphs
- fixes a link to a subgraph on the explorer view (chip created by the supergraph metadata component)
- scrolls to a requested subgraph
=> Fix a subraph reference (link from explorer view)

packages/web/app/pages/[organizationId]/[projectId]/[targetId]/laboratory.tsx
Closes #2743 
Light mode:
Dark mode:
=> GraphiQL: Fix background color for search dropdown

packages/web/app/pages/[organizationId]/[projectId]/[targetId]/laboratory.tsx
Closes #2742 
https://github.com/kamilkisiela/graphql-hive/assets/37614975/12d36719-065d-49ef-8aa6-0c61f53c858d
=> GraphiQL: Bracket change color

packages/web/app/pages/[organizationId]/[projectId]/[targetId]/checks.tsx, packages/web/app/pages/[organizationId]/[projectId]/[targetId]/history.tsx, packages/web/app/pages/[organizationId]/[projectId]/[targetId]/settings.tsx, packages/web/app/src/components/target/explorer/filter.tsx, packages/web/app/src/components/target/settings/cdn-access-tokens.tsx, packages/web/app/src/components/ui/card.tsx, packages/web/app/src/components/ui/page.tsx, packages/web/app/src/components/v2/activities.tsx, packages/web/app/src/components/v2/empty-list.tsx, packages/web/app/src/components/v2/heading.tsx, packages/web/app/src/components/v2/switch.tsx, packages/web/app/src/components/v2/time-ago.tsx
=> Website design: Fix Cursor

packages/services/broker-worker/src/handler.ts, packages/services/broker-worker/src/models.ts, packages/services/broker-worker/tests/broker.spec.ts, packages/services/webhooks/src/jobs.ts
=> Opt-out from resolving response body when sending a webhook

.changeset/four-beds-give.md, packages/libraries/cli/README.md, packages/libraries/cli/src/commands/schema/fetch.ts, packages/services/api/src/modules/schema/module.graphql.ts, packages/services/api/src/modules/schema/providers/schema-manager.ts, packages/services/api/src/modules/schema/resolvers.ts, packages/services/api/src/modules/shared/providers/storage.ts, packages/services/storage/src/index.ts, packages/web/docs/src/pages/docs/api-reference/cli.mdx, packages/web/docs/src/pages/docs/features/schema-registry.mdx
See https://github.com/kamilkisiela/graphql-hive/issues/2716
Closes https://github.com/kamilkisiela/graphql-hive/issues/2716
Closes https://github.com/kamilkisiela/graphql-hive/issues/757
=> feat: fetch a specific schema version from the api via commit/actionId

packages/services/schema/README.md, packages/services/schema/src/environment.ts, packages/services/schema/src/index.ts, packages/services/service-common/src/fastify.ts
Resolves https://github.com/kamilkisiela/graphql-hive/issues/2768
=> add a way to override the request body limit for fastify

packages/services/broker-worker/src/models.ts
=> Log details when broker receives a non-post request

packages/web/docs/src/pages/docs/integrations/apollo-router.mdx
=> improve apollo router, usage reporting docs

packages/services/usage/src/usage.ts
Closes https://github.com/kamilkisiela/graphql-hive/issues/2779
=> Ensure validity of operation reports

packages/web/docs/src/pages/docs/api-reference/client.mdx
Related https://github.com/Urigo/graphql-mesh/issues/5871#issuecomment-1695193742
=> Add GraphQL Mesh

packages/services/api/src/modules/integrations/resolvers.ts
=> Use uuid instead of cleanId when deleting integrations

packages/services/api/src/modules/operations/providers/operations-reader.ts, packages/services/usage-ingestor/src/ingestor.ts, packages/services/usage-ingestor/src/processor.ts, packages/services/usage-ingestor/src/writer.ts
No more writes to `*_old` tables.
=> Use only new tables introduced by #2712

packages/services/schema/__tests__/cache.spec.ts, packages/services/schema/src/cache.ts
SENTRY-4283369594
SENTRY-4341424021
=> Re-run the schema composition when cache expires during waiting

packages/services/service-common/package.json, packages/services/service-common/src/heartbeats.ts, pnpm-lock.yaml
=> Add retry logic to heartbeats

packages/web/app/pages/[organizationId]/view/manage-subscription.tsx
=> Disable buttons during mutation in subscription management

deployment/utils/cloudflare.ts, packages/services/cdn-worker/src/analytics.ts, packages/services/cdn-worker/src/index.ts
=> Add worker analytics bindings

packages/web/docs/src/components/landing-page.tsx
=> Landing page: Text color

packages/services/api/src/modules/schema/providers/schema-publisher.ts
=> Limit gh's check-run summary to 60k characters

codegen.mts, packages/services/api/src/modules/operations/module.graphql.ts, packages/services/api/src/modules/operations/providers/operations-manager.ts, packages/services/api/src/modules/operations/providers/operations-reader.ts, packages/services/api/src/modules/operations/resolvers.ts, packages/services/api/src/shared/mappers.ts, packages/services/cdn-worker/src/artifact-handler.ts, packages/services/cdn-worker/src/dev.ts, packages/services/cdn-worker/src/index.ts, packages/web/app/pages/[organizationId]/[projectId]/[targetId]/operations.tsx, packages/web/app/pages/[organizationId]/[projectId]/[targetId]/operations/[operationName]/[operationHash].tsx, packages/web/app/pages/[organizationId]/[projectId]/[targetId]/operations/schema-coordinate/[coordinate].tsx, packages/web/app/src/components/target/explorer/common.tsx, packages/web/app/src/components/target/explorer/enum-type.tsx, packages/web/app/src/components/target/explorer/input-object-type.tsx, packages/web/app/src/components/target/explorer/interface-type.tsx, packages/web/app/src/components/target/explorer/object-type.tsx, packages/web/app/src/lib/hooks/use-date-range-controller.ts
=> Dedicated page for a schema coordinate

packages/services/schema/package.json, pnpm-lock.yaml
=> Use theguild/federation-composition@0.1.1

packages/web/app/src/components/target/explorer/common.tsx
=> Sort fields in Explorer by usage DESC, name ASC

packages/web/app/src/components/v2/input.tsx
=> Fix 0 0 7 in Conditional Breaking Changes settings

packages/services/api/src/modules/operations/providers/operations-reader.ts, packages/services/api/src/modules/operations/resolvers.ts, packages/web/app/src/components/target/insights/Stats.tsx
and prevent clicking "Other clients (x)" label in clients chart (Insights)
=> Handle "unknown" client as empty or unknown

packages/services/api/src/modules/schema/providers/schema-publisher.ts
=> fix: use boolean condition

packages/services/api/src/modules/schema/module.graphql.ts, packages/services/api/src/modules/schema/resolvers.ts, packages/web/app/src/components/project/settings/external-composition.tsx, packages/web/app/src/components/v2/docs-note.tsx, packages/web/app/src/lib/docs-url.ts, packages/web/docs/src/pages/product-updates/2023-10-10-native-federation-2.mdx
- adds a product update
- links in external composition settings to the product update
=> Announce Native Apollo Federation v2 support

packages/services/api/src/modules/schema/providers/schema-publisher.ts
=> fix: disable the access check which might fail due to pagination

packages/services/api/src/modules/schema/providers/schema-manager.ts, packages/services/api/src/modules/schema/providers/schema-publisher.ts, packages/services/api/src/modules/shared/providers/redis.ts, packages/services/schema/src/index.ts, packages/services/server/src/graphql-handler.ts
Make metrics more accurate to help us prevent regressions.
=> Add logs to all end paths of schema:publish

packages/web/app/src/components/organization/Permissions.tsx, packages/web/app/src/components/v2/modals/create-access-token.tsx, packages/web/app/src/lib/access/common.ts
=> limit registry/usage access tokens to registry/access token scopes

packages/services/api/src/modules/schema/providers/schema-publisher.ts
Fixes https://github.com/kamilkisiela/graphql-hive/actions/runs/6505556274/job/17669407250
=> fix: createPublishCheckRun in not defined

packages/web/docs/src/pages/docs/api-reference/cli.mdx, packages/web/docs/src/pages/docs/api-reference/client.mdx, packages/web/docs/src/pages/docs/features/schema-policy.mdx, packages/web/docs/src/pages/docs/management/external-schema-composition.mdx, packages/web/docs/src/pages/docs/management/targets.mdx
I continue to work through documentation, and have found a few more spots that could be updated. 
A few small typos found in documentation are now fixed. 
n/a
=> A few typos in documentation

packages/web/app/src/components/organization/Permissions.tsx, packages/web/app/src/components/v2/modals/create-access-token.tsx, packages/web/app/src/lib/access/common.ts
Reverts kamilkisiela/graphql-hive#3004
=> Revert "limit registry/usage access tokens to registry/access token scopes"

packages/services/api/src/modules/operations/providers/clickhouse-client.ts
- Log non-http errors
- Pass query_id to ClickHouse server
Every HTTP call to ClickHouse gets a unique identifier that we can use to correlate logs of ClickHouse with logs of GraphQL API.
=> Add a unique id to every ClickHouse call

packages/services/api/src/modules/schema/resolvers.ts, packages/services/api/src/shared/mappers.ts, packages/web/app/src/components/target/explorer/common.tsx
It adds a yellow `*` next to the field with a tooltip saying "This field is used but the presented arguments are not."
If anyone has a better idea on how to present it, please create a Pull Request.
Closes #3049
=> Communicate used field with unused arguments in Unused Schema view

packages/services/api/src/modules/schema/providers/schema-manager.ts, packages/services/api/src/modules/shared/lib/task-runner.ts, packages/services/server/src/index.ts
Deferred promise in Task Runner was never resolved.
=> Fix GraphQL API watch mode process termination

packages/services/api/src/modules/operations/module.graphql.ts, packages/services/api/src/modules/operations/providers/operations-manager.ts, packages/services/api/src/modules/operations/providers/operations-reader.ts, packages/services/api/src/modules/operations/resolvers.ts, packages/web/app/pages/[organizationId]/[projectId]/index.tsx, packages/web/app/pages/[organizationId]/index.tsx
Here's the order of the cards
1. request count DESC
2. schema versions count DESC
3. name ASC
=> Sort Project and Target cards by requests count

packages/services/emails/src/scheduler.ts
=> refactor: simplify check

.changeset/poor-chefs-build.md, packages/libraries/client/package.json, pnpm-lock.yaml
Closes https://github.com/kamilkisiela/graphql-hive/issues/3232
=> Update axios range in client package

packages/web/app/src/components/layouts/target.tsx, packages/web/app/tailwind.config.cjs
=> UI fixes for large screens 

packages/services/api/src/modules/operations/providers/clickhouse-client.ts
Logs when when ClickHouse query is completed.
=> Log ClickHouse query execution performance

packages/web/app/src/config/supertokens/backend.ts
limit it to `profile` and `email`.
=> Limit Google and GitHub OAuth scopes

packages/migrations/test/2023.11.02T14.41.41.schema-checks-dedup.test.ts, packages/services/api/src/modules/shared/providers/storage.ts, packages/services/server/src/index.ts, packages/services/service-common/src/index.ts, packages/services/service-common/src/sentry.ts, packages/services/storage/src/index.ts
Alternative approach of cleaning the schema SDLs in the store
=> feat: schema sdl store purging with schema checks

.changeset/light-guests-dress.md, packages/libraries/client/src/internal/agent.ts
=> Allow to pass http and https agents

packages/services/cdn-worker/src/artifact-handler.ts, packages/services/cdn-worker/src/dev-polyfill.ts, packages/services/cdn-worker/src/dev.ts, packages/services/cdn-worker/src/env.ts, packages/services/cdn-worker/src/handler.ts, packages/services/cdn-worker/src/index.ts
=> feat: serve artifacts in legacy endpoints from R2 instead of KV

deployment/services/graphql.ts, packages/services/api/src/modules/cdn/providers/cdn.provider.ts, packages/services/api/src/modules/cdn/providers/tokens.ts, packages/services/api/src/modules/schema/providers/schema-publisher.ts, packages/services/cdn-worker/src/artifact-handler.ts, packages/services/cdn-worker/src/dev-polyfill.ts, packages/services/cdn-worker/src/dev.ts, packages/services/cdn-worker/src/env.ts, packages/services/cdn-worker/src/handler.ts, packages/services/cdn-worker/src/index.ts, packages/services/cdn-worker/tests/cdn.spec.ts, packages/services/server/README.md, packages/services/server/src/environment.ts
This removes the legacy CDN writes, which are no longer necessary.
=> feat: no longer publish to the legacy CDN

packages/services/api/src/modules/cdn/providers/cdn.provider.ts
Adds more verbose logging for identifying potential issues. (https://guild-oss.slack.com/archives/C05LPPEHZHN/p1698772873246899)
=> feat: add logging for CDN access token S3 interactions

packages/services/server/src/environment.ts
=> fix: remove unused environment variables from validation

deployment/services/graphql.ts, packages/services/api/src/modules/cdn/providers/cdn.provider.ts, packages/services/api/src/modules/cdn/providers/tokens.ts, packages/services/api/src/modules/schema/providers/schema-publisher.ts, packages/services/cdn-worker/src/artifact-handler.ts, packages/services/cdn-worker/src/dev-polyfill.ts, packages/services/cdn-worker/src/dev.ts, packages/services/cdn-worker/src/env.ts, packages/services/cdn-worker/src/handler.ts, packages/services/cdn-worker/src/index.ts, packages/services/cdn-worker/tests/cdn.spec.ts, packages/services/server/README.md, packages/services/server/src/environment.ts
=> revert cdn adjustments

packages/web/docs/src/pages/docs/features/high-availability-cdn.mdx
Mentions the hosts that the CDN uses in the documentation.
=> docs: mention allow-list hosts for CDN in documentation

packages/web/docs/src/pages/docs/integrations/graphql-yoga.mdx
=> Yoga plugin document update

packages/services/api/src/modules/shared/providers/storage.ts, packages/services/storage/src/index.ts
This code is unused, as we now create the check-run before creating a schema check/ doing a schema publish.
=> chore: remove unused code

deployment/services/graphql.ts
=> chore: remove trailing slash in url configuration

docs/DEVELOPMENT.md, packages/services/api/src/modules/integrations/providers/github-integration-manager.ts
Closes https://github.com/kamilkisiela/graphql-hive/issues/3251
It is just a small typo... 👯
=> fix: properly link github check-run to hive schema check

.github/workflows/lint.yaml, .gitignore
It was gitignored in #818. Not sure why...
=> Revert: .gitignore > cypress

packages/web/docs/src/pages/product-updates/2023-11-24-non-npm-cli-version-selection.mdx
=> Product Update: Install a specific version of CLI

packages/web/docs/public/install.sh
=> Fix aarch* checking in CLI's install.sh

packages/web/app/pages/[organizationId]/[projectId]/[targetId]/checks.tsx
=> fix: retain schema check filters when navigating to next schema check

packages/migrations/src/actions/2023.01.17T10.46.28.import-legacy-s3-keys-to-database.ts, packages/services/api/src/modules/cdn/providers/cdn.provider.ts, packages/services/api/src/modules/schema/providers/artifact-storage-writer.ts, packages/services/cdn-worker/src/key-validation.ts, packages/web/docs/src/pages/docs/self-hosting/s3-provider.mdx, pnpm-lock.yaml
See https://github.com/kamilkisiela/graphql-hive/issues/3461
Closes https://github.com/kamilkisiela/graphql-hive/issues/3461
=> fix: ensure s3 query is always signed

packages/web/docs/src/pages/docs/api-reference/client.mdx, packages/web/docs/src/pages/docs/integrations/apollo-gateway.mdx, packages/web/docs/src/pages/docs/integrations/apollo-server.mdx, packages/web/docs/src/pages/docs/integrations/envelop.mdx, packages/web/docs/src/pages/docs/integrations/graphql-ruby.mdx, packages/web/docs/src/pages/docs/integrations/graphql-yoga.mdx
=> docs: remove legacy reporting + backlink to client documentation

.github/workflows/build-and-dockerize.yaml
Based on https://github.com/moby/buildkit/issues/2492#issuecomment-1829827169
=> Ignore Docker build cache errors

packages/web/app/src/components/layouts/organization.tsx, packages/web/app/src/components/layouts/project.tsx
=> fix: attempt to hard navigate issue for organization and project tabs

packages/services/storage/src/index.ts
Name of selected columns did not match related Zod model.
=> Fix selected columns in Storage.getSchemaVersionByActionId

packages/web/app/pages/api/proxy.ts
This will reduce the number of transactions in Sentry by half.
=> Do not create Sentry transactions for /api/proxy

packages/web/app/pages/[organizationId]/[projectId]/[targetId]/laboratory.tsx
=> fix css syntax in laboratory styles overrides

integration-tests/package.json, integration-tests/testkit/auth.ts, packages/libraries/cli/CHANGELOG.md, packages/services/api/package.json, packages/services/api/src/modules/alerts/providers/adapters/webhook.ts, packages/services/api/src/modules/billing/providers/billing.provider.ts, packages/services/api/src/modules/policy/providers/schema-policy-api.provider.ts, packages/services/api/src/modules/rate-limit/providers/rate-limit.provider.ts, packages/services/api/src/modules/schema/providers/orchestrators/federation.ts, packages/services/api/src/modules/schema/providers/orchestrators/single.ts, packages/services/api/src/modules/schema/providers/orchestrators/stitching.ts, packages/services/api/src/modules/shared/providers/emails.ts, packages/services/api/src/modules/token/providers/token-storage.ts, packages/services/api/src/modules/usage-estimation/providers/usage-estimation.provider.ts, packages/services/rate-limit/package.json, packages/services/rate-limit/src/emails.ts, packages/services/rate-limit/src/limiter.ts, packages/services/stripe-billing/package.json, packages/services/usage/package.json, packages/services/usage/src/tokens.ts, packages/web/app/package.json, pnpm-lock.yaml
Trying to narrow down the connection issues.
See SENTRY-4706754519 and SENTRY-4706754481
=> Use whatwg-node/fetch for tRPC calls

.changeset/late-pumpkins-switch.md, packages/libraries/client/src/internal/types.ts, packages/libraries/client/src/internal/usage.ts, packages/libraries/client/tests/usage.spec.ts
=> Update `exclude` arg to accept RegExp (#3555)

.prettierignore
Avoids conflicts with changesets
=> prettierignore CHANGELOG.md files

packages/web/docs/src/pages/docs/self-hosting/get-started.mdx
Adds app to self-hosting hive
Doc addition
See changes
N/A
=> docs: add app to self hosting hive

packages/services/api/package.json, packages/services/schema/package.json, pnpm-lock.yaml
https://github.com/the-guild-org/federation/blob/main/CHANGELOG.md#062
=> Update theguild/federation-composition to v0.6.2

packages/services/api/package.json, packages/services/schema/package.json, pnpm-lock.yaml
https://github.com/the-guild-org/federation/blob/main/CHANGELOG.md#070
=> Update theguild/federation-composition to v0.7.0

packages/libraries/router/CHANGELOG.md, packages/libraries/router/router.yaml
=> Modify router.yaml and update Router's changelog

packages/services/storage/src/index.ts
Even though we ask for `100`, we get `20` now.
=> Set hard-limit to 200 in Storage.getPaginatedDocumentsForDocumentCollection

packages/libraries/cli/README.md
=> chore: update cli readme

packages/services/schema/src/orchestrators.ts
=> fix: prevent failed composition from breaking project settings

packages/services/api/src/modules/schema/module.graphql.ts, packages/services/api/src/modules/schema/resolvers.ts, packages/web/app/pages/[organizationId]/[projectId]/[targetId]/explorer.tsx, packages/web/app/pages/[organizationId]/[projectId]/[targetId]/explorer/unused.tsx, packages/web/app/src/components/v2/empty-list.tsx
Closes https://github.com/kamilkisiela/graphql-hive/issues/3892
=> feat: always use the latest valid version for the schema explorer

packages/web/docs/src/components/product-updates.tsx, packages/web/docs/src/pages/product-updates/2024-02-08-upcoming-stitching-project-changes.mdx
=> docs: add stitching project change product update

packages/libraries/client/src/version.ts, packages/services/emails/src/index.ts, packages/services/policy/src/index.ts, packages/services/rate-limit/src/index.ts, packages/services/schema/src/index.ts, packages/services/server/src/index.ts, packages/services/stripe-billing/src/index.ts, packages/services/tokens/src/index.ts, packages/services/usage-estimator/src/index.ts, packages/services/usage-ingestor/src/index.ts, packages/services/usage/src/index.ts, packages/services/webhooks/src/index.ts, packages/web/app/environment.ts, scripts/upload-sourcemaps.sh
=> sentry fixes

packages/services/storage/src/db/pool.ts
Might fix https://github.com/kamilkisiela/graphql-hive/issues/4008
Suggested in https://github.com/brianc/node-postgres/issues/2512
=> added idleTimout=30 for pg connections

packages/web/docs/src/pages/docs/integrations/ci-cd.mdx
=> docs: best practices for multi-environments

packages/web/docs/src/pages/docs/self-hosting/get-started.mdx
Adds information what needs to be done to unlock the full potential of HIVE in self-hosting mode.
Information on self-hosting HIVE and using enterprise functionality.
Self-explaining
N/A
=> docs: add information on switching to ENTERPRISE plan

packages/services/api/src/modules/operations/providers/clickhouse-client.ts, packages/services/api/src/modules/operations/providers/tokens.ts, packages/services/server/src/index.ts, packages/services/usage-estimator/src/estimator.ts, packages/services/usage-estimator/src/index.ts
Fixes https://github.com/kamilkisiela/graphql-hive/issues/4066
=> Fix ClickHouse stats reporting

integration-tests/tests/api/schema/publish.spec.ts, packages/services/api/src/modules/schema/providers/models/composite-legacy.ts, packages/services/api/src/modules/schema/providers/models/composite.ts, packages/services/api/src/modules/schema/providers/models/shared.ts, packages/services/api/src/modules/schema/providers/schema-publisher.ts
Closes https://github.com/kamilkisiela/graphql-hive/issues/3897
=> feat: sort services/schemas before attempting composition

packages/web/app/pages/[organizationId]/[projectId]/[targetId]/insights/client/[name].tsx
closes https://github.com/kamilkisiela/graphql-hive/issues/4068
=> fix conditional hook

packages/web/docs/src/pages/docs/features/high-availability-cdn.mdx
=> docs: fix url typo

packages/web/app/pages/[organizationId]/[projectId]/[targetId]/checks.tsx, packages/web/app/pages/[organizationId]/[projectId]/[targetId]/history.tsx
Closes https://github.com/kamilkisiela/graphql-hive/issues/4081
=> fix: only show service/supergraph for relevant projects

turbo.json
=> fix: include persisted documents in server input

packages/services/api/src/modules/schema/providers/schema-version-helper.ts, packages/services/storage/src/index.ts
=> fix: avoid n+1 query

packages/services/api/src/modules/operations/providers/operations-reader.ts, packages/web/app/src/components/target/history/errors-and-changes.tsx
=> fix: style and ordering for schema change clients

packages/services/api/src/modules/schema/providers/models/composite-legacy.ts, packages/services/api/src/modules/schema/providers/models/composite.ts
=> fix: typescript exclamation mark

packages/web/docs/src/pages/product-updates/2024-02-26-schema-check-top-affected-operations.mdx
=> docs: add product update

packages/web/app/src/components/project/settings/native-composition.tsx
=> split native federation check into separate query

deployment/services/proxy.ts
=> set timeout for app to 60 seconds

packages/services/api/src/modules/schema/providers/schema-publisher.ts, packages/web/app/src/components/target/history/errors-and-changes.tsx
=> resolve correct target name

packages/services/api/src/modules/schema/providers/breaking-schema-changes-helper.ts
=> safer lookup based on object identity

packages/services/api/src/modules/operations/providers/clickhouse-client.ts
=> Fix QUERY_WITH_SAME_ID_IS_ALREADY_RUNNING by appending query_id

integration-tests/tests/api/artifacts-cdn.spec.ts, packages/services/cdn-worker/src/errors.ts
Closes https://github.com/the-guild-org/website/issues/1537
=> Fix description broken link

deployment/utils/observability.ts
Reverts kamilkisiela/graphql-hive#4257
=> Revert "chore(deps): update helm release opentelemetry-collector to v0.83.1"

packages/web/app/package.json, pnpm-lock.yaml
It is not compatible with ui/components/command and causes all options to be disabled
=> Downgrade cmdk from 1.0.0 to 0.2.1

packages/services/api/src/modules/operations/providers/operations-reader.ts, packages/web/app/src/lib/hooks/use-date-range-controller.ts
=> fix: correctly select materialized view and resolution

packages/services/api/src/modules/schema/providers/models/composite.ts
=> correct condition

pnpm-lock.yaml
=> fix lockfile lol

packages/services/api/src/modules/operations/lib/__tests__/pick-table-by-period.spec.ts, packages/services/api/src/modules/operations/lib/pick-table-by-provider.ts, packages/services/api/src/modules/operations/providers/operations-reader.ts
=> fix: correct range resolution for hourly

packages/services/api/src/modules/operations/providers/helpers.ts
=> magic numbers

packages/web/docs/src/pages/docs/specs/usage-reports.md, packages/web/docs/src/pages/product-updates/2024-03-20-new-date-range-picker.mdx, packages/web/docs/src/pages/product-updates/2024-03-26-subscription-defer-stream-usage-reporting.mdx
=> docs: product update subscription and defer stream usage

.eslintrc.cjs, packages/web/app/pages/[organizationId]/[projectId]/[targetId]/insights/[operationName]/[operationHash].tsx, packages/web/app/pages/[organizationId]/[projectId]/[targetId]/insights/client/[name].tsx, packages/web/app/pages/[organizationId]/[projectId]/[targetId]/insights/schema-coordinate/[coordinate].tsx, packages/web/app/pages/[organizationId]/view/support/[ticketId].tsx
=> Handle safely a missing router query param on first render

deployment/package.json, pnpm-lock.yaml
Reverts kamilkisiela/graphql-hive#4380
=> Revert "fix(deps): update dependency @pulumi/pulumi to v3.112.0"

.changeset/pink-lamps-melt.md, .prettierignore, integration-tests/testkit/cli.ts, integration-tests/tests/cli/dev.spec.ts, packages/libraries/cli/README.md, packages/libraries/cli/src/base-command.ts, packages/libraries/cli/src/commands/dev.ts, packages/services/api/src/modules/schema/module.graphql.ts, packages/services/api/src/modules/schema/providers/schema-manager.ts, packages/services/api/src/modules/schema/resolvers.ts, packages/web/docs/src/pages/docs/api-reference/cli.mdx
=> Allow to compose local subgraphs with subgraphs from the registry

packages/web/docs/next.config.mjs, packages/web/docs/src/pages/docs/get-started/apollo-federation.mdx, packages/web/docs/src/pages/docs/management/external-schema-composition.mdx, packages/web/docs/src/pages/docs/self-hosting/external-composition.mdx, packages/web/docs/src/pages/product-updates/2024-04-04-hive-dev-command.mdx, packages/web/docs/src/pages/product-updates/2024-04-04-native-federation-v2-support.mdx, packages/web/docs/src/pages/product-updates/_meta.ts
Let's merge it once #4394 #4383 are deployed to production.
=> Product Updates for Native Fed v2 and Hive Dev command

packages/web/docs/src/components/product-updates.tsx
=> Fix missing title in product-updates

packages/services/api/src/modules/operations/resolvers.ts, packages/services/api/src/modules/usage-estimation/providers/usage-estimation.provider.ts, packages/services/api/src/modules/usage-estimation/resolvers.ts, packages/services/usage-estimator/src/api.ts, packages/services/usage-estimator/src/estimator.ts
Merge it only after the 006 migration is completed.
=> Store monthly usage per organisation (part 2 - final)

packages/services/api/src/modules/schema/providers/schema-publisher.ts, packages/services/service-common/src/tracing.ts, packages/services/storage/package.json, packages/services/storage/src/index.ts, pnpm-lock.yaml
=> improve telemetry info

codegen.mts, packages/services/api/src/modules/schema/lib/deprecated-graphql.ts, packages/services/api/src/modules/schema/lib/unused-graphql.ts, packages/services/api/src/modules/schema/module.graphql.ts, packages/services/api/src/modules/schema/resolvers.ts, packages/services/api/src/shared/mappers.ts, packages/web/app/pages/[organizationId]/[projectId]/[targetId]/explorer.tsx, packages/web/app/pages/[organizationId]/[projectId]/[targetId]/explorer/[typename].tsx, packages/web/app/pages/[organizationId]/[projectId]/[targetId]/explorer/deprecated.tsx, packages/web/app/pages/[organizationId]/[projectId]/[targetId]/explorer/unused.tsx, packages/web/app/pages/[organizationId]/[projectId]/[targetId]/index.tsx, packages/web/app/src/components/target/explorer/common.tsx, packages/web/app/src/components/target/explorer/enum-type.tsx, packages/web/app/src/components/target/explorer/filter.tsx, packages/web/app/src/components/target/explorer/input-object-type.tsx, packages/web/app/src/components/target/explorer/interface-type.tsx, packages/web/app/src/components/target/explorer/object-type.tsx, packages/web/app/src/components/ui/date-range-picker.tsx
=> Schema Explorer with deprecated fields only

integration-tests/tests/api/schema/check.spec.ts, integration-tests/tests/api/schema/contracts-check.spec.ts, packages/migrations/src/actions/2024.04.09T10-10-00.check-approval-comment.ts, packages/migrations/src/run-pg-migrations.ts, packages/migrations/test/2024.01.26T00.00.01.schema-check-purging.test.ts, packages/services/api/src/modules/schema/module.graphql.ts, packages/services/api/src/modules/schema/providers/schema-manager.ts, packages/services/api/src/modules/schema/resolvers.ts, packages/services/api/src/modules/shared/providers/storage.ts, packages/services/server/src/use-armor.ts, packages/services/storage/src/db/types.ts, packages/services/storage/src/index.ts, packages/services/storage/src/schema-change-model.ts, packages/web/app/pages/[organizationId]/[projectId]/[targetId]/checks.tsx
=> Allow to add a note when accepting a breaking change

packages/web/app/src/components/get-started/trigger.tsx, packages/web/app/src/components/get-started/wizard.tsx, packages/web/app/src/components/ui/user-menu.tsx, packages/web/app/src/stories/callout.stories.tsx, packages/web/app/src/stories/get-started.stories.tsx
=> Redesign Get Started Wizard

.changeset/tough-brooms-compare.md, packages/libraries/client/src/apollo.ts, packages/libraries/client/src/gateways.ts, packages/libraries/client/src/internal/utils.ts, packages/libraries/router/CHANGELOG.md, packages/libraries/router/src/registry.rs
=> CDN endpoints with and without /artifact-type part

packages/services/api/src/modules/schema/providers/schema-manager.ts, packages/services/api/src/shared/entities.ts
> Cannot read properties of null (reading 'enabled')
=> Fix Settings page of a project

packages/web/docs/next.config.mjs, packages/web/docs/src/pages/docs/self-hosting/_meta.ts
=> Fix broken pages in docs website

.changeset/late-toys-nail.md, packages/libraries/cli/src/helpers/schema.ts, packages/services/api/src/modules/alerts/providers/adapters/common.ts, packages/services/api/src/modules/alerts/providers/adapters/slack.ts, packages/services/api/src/modules/schema/providers/schema-publisher.ts
We don't show it in UI since forever, now it's time to sync CLI and GH's check-run.
=> No longer show dangerous changes

.github/workflows/prettier.yaml
It's PAT with `workflow` scope
=> Use GH_PAT_WORKFLOW in prettier workflow

docker/docker-compose.community.yml, docker/docker-compose.dev.yml
Due to https://github.com/ClickHouse/ClickHouse/issues/62113 https://github.com/ClickHouse/ClickHouse/issues/62698
Fix (https://github.com/ClickHouse/ClickHouse/pull/62186) was merged, waiting for release.
=> Revert ClickHouse to v24.2

packages/services/api/src/modules/integrations/providers/github-integration-manager.ts, packages/services/api/src/modules/schema/providers/schema-publisher.ts
=> Limit GH Check-Run summary to 65k chars

packages/web/app/pages/[organizationId]/[projectId]/[targetId]/laboratory.tsx
Bug:
https://github.com/kamilkisiela/graphql-hive/issues/4142
=> bug fixed: laboratory unhandled runtime error when pressing "add operation" button

docker/docker-compose.community.yml
I believe that's a much better default
=> Use LOG_LEVEL=debug by default

packages/web/app/package.json, pnpm-lock.yaml
Reverts kamilkisiela/graphql-hive#4137
=> Revert "fix(deps): update dependency supertokens-web-js to v0.10.1"

packages/web/app/pages/[organizationId]/[projectId]/[targetId]/checks.tsx
Truncate target links in schema check target footer
Closes #4171 
Make the targets links summary readable
https://github.com/kamilkisiela/graphql-hive/assets/37614975/9a931266-6def-4636-8624-544cd03839ca
=> Truncate target links in schema check target footer

packages/web/app/pages/[organizationId]/[projectId]/view/policy.tsx, packages/web/app/pages/[organizationId]/view/policy.tsx
closes https://github.com/kamilkisiela/graphql-hive/issues/4679
=> Fix order of useToast hooks

integration-tests/tests/api/legacy-auth.spec.ts, packages/services/api/src/modules/operations/lib/__tests__/date-time-helpers.spec.ts, packages/services/api/src/modules/operations/lib/__tests__/pick-table-by-period.spec.ts, packages/services/api/src/modules/operations/lib/date-time-helpers.ts, packages/services/api/src/modules/operations/lib/pick-table-by-provider.ts, packages/services/api/src/modules/operations/providers/helpers.ts, packages/services/api/src/modules/operations/providers/operations-manager.ts, packages/services/api/src/modules/operations/providers/operations-reader.ts, packages/web/app/pages/[organizationId]/[projectId]/index.tsx, packages/web/app/pages/[organizationId]/index.tsx, packages/web/app/src/components/target/explorer/provider.tsx, packages/web/app/src/lib/date-math.spec.ts, packages/web/app/src/lib/date-math.ts, packages/web/app/src/lib/hooks/use-date-range-controller.spec.ts, pnpm-lock.yaml
Turns `22.06.2024 09:37` -> `27.06.2024 09:37` with `1 day` interval into `22.06.2024 00:00` -> `28.06.2024 00:00` with `1 day` interval.
=> Fix interval calculation in ClickHouse queries

packages/web/app/src/components/ui/date-range-picker.tsx, packages/web/app/src/stories/date-range-picker.stories.tsx
Date range component sorting was confusing, this PR come to sort the range based on weight.
closes #4696
=> Date range component: fix sorting and storybook

packages/web/app/src/components/ui/date-range-picker.tsx
=> Fix Date Range sorting

packages/libraries/core/src/client/collect-schema-coordinates.ts, packages/libraries/core/src/client/usage.ts, packages/libraries/core/tests/collect-schema-coordinates.spec.ts
this file is useful without the other logic for https://github.com/kamilkisiela/graphql-hive/pull/3068
I want to split up the logic here instead of one big PR with all the changes
=> refactor: move collect schema coordinates file to dedicated file

packages/services/api/src/modules/schema/providers/schema-manager.ts, packages/services/api/src/modules/shared/providers/storage.ts
Doing some cleanup for https://github.com/kamilkisiela/graphql-hive/pull/4746/files
Just removes unnecessary passed arguments, which makes using the thing from other code easier.
=> refactor: remove unused passed arguments

packages/libraries/cli/tsconfig.json
makes our lives easier, forgot to enable it for the CLI as well when introducing it for app.
=> feat: enable graphql autocomplete for cli

docker/router.dockerfile
Reverts kamilkisiela/graphql-hive#4511
Closes #4796
=> chore(deps): downgrade rust docker tag to v1.76

packages/web/app/src/components/ui/command.tsx, packages/web/app/src/pages/target.tsx
**Service not found**
**Keeping the state only in the url**
https://github.com/kamilkisiela/graphql-hive/assets/8167190/453d8126-f268-4188-ac85-c66e52875fd7
**View of a single schema**
**View of a Federation project with a single schema**
No combobox as there's nothing to pick from.
=> reduce complexity

packages/web/app/src/components/ui/command.tsx, packages/web/app/src/pages/target.tsx, packages/web/app/src/stories/schema-filter.stories.tsx
* This pull request come to make the schema sharable by service name:
`'/$organizationId/$projectId/$targetId?service=SchemaName'`
* When user select a schema, the param will add to the URL
* When user reset the schema select, the param will remove to the URL
* When user open new tab with the current param, the schema will open also
#4793 
https://github.com/kamilkisiela/graphql-hive/assets/37614975/a4aa8051-36a4-4e31-9211-ef9c3e544bf6
=> Handle subgraph schemas shareable

integration-tests/tsconfig.json
=> chore: enable graphqlsp for integration tests

packages/services/server/src/graphql-handler.ts
Enable experimental execution cancellation from Yoga
Let's test it in production:
- https://the-guild.dev/graphql/yoga-server/changelog#530
- https://the-guild.dev/graphql/yoga-server/docs/features/execution-cancellation
=> feat: use execution cancellation

packages/services/rate-limit/src/limiter.ts
It should be equal or higher than the highest possible retention value (enterprise), to prevent applying lower retention value then expected.
=> Set dataretention fallback to 365

packages/web/app/src/components/organization/billing/BillingPaymentMethod.tsx
Fixes https://github.com/kamilkisiela/graphql-hive/issues/4915
Closes https://github.com/kamilkisiela/graphql-hive/issues/4907
=> Fix Stripe dashboard button

.changeset/clean-cameras-compete.md, packages/libraries/core/src/client/usage.ts
=> fix: client info sanitisation

.changeset/khaki-mice-destroy.md, packages/libraries/apollo/src/index.ts, packages/libraries/apollo/tests/apollo.spec.ts, packages/libraries/yoga/tests/yoga.spec.ts
Closes https://github.com/kamilkisiela/graphql-hive/issues/4935
=> fix: unhandled rejection in apollo plugin

integration-tests/tests/api/target/usage.spec.ts, pnpm-lock.yaml
Tests to confirm that:
- removing an unused union member is safe
- removing a used union member is breaking
=> Add an integration test where a union member is deleted

packages/web/app/src/components/target/laboratory/create-collection-modal.tsx, packages/web/app/src/components/target/laboratory/create-operation-modal.tsx, packages/web/app/src/pages/target-laboratory.tsx
fixes https://www.notion.so/theguildoss/Make-Laboratory-usable-d4d44ccb81b3417db7076d9f572ca12d?pvs=4#8ebe297d1877472e9a19a46a76aeb433
https://github.com/kamilkisiela/graphql-hive/assets/7361780/7f0340a4-1e8c-4b5f-b8e6-32bb2d68d5c0
=> [laboratory] collections select should contain description

packages/web/app/src/components/layouts/target.tsx, packages/web/app/src/index.css, packages/web/app/src/pages/target-history.tsx, packages/web/app/src/pages/target-laboratory.tsx
https://github.com/kamilkisiela/graphql-hive/assets/7361780/1518ac11-1b98-4708-8eba-ca5abbd15c25
=> [laboratory] make GraphiQL resizable to full viewport size

packages/web/app/src/components/layouts/organization.tsx, packages/web/app/src/components/layouts/project.tsx, packages/web/app/src/components/layouts/target.tsx, packages/web/app/src/components/target/history/errors-and-changes.tsx, packages/web/app/src/components/ui/accordion.tsx, packages/web/app/src/index.css, packages/web/app/src/pages/target-history.tsx, packages/web/app/src/pages/target-laboratory.tsx
https://github.com/kamilkisiela/graphql-hive/assets/7361780/fa17f94d-1ebe-4637-8b65-b405d4394a85
=> [laboratory] scroll to operation in collections' accordion on first load

package.json, pnpm-lock.yaml
Reverts kamilkisiela/graphql-hive#5019
Due to https://github.com/francoismassart/eslint-plugin-tailwindcss/issues/348
=> Revert "chore(deps): update dependency eslint-plugin-tailwindcss to v3.17.4"

packages/services/api/package.json, packages/services/schema/package.json, pnpm-lock.yaml
Fix: do not expose federation__Scope and federation__Policy scalar definitions to a supergraph
=> Update theguild/federation-composition to v0.11.3

package.json, packages/web/app/src/components/target/laboratory/edit-operation-modal.tsx, packages/web/app/src/components/ui/accordion.tsx, packages/web/app/src/pages/target-laboratory.tsx, packages/web/docs/package.json, packages/web/docs/src/components/landing-page.tsx, pnpm-lock.yaml
Turns collection -> operation structure into a file tree. In future we could introduce drag&drop with sorting, to let users organize everything and easily move operations between collections.
**Before**
https://github.com/kamilkisiela/graphql-hive/assets/8167190/07a84e5e-2f26-4310-9542-9d33bca06f8d
**After**
https://github.com/kamilkisiela/graphql-hive/assets/8167190/a8e74500-a615-434e-a7e0-6e01ac7f4ae7
=> [laboratory] folder structure for collections

packages/services/api/package.json, packages/services/schema/package.json, pnpm-lock.yaml
fix: detect incorrect subtypes of interface fields across subgraphs
=> chore: update theguild/federation-composition to v0.11.4

deployment/utils/observability.ts
Reverts kamilkisiela/graphql-hive#5077
=> Revert "chore(deps): update helm release opentelemetry-collector to v0.96.0"

packages/web/docs/src/pages/docs/integrations/envelop.mdx
=> Fix broken link to yoga plugin

docker/docker-compose.dev.yml
=> Limit memory usage of docker-compose.dev.yaml

packages/services/api/package.json, packages/services/schema/package.json, pnpm-lock.yaml
Support INTERFACE_FIELD_NO_IMPLEM
=> Update theguild/federation-composition to v0.12.0

deployment/utils/observability.ts
Reverts kamilkisiela/graphql-hive#5146
=> Revert "chore(deps): update helm release opentelemetry-collector to v0.97.1"

packages/web/app/src/components/ui/tabs.tsx, packages/web/app/src/pages/target-history-version.tsx
https://github.com/kamilkisiela/graphql-hive/assets/7361780/1371f379-ca8e-4312-8a49-7a6b95d72385
=> [hive/app] fixes error `<button>` cannot appear as a descendant of `<button>` for `TabsTrigger` inside `TooltipTrigger

codegen.mts, packages/services/api/src/modules/activity/index.ts, packages/services/api/src/modules/activity/resolvers.ts, packages/services/api/src/modules/activity/resolvers/ActivityConnection.ts, packages/services/api/src/modules/activity/resolvers/MemberAddedActivity.ts, packages/services/api/src/modules/activity/resolvers/MemberDeletedActivity.ts, packages/services/api/src/modules/activity/resolvers/MemberLeftActivity.ts, packages/services/api/src/modules/activity/resolvers/OrganizationCreatedActivity.ts, packages/services/api/src/modules/activity/resolvers/OrganizationIdUpdatedActivity.ts, packages/services/api/src/modules/activity/resolvers/OrganizationNameUpdatedActivity.ts, packages/services/api/src/modules/activity/resolvers/OrganizationPlanChangeActivity.ts, packages/services/api/src/modules/activity/resolvers/ProjectCreatedActivity.ts, packages/services/api/src/modules/activity/resolvers/ProjectDeletedActivity.ts, packages/services/api/src/modules/activity/resolvers/ProjectIdUpdatedActivity.ts, packages/services/api/src/modules/activity/resolvers/ProjectNameUpdatedActivity.ts, packages/services/api/src/modules/activity/resolvers/Query/organizationActivities.ts, packages/services/api/src/modules/activity/resolvers/Query/projectActivities.ts, packages/services/api/src/modules/activity/resolvers/Query/targetActivities.ts, packages/services/api/src/modules/activity/resolvers/TargetCreatedActivity.ts, packages/services/api/src/modules/activity/resolvers/TargetDeletedActivity.ts, packages/services/api/src/modules/activity/resolvers/TargetIdUpdatedActivity.ts, packages/services/api/src/modules/activity/resolvers/TargetNameUpdatedActivity.ts
This PR migrates `activity` module to use Server Preset
=> Migrate `activity` module to Server Preset (Part 9)

packages/web/app/src/components/project/alerts/channels-table.tsx, packages/web/app/src/components/v2/tag.tsx
=> fix: access token success modal

codegen.mts, packages/services/api/src/modules/auth/index.ts, packages/services/api/src/modules/auth/module.graphql.mappers.ts, packages/services/api/src/modules/auth/resolvers.ts, packages/services/api/src/modules/auth/resolvers/Member.ts, packages/services/api/src/modules/auth/resolvers/MemberConnection.ts, packages/services/api/src/modules/auth/resolvers/Mutation/updateMe.ts, packages/services/api/src/modules/auth/resolvers/OrganizationAccessScope.ts, packages/services/api/src/modules/auth/resolvers/ProjectAccessScope.ts, packages/services/api/src/modules/auth/resolvers/Query/me.ts, packages/services/api/src/modules/auth/resolvers/TargetAccessScope.ts, packages/services/api/src/modules/auth/resolvers/User.ts, packages/services/api/src/modules/auth/resolvers/UserConnection.ts
This PR migrates `auth` module to Server Preset
=> Migrate `auth` module to Server Preset (Part 10)

packages/web/app/src/pages/target-history-version.tsx
=> fix: border style for schema versions

packages/services/api/src/modules/support/providers/support-manager.ts
We got some random 422 errors reported on Sentry and https://github.com/kamilkisiela/graphql-hive/issues/5180
Closes https://github.com/kamilkisiela/graphql-hive/issues/5180
There was an issue where we attempted to create an existing user on ZenDesk (e.g. because he signed up with both social login and email login) or similar. Creating that caused the 422 errors raised from the ZenDesk API. I altered the check to search the user on the ZenDesk API before attempting to create it. I also noticed that some properties sent to the ZenDesk API were sent as strings instead of integers, I also changed these. Now the tickets created by a user that is a member of multiple organizations will show up for the right organization.
=> fix: zendesk ticket user creation

packages/web/app/src/components/layouts/organization.tsx, packages/web/app/src/components/layouts/project.tsx, packages/web/app/src/components/layouts/target.tsx, packages/web/app/src/components/ui/dotted-background.tsx, packages/web/app/src/index.css, packages/web/app/src/pages/auth.tsx, packages/web/app/src/pages/organization-join.tsx, packages/web/app/src/pages/organization-new.tsx, packages/web/app/src/pages/target-checks-single.tsx, packages/web/app/src/pages/target-checks.tsx, packages/web/app/src/pages/target-history-version.tsx, packages/web/app/src/pages/target-history.tsx, packages/web/app/src/pages/target-laboratory.tsx, packages/web/app/src/pages/target.tsx
instead of fixing body to fixed 100% of viewport, we can ensure that the content container is always at least as big as the window size - header.
=> fix: identical page sizes and no flashing

docker/router.dockerfile
https://github.com/apollographql/router/issues/5084
=> Stick to Rust v1.76

packages/web/app/src/components/layouts/target.tsx, packages/web/app/src/components/organization/members/invitations.tsx, packages/web/app/src/components/organization/members/list.tsx, packages/web/app/src/components/organization/members/migration.tsx, packages/web/app/src/components/organization/members/roles.tsx, packages/web/app/src/components/target/settings/cdn-access-tokens.tsx, packages/web/app/src/components/target/settings/schema-contracts.tsx, packages/web/app/src/components/ui/page-content-layout.tsx, packages/web/app/src/components/ui/skeleton.tsx, packages/web/app/src/lib/urql.ts, packages/web/app/src/pages/target-app-version.tsx, packages/web/app/src/pages/target-apps.tsx, packages/web/app/src/pages/target-laboratory.tsx, packages/web/app/src/pages/target-settings.tsx, packages/web/app/src/router.tsx, packages/web/app/tailwind.config.cjs
UI implementation for app deployments. 
See https://github.com/kamilkisiela/graphql-hive/pull/4746
=> feat: app deployment UI

.github/workflows/release-alpha.yaml, .github/workflows/release-stable.yaml, packages/libraries/cli/package.json
=> Remove Windows installer

cypress/support/commands.ts, packages/web/app/src/components/organization/settings/oidc-integration-section.tsx
Closes #716
https://github.com/user-attachments/assets/40fb30e6-9d0c-4ef6-8f65-0715ddc6b184
=> Fetch endpoints from OpenID Connect Metadata document

packages/web/app/src/pages/index.tsx, packages/web/app/src/pages/target-checks-single.tsx, packages/web/app/src/pages/target-explorer.tsx, packages/web/app/src/pages/target-history-version.tsx, packages/web/app/src/pages/target-laboratory.tsx, packages/web/app/src/pages/target-settings.tsx
Some leftovers from https://github.com/kamilkisiela/graphql-hive/pull/5205
Loading spinners were positioned wrong.
=> fix: loading spinner positions

.eslintrc.cjs, packages/web/app/src/lib/supertokens/last-auth-method.ts, packages/web/app/src/lib/supertokens/start-auth-flow-for-provider.ts, packages/web/app/src/lib/supertokens/third-party-email-password-react-oidc-provider.ts, packages/web/app/src/pages/auth-sign-in.tsx, packages/web/app/src/pages/auth-sign-up.tsx, packages/web/app/tailwind.config.cjs
https://github.com/user-attachments/assets/72423de4-bd07-427f-bf9b-233c24b906ec
=> Hint recent authentication method

.github/workflows/build-and-dockerize.yaml, .github/workflows/dockerize-cli.yaml, .github/workflows/release-alpha.yaml, .github/workflows/release-stable.yaml, docker/cli.dockerfile, docker/docker.hcl
This does not require building everything again. We only publish docker images for the CLI after we published the alpha to npm anyways.
=> new approach for cli image building

deployment/index.ts, deployment/services/app.ts, deployment/utils/publish-app-deployment.ts
This simplifies our life.
TODO
=> chore: publish app deployment as part of pulumni step

packages/web/app/src/components/ui/button.tsx, packages/web/app/src/pages/organization.tsx, packages/web/app/src/pages/project.tsx, packages/web/app/src/router.tsx, pnpm-lock.yaml
Closes #5274
Option 1
Option 2
Option 3
=> Add searching and sorting options to the list of projects

README.md
Way to boost GraphQL Conf. Discussed on [Slack](https://guild-oss.slack.com/archives/C03J3MBLJ6M/p1722873867810819).
=> add graphql conf banner

packages/services/api/src/modules/schema/providers/artifact-storage-writer.ts, packages/services/cdn-worker/src/aws.ts
10s for writing artifacts, 5s to delete them.
=> Add time out to AWSClient

packages/web/app/src/components/target/history/errors-and-changes.tsx, packages/web/app/src/pages/target-checks-single.tsx
=> Fix text alignment in Schema Checks

packages/services/policy/package.json, packages/web/docs/package.json, packages/web/docs/theme.config.tsx, pnpm-lock.yaml
The tiniest first step towards the new design.
Updated the logo in the Hive landing page and docs.
Depends on https://github.com/the-guild-org/docs/pull/1581.
=> Use the new Hive Platform logo

packages/web/docs/package.json, packages/web/docs/src/components/arrow-icon.tsx, packages/web/docs/src/components/call-to-action.tsx, packages/web/docs/src/components/hero.tsx, packages/web/docs/src/components/landing-page.tsx, packages/web/docs/src/components/pricing.tsx, pnpm-lock.yaml
Added the features section. Need to upload proper cropped images so every section has one, but the layout for desktop is done. I imagine the mobile layout would be the same as with the old design, but let's circle back with designers.
=> Add features section (needs polish on images)

packages/web/docs/src/components/call-to-action.tsx, packages/web/docs/src/components/heading.tsx, packages/web/docs/src/components/hero.tsx, packages/web/docs/src/components/landing-page.tsx, packages/web/docs/src/components/pricing.tsx, packages/web/docs/src/components/stats.tsx
https://github.com/user-attachments/assets/943b7244-7f7c-45a1-9551-6a8a358bb62f
https://github.com/user-attachments/assets/fd9e0b42-eaa5-4c22-9334-4d7db1c525d2
Implemented the new styles for the counters and pricing.
Could probably change the font size in pricing for smaller screens, but I'm pretty happy with how it turned out.
=> Pricing & Counters

packages/libraries/cli/src/commands/app/create.ts, packages/libraries/cli/src/commands/app/publish.ts
=> chore: fix CLI typescript error

packages/web/docs/package.json, packages/web/docs/src/components/call-to-action.tsx, packages/web/docs/src/components/company-testimonials.tsx, packages/web/docs/src/components/ecosystem-management.tsx, packages/web/docs/src/components/feature-tabs.tsx, packages/web/docs/src/components/heading.tsx, packages/web/docs/src/components/hero.tsx, packages/web/docs/src/components/info-card.tsx, packages/web/docs/src/components/landing-page.tsx, packages/web/docs/src/components/logos.tsx, packages/web/docs/src/components/stats.tsx, packages/web/docs/src/components/team-section.tsx, packages/web/docs/tailwind.config.cjs, packages/web/docs/tsconfig.json, pnpm-lock.yaml
Added a desktop version of the testimonials section.
=> Company testimonials

packages/services/api/src/modules/alerts/resolvers/Project.ts, packages/services/api/src/modules/app-deployments/resolvers/Organization.ts, packages/services/api/src/modules/app-deployments/resolvers/Target.ts, packages/services/api/src/modules/auth/resolvers/Member.ts, packages/services/api/src/modules/auth/resolvers/User.ts, packages/services/api/src/modules/billing/resolvers/Organization.ts, packages/services/api/src/modules/cdn/resolvers/Contract.ts, packages/services/api/src/modules/cdn/resolvers/Target.ts, packages/services/api/src/modules/integrations/resolvers/Organization.ts, packages/services/api/src/modules/integrations/resolvers/Project.ts, packages/services/api/src/modules/oidc-integrations/resolvers/Organization.ts, packages/services/api/src/modules/oidc-integrations/resolvers/User.ts, packages/services/api/src/modules/policy/resolvers/Organization.ts, packages/services/api/src/modules/policy/resolvers/Project.ts, packages/services/api/src/modules/policy/resolvers/Target.ts, packages/services/api/src/modules/project/resolvers/Organization.ts, packages/services/api/src/modules/project/resolvers/Project.ts, packages/services/api/src/modules/rate-limit/resolvers/Organization.ts, packages/services/api/src/modules/support/resolvers/Organization.ts, packages/services/api/src/modules/target/resolvers/Project.ts, packages/services/api/src/modules/target/resolvers/Target.ts, packages/services/api/src/modules/token/resolvers/Target.ts
Changes after running codegen after upgrading server preset
=> chore: codegen updates

packages/web/app/src/components/target/laboratory/create-collection-modal.tsx, packages/web/app/src/stories/create-collection-modal.stories.tsx
- Use `zod`
- Use `react-hook-form`
- Fix some design issues
- Added component to Storybook: `Create` and `Update`
=> (1) Drop V2: Create Collection Modal

packages/web/app/src/components/target/laboratory/create-collection-modal.tsx, packages/web/app/src/components/target/laboratory/delete-collection-modal.tsx, packages/web/app/src/stories/delete-collection-modal.stories.tsx
- Align design for all delete modals
- Added component to Storybook
- Added `toast` for better user experience
=> (2) Drop V2: Delete Collection Modal

packages/web/app/src/components/target/laboratory/create-collection-modal.tsx, packages/web/app/src/components/target/laboratory/create-operation-modal.tsx, packages/web/app/src/stories/create-operation-modal.stories.tsx
- Align design for all modals
- Added component to Storybook
- Added `toast` for better user experience
=> (4) Drop v2: Create Operation Modal

packages/web/app/src/components/target/laboratory/create-collection-modal.tsx, packages/web/app/src/components/target/laboratory/edit-operation-modal.tsx, packages/web/app/src/stories/edit-operation-modal.stories.tsx
- Align design for all modals
- Added component to Storybook
- Added `toast` for better user experience
=> (5) Drop V2: Edit Operation Modal

packages/services/api/package.json, packages/services/api/src/create.ts, packages/services/cdn-worker/src/artifact-storage-reader.ts, packages/services/cdn-worker/src/aws.ts, pnpm-lock.yaml
=> feat: set timeout on undici level

packages/services/api/src/create.ts, packages/services/api/src/modules/app-deployments/providers/app-deployments.ts, packages/services/api/src/modules/app-deployments/providers/persisted-document-ingester.ts, packages/services/api/src/modules/app-deployments/worker/persisted-documents-worker.ts, packages/services/api/src/modules/cdn/providers/aws.ts, packages/services/api/src/modules/cdn/providers/cdn.provider.ts, packages/services/api/src/modules/schema/providers/artifact-storage-writer.ts, packages/services/api/src/modules/shared/providers/s3-config.ts
Replaces `fetch` with `got` only in the GraphQL API server
=> Use Got to write artifacts to S3/R2

packages/services/api/src/modules/operations/providers/clickhouse-client.ts, packages/services/api/src/modules/operations/providers/operations-reader.ts
=> increase batch size

packages/services/api/src/modules/operations/__tests__/sql.spec.ts, packages/services/api/src/modules/operations/providers/operations-reader.ts, packages/services/api/src/modules/operations/providers/sql.ts
=> feat: split coordinate array parameter

packages/services/api/src/modules/operations/providers/operations-reader.ts, packages/services/api/src/shared/__tests__/helpers.spec.ts, packages/services/api/src/shared/helpers.ts
=> feat: disable splitting clickhouse requests

packages/services/api/src/modules/schema/providers/models/composite.ts, packages/services/api/src/modules/schema/providers/models/single.ts, packages/services/api/src/modules/schema/providers/registry-checks.ts
trying to get more visibility around this area on what's going on
=> add more logs and traces for debugging

deployment/grafana-dashboards/Container-Logs.json, deployment/utils/contour.types.ts, deployment/utils/observability.ts, packages/services/api/src/modules/schema/providers/models/composite.ts, packages/services/api/src/modules/schema/providers/models/single.ts, packages/services/api/src/modules/schema/providers/registry-checks.ts, packages/services/api/src/modules/shared/providers/mutex.ts, packages/services/service-common/src/tracing.ts, packages/web/docs/src/pages/docs/self-hosting/telemetry.mdx, pnpm-lock.yaml
=> Trace mutex locks in otel and fix tracing issues

packages/services/api/src/modules/collection/resolvers.ts, packages/web/app/src/components/target/laboratory/create-operation-modal.tsx
=> increase operation size from 5k to 10k characters, show error message in toast

packages/web/docs/src/components/landing-page.tsx, packages/web/docs/src/components/team-section.tsx
It still needs pictures, and I'm not 100% happy with tablet-sized screens, but it matches the new designs for mobiles.
=> Team section mobile

packages/web/docs/src/components/call-to-action.tsx, packages/web/docs/src/components/decorations.tsx, packages/web/docs/src/components/hero.tsx, packages/web/docs/src/components/landing-page.tsx
It ain't much but it's honest work.
=> Mobile hero

packages/web/docs/package.json, packages/web/docs/src/components/call-to-action.tsx, packages/web/docs/src/components/community-section.tsx, packages/web/docs/src/components/frequently-asked-questions/index.tsx, packages/web/docs/src/components/frequently-asked-questions/questions.mdx, packages/web/docs/src/components/get-your-api-game-right.tsx, packages/web/docs/src/components/heading.tsx, packages/web/docs/src/components/landing-page.tsx, packages/web/docs/src/components/pricing.tsx, packages/web/docs/src/components/team-section/index.tsx, packages/web/docs/src/components/tools-and-libraries-cards.tsx, packages/web/docs/tailwind.config.cjs, pnpm-lock.yaml
https://github.com/user-attachments/assets/261a2ab2-23e2-48a6-95e4-e7349fc2d4ff
https://github.com/user-attachments/assets/126a69ba-7a6b-4fcd-a399-a1d9213346e0
Added the FAQs, "Get Your API Right" section and made some minor fixes.
=> Hive footer FAQ & Get Your API Right

packages/services/api/src/modules/shared/providers/mutex.ts
=> fix: unhandled promise rejection

packages/web/docs/src/pages/docs/features/app-deployments.mdx
=> fix: duplicated paragraph

packages/libraries/core/tests/usage.spec.ts
=> Fix flaky unit test

packages/web/app/package.json, pnpm-lock.yaml
Reverts kamilkisiela/graphql-hive#5489
=> Revert "chore(deps): update dependency lucide-react to v0.435.0"

packages/services/usage/src/index.ts
If a request (to check rate limits or to resolve data retention) from usage service to rate-limit service fails, use defaults and do not prevent a usage report to be dropped.
=> Gracefully catch http requests to rate-limit service in /usage

packages/web/app/src/pages/organization-settings.tsx
Issue:
https://theguild.zendesk.com/agent/tickets/314
=> Fix description text for change organization name modal

packages/services/api/src/modules/schema/lib/federation-super-graph.ts
=> Account for usedOverridden arg in extractSuperGraphInformation (#5547)

deployment/grafana-dashboards/CDN-Usage.json
=> update cloudflare dashboard

packages/services/cdn-worker/src/artifact-storage-reader.ts, packages/services/cdn-worker/src/index.ts
2s should be enough even for a Worker on the opposite side of the world calling us-east-2
=> Decrease timeout on S3/R2 calls to 2s

packages/services/cdn-worker/src/artifact-storage-reader.ts
Share more light on requests and retries
=> Add more breadcrumbs to CDN Worker

packages/web/app/src/pages/organization-settings.tsx
=> fix: add a space

packages/web/docs/src/components/feature-tabs.tsx
https://github.com/user-attachments/assets/efcbf4ea-f575-4113-9798-bb8d7858db87
Added background on hover and some extra padding with negative margin.
=> Feature highlight hover

packages/web/docs/src/components/team-section/index.tsx
I wanted to come up with a generalizable equation for this layout, but for now we're good with a ternary.
=> Team Section Polish

packages/web/docs/src/components/ecosystem-management.module.css, packages/web/docs/src/components/ecosystem-management.tsx, packages/web/docs/src/components/page.tsx
Made the tile title better on small screens and moved Crisp button to `z-index: 40` below the cookies consent banner.
=> fix landing page after deploy to prod

packages/web/docs/public/graphql-logo.svg, packages/web/docs/src/components/ecosystem-management.tsx
The relative link I pushed in #5587 won't work.
=> prefix svg logos with basePath

packages/web/docs/src/components/page.tsx
https://github.com/user-attachments/assets/629f1f76-09fd-4c38-bd09-71d6dd05fdef
This one has non-static position, so it's gonna work (as in the video).
=> Use proper selector to target #crisp-chatbox

packages/web/docs/src/pages/docs/gateway/_meta.ts, packages/web/docs/src/pages/docs/gateway/authorization-authentication.mdx, packages/web/docs/src/pages/docs/gateway/persisted-documents.mdx
moves jwt docs to top level and introduces them as the main authorization/authentication docs
=> docs: authorization and authentication

packages/web/docs/src/pages/docs/api-reference/gateway-config.mdx
Fixes https://github.com/ardatan/graphql-mesh/issues/7672
=> fix(docs/gateway): correct `logging` reference

packages/web/docs/src/pages/docs/other-integrations/ci-cd.mdx
I am directly fixing the parts that were confusing when initially setting up Hive CI/CD.
- Updated to use `actions/checkout@v4` instead of `v3`
- Used `HIVE_TOKEN` directly without exporting as an environment variable
- Documented that the `HIVE_ENDPOINT` environment variable is optional
- Clarified that 'schema.graphql' is a file path
=> ci-cd.mdx: Revised the document for better clarity.

README.md
Reverts kamilkisiela/graphql-hive#5309
=> Remove GraphQL Conf 2024 banner

scripts/apollo-router-action.ts
Fetching crates.io constantly fails
=> Use Github API to fetch the latest version of Apollo Router

packages/web/app/src/components/target/insights/Fallback.tsx, packages/web/app/src/components/target/insights/Filters.tsx, packages/web/app/src/components/target/insights/List.tsx, packages/web/app/src/components/target/insights/Stats.tsx, packages/web/app/src/lib/hooks/use-date-range-controller.ts, packages/web/app/src/lib/hooks/use-search-params-filters.ts, packages/web/app/src/lib/object.spec.ts, packages/web/app/src/lib/object.ts, packages/web/app/src/pages/target-insights-client.tsx, packages/web/app/src/pages/target-insights-operation.tsx, packages/web/app/src/pages/target-insights.tsx
=> feat: Track clients & operations filters using search params (#5616)

packages/libraries/cli/package.json, packages/services/api/package.json, packages/services/schema/package.json, pnpm-lock.yaml
Support directives on enum type definitions and extensions
=> Update theguild/federation-composition to v0.13.0

packages/libraries/cli/package.json, packages/services/api/package.json, packages/services/schema/package.json, pnpm-lock.yaml
Support directives on enum values and unions
=> Update theguild/federation-composition to v0.14.0

packages/services/cdn-worker/src/artifact-storage-reader.ts, packages/services/cdn-worker/src/aws.ts
Cloudflare Worker supports it and we reduce a bit of complexity
=> Use AbortSignal.any

packages/web/docs/src/pages/docs/gateway/monitoring-tracing.mdx
Fix customization examples and add instructions for labels customization.
Fixes #5643
=> docs: fix prometheus documentation

packages/web/app/src/components/layouts/organization.tsx, packages/web/app/src/components/ui/form.tsx, packages/web/app/src/index.css, packages/web/app/tailwind.config.cjs
- No page shift when triggering a form error
- Highlight icon of the selected project type
- Use red color with more contrast for black/darkish background
=> feat: improve create project modal

integration-tests/package.json, package.json, packages/migrations/package.json, packages/services/api/package.json, packages/services/broker-worker/package.json, packages/services/cdn-worker/package.json, packages/services/emails/package.json, packages/services/policy/package.json, packages/services/rate-limit/package.json, packages/services/schema/package.json, packages/services/server/package.json, packages/services/service-common/package.json, packages/services/storage/package.json, packages/services/stripe-billing/package.json, packages/services/tokens/package.json, packages/services/usage-common/package.json, packages/services/usage-estimator/package.json, packages/services/usage-ingestor/package.json, packages/services/usage/package.json, packages/services/webhooks/package.json, packages/web/app/package.json, packages/web/docs/package.json, pnpm-lock.yaml, rules/package.json, scripts/package.json
Changeset should ignore it now
=> Remove version from private packages

.changeset/moody-schools-kneel.md, integration-tests/tests/api/app-deployments.spec.ts, packages/libraries/cli/src/commands/app/create.ts, packages/services/api/src/modules/app-deployments/providers/persisted-document-ingester.ts
A client tried publishing an app deployment and could not see why the operations were rejected.
We now provide more helpful error messages in that scenario, pointing to the right document.
=> feat: improve error handling for app deployment creation

packages/services/api/src/modules/schema/providers/schema-manager.ts, packages/web/app/src/components/layouts/target.tsx, packages/web/app/src/components/target/settings/cdn-access-tokens.tsx, packages/web/app/src/pages/target-settings.tsx, packages/web/docs/src/pages/docs/management/sso-oidc-provider.mdx
A member without `settings` scope, but with `tokens` scope, couldn't access registry tokens sub-page.
=> Align target access on UI with backend

packages/web/docs/src/pages/docs/gateway/subscriptions.mdx
https://github.com/ardatan/graphql-mesh/issues/7208
=> Hive Gateway supports only SSE for subscriptions

.changeset/light-cougars-provide.md, configs/cargo/Cargo.lock, packages/libraries/core/src/client/collect-schema-coordinates.ts, packages/libraries/core/tests/usage-collector.spec.ts, packages/libraries/router/CHANGELOG.md, packages/libraries/router/Cargo.toml, packages/libraries/router/src/graphql.rs
between JS and Rust.
Correct collection of enum values when used in a list.
=> Align schema coordinates collecting logic

packages/web/app/package.json, pnpm-lock.yaml
Reverts graphql-hive/platform#5519 https://guild-oss.slack.com/archives/C01E8ATBQGN/p1729800117389199
=> Revert "chore(deps): update dependency react-hook-form to v7.53.0"

package.json, pnpm-lock.yaml
=> run `pnpm dedupe`

packages/web/app/src/lib/billing/stripe.tsx
https://guild-oss.slack.com/archives/C01E8ATBQGN/p1729766480779259
=> Avoid make stripe API calls on `development`. Update stripe.tsx

packages/web/app/src/components/ui/meta.tsx, packages/web/docs/src/pages/index.mdx
It is recommended by [ahref to keep these around 160 chars](https://ahrefs.com/seo/glossary/meta-description)
=> feat: improve description for site

pnpm-lock.yaml
=> Update dset from 3.1.2 to 3.1.4

packages/web/docs/src/pages/docs/self-hosting/cdn-artifacts.mdx
Removes typos
see above
see above
N/A
=> remove typos

packages/web/docs/src/pages/docs/schema-registry/index.mdx
Fixing typos in couple of words
=> Update index.mdx with spelling changes

turbo.json
`codegen.yml` is no longer a thing
=> Add codegen.mts to globalDependencies of turbo

packages/web/docs/src/authors.ts, packages/web/docs/src/pages/product-updates/2024-10-15-new-home.mdx, packages/web/docs/src/pages/product-updates/2024-10-29-new-home/index.mdx, packages/web/docs/src/pages/product-updates/2024-10-29-versioning-for-self-hosters/index.mdx
=> Product Update on new home

packages/web/docs/public/install-gateway.sh
Blocking https://github.com/the-guild-org/graphql-federation-gateway-audit/pull/77
=> Use the new repo in the install script

codegen.mts, packages/web/app/src/server/github.ts, packages/web/app/src/server/lab.ts, packages/web/app/src/server/slack.ts, packages/web/app/src/server/utils.ts
The query was invalid and affected Github Integration.
=> Fix /api/github/setup-callback

.changeset/sour-dolls-behave.md, packages/libraries/cli/package.json, packages/services/api/package.json, packages/services/schema/package.json, pnpm-lock.yaml
=> Update @theguild/federation to v0.14.1

packages/web/docs/next.config.js, packages/web/docs/src/pages/docs/gateway/index.mdx
closes https://github.com/the-guild-org/website/issues/1784
=> Fix 404 and broken links

integration-tests/testkit/auth.ts, packages/services/api/package.json, packages/services/api/src/modules/auth/lib/supertokens-strategy.ts, packages/services/server/package.json, packages/services/server/src/supertokens.ts, pnpm-lock.yaml
https://github.com/supertokens/supertokens-node/blob/master/CHANGELOG.md#1674---2024-03-01
=> chore: upgrade supertokens-node to 16.x.x

.changeset/wet-llamas-unite.md, deployment/services/supertokens.ts, docker/docker-compose.community.yml, docker/docker-compose.dev.yml, packages/migrations/src/actions/2024.11.11T00-00-00.supertokens-8.0.ts, packages/migrations/src/actions/2024.11.11T00-00-00.supertokens-8.x.x.ts, packages/migrations/src/pg-migrator.ts, packages/migrations/src/run-pg-migrations.ts
https://github.com/supertokens/supertokens-core/blob/master/CHANGELOG.md#801---2024-03-11
=> chore: upgrade supertokens-core to 8.x.x

packages/web/docs/src/pages/docs/gateway/deployment/serverless/cloudflare-workers.mdx
[Workers support explicit resource management](https://developers.cloudflare.com/workers/runtime-apis/rpc/lifecycle/#explicit-resource-management), so does Hive Gateway.
=> Document waiting for the Gateway to dispose in Cloudflare Workers

packages/services/api/src/modules/auth/lib/supertokens-strategy.ts
=> feat: add create target permission

.changeset/twelve-moons-lie.md, .github/workflows/release-stable.yaml, configs/cargo/Cargo.lock, packages/libraries/router/Cargo.toml, packages/libraries/router/package.json
Closes https://github.com/graphql-hive/platform/issues/291
=> Added release flow for hive-apollo-router-plugin crate

packages/libraries/router/README.md, packages/web/docs/src/authors.ts, packages/web/docs/src/pages/docs/other-integrations/apollo-router.mdx, packages/web/docs/src/pages/product-updates/2024-11-13-hive-plugin-apollo-router-crate.mdx
related https://github.com/graphql-hive/console/issues/291
=> added product update for Hive plugin on Crates.io

.changeset/seven-tools-cover.md, packages/services/usage/src/usage-processor-2.ts
Just a small typo fix I noticed.
=> fix: log formatting in usage reporting service

.changeset/afraid-papayas-perform.md, .changeset/great-baboons-invite.md, deployment/services/supertokens.ts, docker/docker-compose.community.yml, docker/docker-compose.dev.yml, packages/migrations/src/actions/2024.11.12T00-00-00.supertokens-9.0.ts, packages/migrations/src/actions/2024.11.12T00-00-00.supertokens-9.1.ts, packages/migrations/src/actions/2024.11.12T00-00-00.supertokens-9.2.ts, packages/migrations/src/actions/2024.11.12T00-00-00.supertokens-9.3.ts, packages/migrations/src/run-pg-migrations.ts
Upgrade `supertokens-core` to the latest possible version, since we are a few behind and don't want to fall behind even further.
Upgrading `supertokens-core` got simpler as it is backward compatible with more SDK versions.
- 9.0 https://github.com/supertokens/supertokens-core/blob/master/CHANGELOG.md#900---2024-03-13
- 9.1 https://github.com/supertokens/supertokens-core/blob/master/CHANGELOG.md#920---2024-08-20
- 9.2 https://github.com/supertokens/supertokens-core/blob/master/CHANGELOG.md#923---2024-10-09
- 9.3 https://github.com/supertokens/supertokens-core/blob/master/CHANGELOG.md#930
=> upgrade supertokens-core to 9.3

.github/workflows/ci-cache-cleaner.yaml
=> Clear GH Actions cache periodically

packages/web/app/package.json, pnpm-lock.yaml
Reverts graphql-hive/console#5980
=> Revert "chore(deps): update dependency react-hook-form to v7.53.2"

.github/workflows/apollo-router-release.yaml, .github/workflows/build-and-dockerize.yaml, .github/workflows/main.yaml, .github/workflows/pr.yaml, .github/workflows/release-docker.yaml
=> exploring multi arch docker builds for services 

packages/web/docs/src/components/ecosystem-management/index.tsx, packages/web/docs/src/pages/docs/gateway/other-features/security/rate-limiting.mdx, packages/web/docs/src/pages/docs/other-integrations/apollo-gateway.mdx
=> Fixes and improvements to the website

packages/web/docs/src/components/ecosystem-management/index.tsx, packages/web/docs/src/components/landing-page.tsx
Highlight our federation support, the fact we have a gateway, that we're an alternative to apollo
Make those things pop a bit more, they are lost and not so obvious to look at.
=> Improve the landing page a bit

packages/web/docs/src/pages/_app.tsx
The letter-spacing in docs doesn't look right now, this should help. For now at least.
=> Improve letter spacing in docs until we have more font weights

.eslintrc.cjs, cypress/e2e/app.cy.ts, cypress/e2e/usage.cy.ts, cypress/local.sh, cypress/support/testkit.ts, integration-tests/testkit/flow.ts, integration-tests/testkit/seed.ts, integration-tests/testkit/usage.ts, integration-tests/tests/api/target/usage.spec.ts, package.json, packages/web/app/src/components/layouts/organization-selectors.tsx, packages/web/app/src/components/layouts/organization.tsx, packages/web/app/src/components/layouts/project-selector.tsx, packages/web/app/src/components/layouts/target-selector.tsx, packages/web/app/src/components/organization/Permissions.tsx, packages/web/app/src/components/target/settings/registry-access-token.tsx, packages/web/app/src/pages/target-settings.tsx
It makes sure that sent operations are visible on Insights pages
We test a few cases, one is when a client name is undefined, the other when its value is "unknown"
=> Add E2E test for usage reporting

.changeset/seven-tools-cover.md
bad rebase in #5900 brought this chagneset. Not needed
=> no changeset needed

packages/web/docs/src/components/partners-page.tsx
trying to see if this fixes the logos on deployed router or if I need to do some other trick....
=> fix logos for partners

deployment/services/observability.ts, deployment/utils/observability.ts
needs https://github.com/graphql-hive/deployment/pull/1421
=> Enable observability for `dev` environment and `stdout` for sink

packages/services/api/src/modules/operations/providers/operations-reader.ts
```
29.8s - peak memory usage at 2.34GB (340K rows per second)
vs
0.9s - peak memory usage at  218MB (12.9M rows per second)
```
=> Speed up get_top_operations_for_types query

packages/web/docs/src/pages/docs/gateway/authorization-authentication.mdx
Based on the feedback on Crisp
=> Fix typos on authorization-authentication.mdx

packages/services/api/src/modules/schema/providers/schema-manager.ts, packages/services/api/src/modules/shared/providers/storage.ts, packages/services/api/src/shared/entities.ts, packages/services/storage/src/index.ts
I will touch this code soon, so I wanted ti first clean it up a bit.
=> refactor: decode user in storage

packages/services/api/src/modules/schema/providers/models/composite.ts, packages/services/schema/src/orchestrators.ts
related https://github.com/graphql-hive/console/pull/6054
=> improve logging around schema composition and external calls

packages/services/api/src/modules/auth/lib/target-access-token-strategy.ts, packages/services/api/src/modules/token/providers/token-storage.ts, packages/services/service-common/src/helpers.spec.ts, packages/services/service-common/src/helpers.ts, packages/services/service-common/src/index.ts, packages/services/tokens/src/api.ts, packages/services/usage/src/helpers.ts, packages/services/usage/src/index.ts
https://github.com/graphql-hive/console/pull/6045 introduced an exception that can crash the whole service. This PR fixes the implementation of the pull request, adds basic tests and replaces usages of similar functions in the codebase with this shared one.
=> fix(service): maskToken function throwing an exception

packages/services/api/src/modules/schema/providers/schema-manager.ts, packages/services/api/src/modules/shared/providers/storage.ts, packages/services/api/src/shared/entities.ts, packages/services/storage/src/index.ts
Reverts graphql-hive/console#6021
=> Revert "refactor: decode user in storage"

.github/workflows/main.yaml
Reverts graphql-hive/console#6076
=> enable again staging deployments

packages/web/docs/src/components/ecosystem-management/index.tsx
The hierarchy of headings is incorrect
=> Make 360° GraphQL API Management an h2

packages/web/docs/src/pages/docs/gateway/monitoring-tracing.mdx
This PR adds documentation for the new feature added by this PR: https://github.com/graphql-hive/gateway/pull/174
Please wait for release before actually merging :-)
=> docs: [prometheus] add docs for new `phases` and `shouldObserve` config

packages/web/docs/src/pages/docs/gateway/authorization-authentication.mdx
`resolveUser` should be `resolveUserFn`
=> Fix \`resolveUserFn\` typo authorization-authentication.mdx

.github/workflows/validate-mdx.links.yaml, package.json, packages/web/docs/src/app/docs/[[...mdxPath]]/page.tsx, packages/web/docs/src/content/docs/api-reference/client.mdx, pnpm-lock.yaml, scripts/validate-mdx-links.ts
[Thread on Slack](https://northstar-e5s5760.slack.com/archives/C07DYCW4NUD/p1733416767816089)
Used `next-validate-link` to add a CI check that ensures all links lead to pages that exist.
=> Validate MDX links

deployment/index.ts, deployment/services/cloudflare-security.ts
We should merge this PR separately, before https://github.com/graphql-hive/console/pull/6071  because CSP is deployed just once (for the entire Apex domain).
=> CSP adjustments to support Lab preflight worker

packages/web/docs/src/theme.config.tsx
=> feat: add partners to footer

packages/web/app/src/components/layouts/target.tsx
https://guild-oss.slack.com/archives/C01E8ATBQGN/p1734531251730209
=> Fix flag for CDN code block

packages/services/api/src/modules/token/providers/token-storage.ts, packages/services/tokens/src/multi-tier-storage.ts, packages/services/usage/src/tokens.ts
=> Improve logging around tokens and fix initial read path

deployment/grafana-dashboards/Hive-Vitals.json, deployment/grafana-dashboards/Performance-Traces.json
It should look something like this:
=> feat(grafana): postgres connection panel, db performance tracking dashboard

deployment/grafana-dashboards/Performance-Traces.json
=> feat(grafana): added more views to performance tracing

deployment/services/usage.ts
Reverts graphql-hive/console#6083
=> Revert "limit memory on usage service"

.changeset/fair-donuts-cough.md, packages/web/docs/src/pages/docs/management/_meta.ts, packages/web/docs/src/pages/docs/management/audit-logs.mdx, packages/web/docs/src/pages/product-updates/2024-12-27-audit-logs/index.mdx
See https://github.com/graphql-hive/console/pull/5530
=> docs: audit log changeset + documentation

packages/services/api/src/modules/schema/providers/contracts.ts
=> fix: log typo for contract checks

packages/web/docs/src/mermaid.css, packages/web/docs/src/pages/_app.tsx, packages/web/docs/src/pages/docs/gateway/_meta.ts, packages/web/docs/src/pages/docs/gateway/other-features/_meta.ts, packages/web/docs/src/pages/docs/gateway/other-features/custom-plugins.mdx, packages/web/docs/src/pages/docs/gateway/subscriptions.mdx, packages/web/docs/tailwind.config.ts, pnpm-lock.yaml
This is a follow up of the #6128 PR.
It contains:
> [!NOTE]
>  I've modified the Tailwind configuration to give access to the primary color of the nextra theme. Before, it was entirely overridden by the `hive-yellow` color. 
> 
> I've named it `nextra-primary` instead of changing the `primary` color value to avoid breaking change, and to maintain coherence with Figma.
=> docs: finalize Custom Plugins documentation

packages/web/docs/src/pages/docs/dashboard/laboratory/preflight-scripts.mdx
Once the oauth and oidc helpers are done, the list of examples will be complete and docs will ve much nicer than it is today.
=> Rewrite documentation of Preflight Script and explain the API

package.json, pnpm-lock.yaml
https://guild-oss.slack.com/archives/C01E8ATBQGN/p1735797170636169
=> override `ip` package with `neoip`

.changeset/quiet-meals-refuse.md
https://github.com/graphql-hive/console/pull/6266
=> added missing changeset for #6266

packages/web/docs/src/components/ecosystem-page/components.tsx, packages/web/docs/src/components/ecosystem-page/ecosystem-page-nav-h2.tsx, packages/web/docs/src/components/ecosystem-page/page.tsx, packages/web/docs/src/components/got-an-idea-section.tsx, pnpm-lock.yaml
This PR improves mobile of /ecosystem page on smaller viewports.
=> Ecosystem page mobile fixes

.changeset/big-experts-melt.md, integration-tests/testkit/cli.ts, integration-tests/tests/cli/schema.spec.ts, packages/libraries/apollo/src/version.ts, packages/libraries/cli/README.md, packages/libraries/cli/package.json, packages/libraries/cli/src/commands/schema/fetch.ts, packages/libraries/cli/src/helpers/print-table.ts, packages/libraries/envelop/src/version.ts, packages/libraries/yoga/src/version.ts, packages/web/docs/src/pages/docs/api-reference/cli.mdx
Fixes https://github.com/graphql-hive/console/issues/3855
=> Add subgraphs type to cli schema:fetch

.changeset/grumpy-lemons-do.md, packages/web/app/src/server/slack.ts
Response validation of POST https://slack.com/api/oauth.v2.access
=> Ensure correct Slack API response format when connecting Slack to Hive

packages/libraries/cli/.gitignore
Progresses toward: https://github.com/graphql-hive/console/pull/6122
=> chore(cli): gitignore oclif manifest file

.vscode/settings.json
Progresses toward: https://github.com/graphql-hive/console/pull/6122
=> chore(vscode-settings): search exclude, prettier format

packages/libraries/cli/src/helpers/config.ts
=> refactor(cli): zod namespace

.github/actions/setup/action.yml, package.json, pnpm-lock.yaml
Progresses #6122 
It seems that the lock file changes.
=> chore: update pnpm to latest minor

.changeset/five-yaks-type.md, packages/services/api/src/modules/auth/lib/target-access-token-strategy.ts
Closes #6155 
I will try to add an e2e test on Monday
=> Fix missing access in the laboratory mocked endpoint

.github/workflows/tests-integration.yaml, integration-tests/testkit/cli-snapshot-serializer.ts, integration-tests/tests/cli/__snapshots__/schema.spec.ts.snap, integration-tests/tests/cli/schema.spec.ts
progresses #6122.
CLI output snapshots permit detecting unexpected changes as large changes are undertaken such as #6122.
=> tests(integration/cli): snapshot cli output

packages/libraries/cli/package.json
Follow up from https://github.com/graphql-hive/console/pull/6285/commits/eec01f7329d7ae8c6e9e851df8f81f4b359b4006#r1907959641
=> chore(cli): use prebuild script

packages/libraries/cli/package.json, packages/libraries/cli/src/helpers/typebox/_.ts, packages/libraries/cli/src/helpers/typebox/__.ts, packages/libraries/cli/src/helpers/typebox/formats/uri.ts, packages/libraries/cli/src/helpers/typebox/types/Nullable.ts, packages/libraries/cli/src/helpers/typebox/types/StringNonEmpty.ts, packages/libraries/cli/src/helpers/typebox/value/_.ts, packages/libraries/cli/src/helpers/typebox/value/__.ts, packages/libraries/cli/src/helpers/typebox/value/materialized-value-error.ts, packages/libraries/cli/src/helpers/typebox/value/parse-json.ts, pnpm-lock.yaml
Progresses #6122
This PR brings a changeset for a local Typebox lib (extending base one).
It will be used by future PRs that introduce JSON format output to the
CLI.
=> chore(cli): prepare typebox lib code

.eslintrc.cjs, packages/web/docs/src/components/community-section.tsx, packages/web/docs/src/components/company-testimonials/index.tsx, packages/web/docs/src/components/page.tsx, packages/web/docs/src/components/team-section/index.tsx
Switched my OS settings to always show scrollbars and styled them in Team, Community, and Testimonials sections.
=> Scrollbars and small CSS tweaks

deployment/utils/reverse-proxy.ts
A workaround for  https://github.com/bitnami/charts/issues/31352
As suggested in https://github.com/bitnami/charts/issues/31348#issuecomment-2589404332
=> Replace Bitnami proxy with GH raw url

packages/services/usage/src/index.ts, packages/services/usage/src/metrics.ts
This should help us understand the time spent in fastify vs time spent in the handler
=> Measure duration of the POST /usage request and time of execution of the handler

packages/web/docs/src/app/case-studies/(posts)/sound-xyz/page.mdx, packages/web/docs/src/app/case-studies/(posts)/wealthsimple/page.mdx
Update content for case studies
=> case study content

.changeset/giant-keys-kneel.md, packages/web/app/src/server/slack.ts
=> fix: slack connect error

.github/actions/setup/action.yml, .github/workflows/apollo-router-updater.yaml, .github/workflows/db-types-diff.yaml, .github/workflows/lint.yaml, .github/workflows/prettier.yaml, .github/workflows/publish-rust.yaml, .github/workflows/release-alpha.yaml, .github/workflows/release-stable.yaml, .github/workflows/storybook.yaml, .github/workflows/tests-db-migrations.yaml, .github/workflows/tests-e2e.yaml, .github/workflows/tests-integration.yaml, .github/workflows/tests-unit.yaml, .github/workflows/typescript-typecheck.yaml, .github/workflows/website.yaml
It's flakey sometimes and does not speed up things that much anyway.
=> Disable caching of Turbo in CI

.changeset/little-donuts-kiss.md, packages/libraries/core/src/client/collect-schema-coordinates.ts, packages/libraries/core/tests/collect-schema-coordinates.spec.ts, packages/libraries/core/tests/usage-collector.spec.ts, packages/libraries/router/src/graphql.rs
=> Collect custom scalars from arguments and input object fields

.changeset/spotty-pots-confess.md, cypress/e2e/app.cy.ts, packages/web/app/src/components/layouts/organization-selectors.tsx, packages/web/app/src/components/layouts/organization.tsx
=> Disable "select organization" dropdown for OIDC accounts

.changeset/cuddly-yaks-peel.md, cypress/e2e/laboratory-preflight-script.cy.ts, packages/web/app/package.json, packages/web/app/src/components/ui/collapsible.ts, packages/web/app/src/lib/preflight-sandbox/graphiql-plugin.tsx, packages/web/app/src/pages/target-laboratory.tsx, pnpm-lock.yaml
Closes #6229
https://github.com/user-attachments/assets/28148db9-f00e-40dc-b1d7-17a03959e91b
=> Show output of preflight script

.changeset/dry-news-db.md, .changeset/dry-news-join.md, packages/migrations/src/actions/2025.01.17T10-08-00.drop-activities.ts, packages/migrations/src/run-pg-migrations.ts, packages/services/storage/src/db/types.ts
=> Remove activity db leftovers

packages/web/docs/package.json, pnpm-lock.yaml
Same as in the title. We could use some cross-browser tests.
=> Update Components to fix lightning noodle bug in Firefox (again)

packages/services/service-common/src/fastify-tracing.ts, packages/services/usage/src/index.ts, pnpm-lock.yaml
=> Improvements to OTEL traces in usage

packages/services/api/src/modules/schema/providers/schema-manager.ts
=> fix: check uuid

packages/web/app/src/components/admin/AdminStats.tsx
This kicks off a bunch of expensive SQL queries.
=> fix: remove member selection for organization overview management

packages/web/docs/src/content/gateway/authorization-authentication.mdx
Fixed typo tokentokenLookupLocations
Small repetition typo in https://github.com/graphql-hive/console/blob/main/packages/web/docs/src/content/gateway/authorization-authentication.mdx#L81
=> Fixed typo

packages/web/docs/src/components/team-section/index.tsx
=> Add Jason to Team Section

.changeset/two-dryers-float.md, packages/libraries/core/src/client/http-client.ts, packages/libraries/core/src/client/utils.ts
=> fix: uuid generation on old Node.js

packages/web/docs/src/content/gateway/other-features/performance/index.mdx
Related https://github.com/graphql-hive/gateway/issues/576
=> docs(gateway): new Upstash Redis storage

packages/web/docs/src/content/gateway/usage-reporting.mdx
Adds all options Gateway has for GraphOS reporting feature
=> Update GraphOS integration docs

packages/services/cdn-worker/src/artifact-storage-reader.ts
- more insights
- do not abort if already aborted
=> More insights from S3 client when fetching from S3 and R2

packages/web/docs/src/app/gateway/cloud-native-section.tsx, packages/web/docs/src/app/gateway/lets-get-advanced-section.tsx, packages/web/docs/src/app/gateway/page.tsx
Added the Cloud Native Nature section. (screenshots on Slack)
=> Hive Gateway landing page: cloud native section

scripts/generate-changelog.js
=> Fix urls to product updates in Latest Changes component

packages/web/docs/src/content/gateway/other-features/security/hmac-signature.mdx
=> fix(docs) Fix HMAC Upstream Signature option gateway option name

packages/web/docs/src/content/gateway/other-features/performance/automatic-persisted-queries.mdx
Closes https://github.com/graphql-hive/gateway/issues/319
Completes GW-178
=> Docs/Gateway - Automatic Persisted Queries between subgraphs and GW

packages/web/docs/src/app/page.tsx
=> Update stats on landing page

.changeset/light-llamas-divide.md, packages/libraries/apollo/src/index.ts, pnpm-lock.yaml
This backports #4958 also for the legacy v3 of apollo.
Closes https://github.com/graphql-hive/console/pull/6560
=> fix: unhandled rejection in apollo plugin for apollo v3

packages/libraries/apollo/src/index.ts, packages/libraries/core/src/client/supergraph.ts, packages/libraries/core/src/client/utils.ts, packages/libraries/core/tests/supergraph.spec.ts
https://github.com/graphql-hive/console/issues/6359
Allow providing a custom `fetch` implementation to the supergraph manager and fetcher.
=> feat(sdk): allow providing a custom fetch implementation for the supergraph fetcher and manager

packages/web/docs/src/content/gateway/authorization-authentication.mdx, packages/web/docs/src/content/gateway/other-features/security/_meta.ts, packages/web/docs/src/content/gateway/other-features/security/aws-sigv4.mdx
Docs for https://github.com/graphql-hive/gateway/pull/746
Completes GW-198
=> Docs/Gateway: AWS Sigv4

packages/web/docs/src/content/gateway/other-features/security/aws-sigv4.mdx
Documentation of this PR https://github.com/graphql-hive/gateway/pull/782
Ref GW-237
=> Documentation: Incoming AWS Sigv4 validation

.changeset/curvy-mice-joke.md, configs/cargo/Cargo.lock, packages/libraries/router/src/usage.rs, packages/web/docs/src/content/other-integrations/apollo-router.mdx
=> feat(hive-apollo-router-plugin): support target id and org access token

packages/web/docs/src/app/product-updates/(posts)/2025-03-08-metadata/page.mdx
We recently added support for a `@link` to add meta data to subgraphs.
This product update announces this feature more widely.
=> docs: @meta product update

packages/services/server/README.md
=> docs: fix whitespace

.changeset/rotten-scissors-matter.md
Missed after doing adjustments for https://github.com/graphql-hive/console/pull/6585
=> adjust changeset

.changeset/neat-ladybugs-pay.md
=> chore: it is a breaking change

packages/web/docs/src/content/gateway/other-features/security/aws-sigv4.mdx
Fixes the example for JWT and Sigv4 usage
=> fix(gateway/docs): jwt and sigv4 usage

.changeset/lazy-guests-leave.md, packages/services/usage-ingestor/src/ingestor.ts
Recover when it successfully fetches messages from the broker.
Closes CONSOLE-1129
=> Mark usage-ingestor as unhealthy when consumer crashes

.github/workflows/main.yaml
Reverts graphql-hive/console#6546
=> Revert "chore: temporarily disable auto-deployments to staging"

configs/cargo/Cargo.lock, package.json, pnpm-lock.yaml
=> chore(security): cve cleanup

pnpm-lock.yaml
completes CONSOLE-1139
completes CONSOLE-1140
=> chore(security): another cycle of cves

packages/web/app/src/components/organization/settings/access-tokens/access-tokens-sub-page.tsx
=> fix(app): use correct link in docs

.changeset/honest-numbers-heal.md, packages/libraries/cli/package.json, packages/services/api/package.json, packages/services/schema/package.json, pnpm-lock.yaml
https://github.com/graphql-hive/federation-composition/pull/87
=> fix: bump @theguild/federation-composition

packages/web/docs/src/content/gateway/other-features/security/_meta.ts, packages/web/docs/src/content/gateway/other-features/security/block-field-suggestions.mdx, packages/web/docs/src/content/gateway/other-features/security/character-limit.mdx, packages/web/docs/src/content/gateway/other-features/security/disable-introspection.mdx, packages/web/docs/src/content/gateway/other-features/security/index.mdx, packages/web/docs/src/content/gateway/other-features/security/max-depth.mdx, packages/web/docs/src/content/gateway/other-features/security/max-tokens.mdx, packages/web/docs/src/content/gateway/other-features/security/rate-limiting.mdx
Merge after https://github.com/graphql-hive/gateway/pull/871.
Contains some additional cleanup, improvements and fixes around gateway security.
=> Introduce built-in armor security features

.github/workflows/release-stable.yaml
=> chore: permissions to create pr

.changeset/proud-balloons-yell.md, packages/libraries/cli/package.json, packages/services/api/package.json, packages/services/schema/package.json, pnpm-lock.yaml
=> feat: upgrade `@theguild/federation-composition` to `0.15.0`

package.json
Reverts graphql-hive/console#6646
=> Revert "chore(deps): update pnpm to v10.6.5"

.changeset/tidy-singers-double.md, integration-tests/tests/cli/__snapshots__/schema.spec.ts.snap, integration-tests/tests/cli/schema.spec.ts, packages/services/api/src/modules/schema/providers/models/composite.ts
Resolves #6659 , Ref CONSOLE-1169 
Defaults to previously published url instead of erroring.
=> Publish url optional

integration-tests/package.json, package.json, pnpm-lock.yaml
Fixes https://github.com/graphql-hive/console/security/dependabot/290
=> fix(deps): tar-fs cve

packages/services/server/src/use-armor.ts
=> Bump maximum query depth to 22

packages/services/api/src/modules/schema/providers/schema-publisher.ts
https://github.com/graphql-hive/console/pull/6683
=> fix: retain url with next schema log if omitted during publish

.changeset/plenty-apes-hug.md, packages/services/api/src/modules/schema/providers/schema-publisher.ts
Closes https://github.com/graphql-hive/console/issues/6696
=> show dangerous changes as separate list

.changeset/wicked-flowers-bake.md, integration-tests/tests/schema/contracts.spec.ts, packages/services/schema/src/lib/federation-tag-extraction.spec.ts, packages/services/schema/src/lib/federation-tag-extraction.ts
=> fix(schema): building contracts with extend keyword

packages/services/api/src/modules/project/module.graphql.ts
=> feat(server): add `ProjectType` to the public API

packages/libraries/router/src/agent.rs, packages/libraries/router/src/graphql.rs, packages/libraries/router/src/persisted_documents.rs, packages/libraries/router/src/registry.rs, packages/libraries/router/src/usage.rs
fix some warnings found by clippy
=> fix some clippy warnings

.changeset/green-boats-begin.md, packages/services/schema/src/lib/metadata-extraction.ts
References https://github.com/graphql-hive/console/issues/6700
Adjusts the metadata collecting logic to only store if there is metadata.
=> No empty metadata

packages/web/docs/src/content/gateway/deployment/node-frameworks/fastify.mdx, packages/web/docs/src/content/gateway/logging-and-error-handling.mdx
Documentation of https://github.com/graphql-hive/gateway/pull/946
Related GW-270
=> Better Fastify and Pino integration

packages/services/schema/src/orchestrators.ts
We are investigating an issue where the TRPC request to composeAndValidate schemas is hanging.
https://theguild.zendesk.com/agent/tickets/371
This PR adds more debug logs to the composition flow to better identify where the issue is taking place in production.
=> Add debug logs to federation composition

deployment/services/redis.ts
=> chore: increase redis memory

packages/libraries/core/package.json, packages/libraries/yoga/package.json, packages/migrations/package.json, packages/services/broker-worker/package.json, packages/services/cdn-worker/package.json, packages/services/external-composition/federation-2/package.json, packages/services/server/package.json, pnpm-lock.yaml
=> fix: bump whatwg-node packages

deployment/config/public-graphql-api-gateway/gateway.config.ts, deployment/index.ts, deployment/services/proxy.ts, deployment/services/public-graphql-api-gateway.ts
Use Hive Gateway as the entry-point for the private API endpoint.
=> chore: hive gateway as entrypoint for the public api

deployment/services/redis.ts, deployment/services/schema.ts, deployment/utils/redis.ts
=> feat(schema): cache adjustments

deployment/grafana-dashboards/Schema-Service.json, packages/services/schema/src/cache.ts, packages/services/schema/src/composition-scheduler.ts, packages/services/schema/src/metrics.ts
=> feat: some more metrics on the schema service

packages/web/docs/src/content/gateway/other-features/performance/deduplicate-request.mdx
=> useDeduplicateRequest is the Hive Gateway plugin name

packages/services/broker-worker/src/handler.ts
=> Add User-Agent to the requests made by broker-worker

packages/services/schema/src/composition/__tests__/federation.spec.ts, packages/services/schema/src/composition/federation.ts, packages/services/schema/src/lib/__tests__/federation-tag-extraction.spec.ts, packages/services/schema/src/lib/compose.ts
Adds additional test cases for https://github.com/graphql-hive/console/pull/6770 to see if the "whole" composition output is legit.
=> test: contract composition

.changeset/lemon-lies-carry.md, integration-tests/testkit/flow.ts, integration-tests/testkit/seed.ts, integration-tests/tests/api/project/crud.spec.ts, packages/services/api/src/modules/organization/lib/organization-access-token-permissions.ts, packages/services/api/src/modules/project/module.graphql.ts, packages/services/api/src/modules/project/providers/project-manager.ts, packages/services/api/src/modules/project/resolvers/Mutation/createProject.ts, packages/services/api/src/modules/project/resolvers/Mutation/deleteProject.ts, packages/services/api/src/modules/project/resolvers/Mutation/updateProjectSlug.ts, packages/services/api/src/modules/shared/providers/storage.ts, packages/web/app/src/components/layouts/organization.tsx, packages/web/app/src/lib/urql-cache.ts, packages/web/app/src/pages/project-settings.tsx
=> feat(api): add project mutations to public api schema

integration-tests/testkit/seed.ts
=> fix: types

packages/services/api/src/modules/schema/module.graphql.ts
=> feat: make schema version pagination arguments public

.changeset/fast-trees-call.md, integration-tests/tests/api/schema/contracts-check.spec.ts, integration-tests/tests/api/schema/contracts-publish.spec.ts, integration-tests/tests/api/target/contracts.spec.ts, packages/services/api/src/modules/schema/module.graphql.ts, packages/services/api/src/modules/schema/providers/contracts-manager.ts, packages/services/api/src/modules/schema/resolvers/Mutation/createContract.ts, packages/services/api/src/modules/schema/resolvers/Mutation/disableContract.ts, packages/web/app/src/components/target/settings/schema-contracts.tsx
=> feat(api): manage contracts via public api

integration-tests/testkit/flow.ts, integration-tests/tests/api/target/usage.spec.ts, packages/services/api/src/modules/operations/module.graphql.ts, packages/services/api/src/modules/operations/providers/operations-manager.ts, packages/services/api/src/modules/operations/providers/operations-reader.ts, packages/services/api/src/modules/operations/resolvers/SchemaChangeUsageStatisticsAffectedOperation.ts, packages/services/api/src/modules/organization/lib/organization-access-token-permissions.ts, packages/services/api/src/modules/schema/module.graphql.mappers.ts, packages/services/api/src/modules/schema/providers/breaking-schema-changes-helper.ts, packages/services/api/src/modules/schema/providers/contracts-manager.ts, packages/services/api/src/modules/schema/providers/schema-manager.ts, packages/services/api/src/modules/schema/resolvers/SchemaChangeUsageStatisticsAffectedOperation.ts, packages/web/app/src/pages/target-insights-operation.tsx
=> feat(api): add `OperationStatsValues.name` and `OperationStatsValues,operationHash` to the public api schema

packages/web/docs/src/components/frequently-asked-questions/home-questions.mdx
=> chore(faq): fix typo in the faq

packages/services/api/src/modules/organization/module.graphql.ts, packages/web/docs/src/content/_meta.ts, packages/web/docs/src/content/graphql-api/_meta.ts, packages/web/docs/src/content/graphql-api/access-token-management.mdx, packages/web/docs/src/content/graphql-api/contract-management.mdx, packages/web/docs/src/content/graphql-api/index.mdx, packages/web/docs/src/content/graphql-api/member-management.mdx, packages/web/docs/src/content/graphql-api/project-management.mdx, packages/web/docs/src/content/graphql-api/target-management.mdx
Adds some basic information and example operations for interacting with the GraphQL API. This could be more detailed etc. but for the beginning it is enough. We can improve it further as people ask questions.
This information will exist here temporarily, as this kind of information should later on exists within our [polen developer portal](https://github.com/the-guild-org/polen) (cc @jasonkuhrt). While writing the docs I already had [some ideas that could lead to features within polen](https://github.com/the-guild-org/polen/issues/22#issuecomment-2900841027).
=> docs: public graphql api documentation

packages/web/app/package.json, packages/web/app/src/components/layouts/target.tsx, packages/web/app/src/components/ui/input-copy.tsx, packages/web/app/src/components/ui/textarea.tsx, pnpm-lock.yaml
Improves the readability of the commands and fixes the copy input to always copy the latest value.
**Before:**
**After:**
**Before:**
**After:**
=> fix(app): connect to cdn modal instructions

packages/web/docs/src/content/gateway/other-features/performance/index.mdx
Related GW-386
Blocked by https://github.com/ardatan/graphql-mesh/pull/8651
=> Documentation for Redis Cluster Support

.changeset/plenty-clouds-obey.md, integration-tests/package.json, packages/libraries/cli/package.json, packages/services/api/package.json, packages/services/schema/package.json, pnpm-lock.yaml
Closes https://github.com/graphql-hive/console/issues/6840
=> bump `@theguild/federation-composition`

.changeset/tender-rings-explode.md, packages/services/api/src/modules/schema/providers/schema-publisher.ts
Reference: https://theguild.zendesk.com/agent/tickets/393
=> fix: include "safe based on usage" within github checkrun summary

.changeset/sharp-llamas-play.md, packages/services/api/src/modules/organization/lib/organization-access-token-permissions.ts
=> fix(api): create project permission

packages/web/docs/package.json, packages/web/docs/src/app/layout.tsx, packages/web/docs/src/components/frequently-asked-questions/home-questions.mdx, pnpm-lock.yaml
=> Add SOC-2 badge to the footer

packages/web/docs/src/components/pricing/plans-table.tsx
Take note that this is gonna look off if Pro gets renamed to Premium and Enterprise to Biz.
=> align columns in the pricing table

packages/web/docs/src/content/gateway/persisted-documents.mdx
=> Fix h-levels and correct the line highlighted in the code block

packages/web/docs/src/content/gateway/other-features/security/aws-sigv4.mdx
Documentation for https://github.com/graphql-hive/gateway/pull/1368
=> Documentation for AWS Credentials Providers support

packages/web/docs/src/app/blog/(posts)/welcome-hive-router/components.tsx
=> Fix light mode

.changeset/fuzzy-kiwis-crash.md, packages/web/app/src/components/target/settings/cdn-access-tokens.tsx
pressing enter did close the form, now it just submits the form.
=> fix(dashboard): registry access tokens usability

deployment/index.ts, deployment/services/cf-broker.ts, deployment/services/cf-cdn.ts, deployment/services/cloudflare-security.ts, deployment/utils/reverse-proxy.ts
goes along with https://github.com/graphql-hive/deployment/pull/1495
=> standalone domains for dev/staging

docker/docker-compose.community.yml, docker/docker-compose.dev.yml
closes https://github.com/graphql-hive/console/issues/7015
=> use `bitnamilegacy/redis:7.4.2`

deployment/services/environment.ts
=> adjust resources and pods/replicas count in staging+prod

packages/services/service-common/src/fastify.ts
https://theguild.zendesk.com/agent/tickets/414
=> increase default http body limit size

.changeset/wicked-rooms-mate.md, packages/web/app/src/components/project/settings/apollo-composition.tsx, packages/web/app/src/components/project/settings/composition.tsx, packages/web/app/src/components/project/settings/external-composition.tsx, packages/web/app/src/components/project/settings/legacy-composition.tsx, packages/web/app/src/components/project/settings/native-composition.tsx, packages/web/app/src/pages/project-settings.tsx
Closes #7020
The schema composition settings UI didn't reflect the mutual exclusiveness of native/external/Apollo composition modes. This was both hard to use and understand.
<details>
<summary>Screenshots</summary>
</details>
Combines the composition settings as a single card, separated into tabs. Enabling one mode automatically disables others.
The current implementation involves client-side waterfalls: one mutation for updating the native composition status and another for updating the external composition status. In the long run, we could unify these as a single mutation, possibly using `@oneOf` to express the mutual exclusiveness of each mode.
=> feat(app): refine schema composition settings UI

packages/web/docs/src/content/migration-guides/gateway-v1-v2.mdx
Edit diff for loggers to make visible, that Logger is also newly imported
=> Edit diff for logger

.eslintrc.cjs, packages/web/app/src/components/admin/AdminStats.tsx, packages/web/app/src/components/target/history/errors-and-changes.tsx, packages/web/app/src/components/target/insights/Filters.tsx, packages/web/app/src/components/target/settings/cdn-access-tokens.tsx, packages/web/app/src/pages/target-checks.tsx, packages/web/app/src/pages/target.tsx
We have runtime errors. We can avoid these easily with this!
=> chore: enable rule of hooks
